### ISSUE TITLE
Add the ability to set a data retention policy to trace data

### ISSUE THREAD

**Issue by ramonguiu** [timescale/promscale#1006]
### Problem
Currently there are not retention policies enforced on tracing data. As a result, users could fill their disk space with tracing data without knowing.

### Solution
We want to provide users the ability to configure retention for tracing data and ensure that retention is applied when the maintenance job is executed.

We will add a new SQL function

```
set_span_retention_period(new_retention_period interval)
```

The default retention period for spans will be set to 30 days.

**Considerations**
As a result of this, some of the oldest traces may be incomplete in the database (some spans of a trace have been deleted). This is an acceptable tradeoff to ensure applying the retention policy is fast.

**Comment by jgpruitt** [comment]
- [ ] look at how `add_retention_policy()` works
- [ ] look at how `remove_retention_policy()` works
- [ ] look at how `drop_chunks()` works

**Comment by jgpruitt** [comment]
- [ ] create `drop_trace_chunks()` procedure
- [ ] create `execute_data_retention_policy()` procedure

**Comment by jgpruitt** [comment]
@ramonguiu do we want the users to be able to disable data retention for tracing, and if so, how? Perhaps, a special value passed (e.g. null) to `set_span_retention_period()`? Thoughts?

**Comment by ramonguiu** [comment]
@jgpruitt I don't think we should allow users to completely disable retention. They could always set it way into the future but we should force users to define how long they want to retain the data. Do we allow users to set infinite retention for metrics at the moment?

**Comment by jgpruitt** [comment]
@ramonguiu I don't think we make it "easy" for users to disable retention for metrics, but unless I'm missing something you could achieve it by setting a negative retention period on the metric, or leaving the metric retention period null and setting a negative default retention period. cc @cevian
