### ISSUE TITLE
Add the ability to delete trace data

### ISSUE THREAD

**Issue by ramonguiu** [timescale/promscale#1007]
### Problem
Currently there is no easy way to delete trace data. A user may have done a test and may want to drop their trace data to remove test data or because they have decided to stop using tracing altogether and they don't want the trace data to consume space on disk.

### Solution
We want to offer users the ability to delete trace data. 
We will add a new SQL function
```
delete_span_data()
```
which will delete all trace data (spans, links, events, tags, etc.).

**Comment by jgpruitt** [comment]
@ramonguiu just to confirm: you want this function to delete all the data for ALL the traces leaving completely empty tables?

**Comment by ramonguiu** [comment]
@jgpruitt yes, correct. The reason behind is that if for some reason someone using Promscale for metrics enables tracing and quickly realizes they are filling their disk, they have an easy way to drop the trace data to free up space for their metrics.

One question I have is how expensive this operation is.

Additionally thing to review is whether the name should be delete_span_data() or something else like delete_spans() or delete_all_spans(). Now I think delete_spans() is better and in the future if there is a need it could take parameters so it only deletes certain data.

We currently have a function names drop_metric in prom_api to drop a single metric from the database. So maybe using drop instead of delete would be better to be consistent. I personally prefer delete to drop. It's more universal and drop in databases also deletes table structures (when dropping a table).

**Comment by jgpruitt** [comment]
@ramonguiu in the case where we want to remove ALL the data, we can use `TRUNCATE` which is much more efficient than `DELETE`. `TRUNCATE` effectively just deletes the data files off the disk.

If we later want a version that lets you delete a subset of data, I'd probably overload the function and have it do `DELETE` leaving the original to use `TRUNCATE`.

**Comment by jgpruitt** [comment]
I'll name the function `delete_spans()`

**Comment by ramonguiu** [comment]
It doesn't concern me now. If at some point we reuse the same tags table for other telemetry types then we will need to be careful with that.

Do you think delete_spans would be confusing to developers and it would be better to use another name like delete_traces or delete_trace_data? A span technically includes all the other data that we will delete even though we've modelled it as multiple tables.

@cevian do you have any preference on how we name this function?

**Comment by jgpruitt** [comment]
I'm not sure. `delete_spans` just feels a little to benign for what it does. `nuke_all_your_tracing_data_be_careful_are_you_sure` is maybe too much ;) but something that conveys the gravity of what's about to happen?

**Comment by cevian** [comment]
My preference
1) truncate_traces()
2) delete_all_traces()
3) delete_all_spans()

**Comment by ramonguiu** [comment]
Ok. Truncate sounds very specific to database terminology in my opinion which not everybody may be familiar with.
Let's go with delete_all_traces() then.

**Comment by ramonguiu** [comment]
We'll need to add documentation for these in https://github.com/timescale/promscale/blob/master/docs/cli.md and https://github.com/timescale/promscale/blob/master/docs/tracing.md. For the latter I would add a new section "Manage your traces in Promscale" after the "Ingest Traces into Promscale" section and would explain how retention works and how to delete trace data. @jgpruitt is that something you could do?

**Comment by jgpruitt** [comment]
Will do!

**Comment by jgpruitt** [comment]
@ramonguiu what documentation needs to be added to the `cli` doc? To my knowledge there isn't anything relevant in there.

**Comment by JamesGuthrie** [comment]
@jgpruitt perhaps it should be added to this: https://github.com/timescale/promscale/blob/master/docs/dataset.md

**Comment by jgpruitt** [comment]
I'll check that out. Thanks
