### ISSUE TITLE
add_prom_node(unknown) is a procedure

### ISSUE THREAD

**Issue by a517363523** [timescale/promscale#1010]
use promscale  version 0.7.1,distributed hypertable not create,It's only create hypertable

**Comment by ramonguiu** [comment]
@a517363523 could you provide more details on your issue? I assume you are using a TimescaleDB multi-node setup and following [these instructions](https://github.com/timescale/promscale/blob/4330f6ce02dd2f9c1f66b23cc8e2fe6de428661c/docs/multinode.md) but I don't understand what is the issue you are having.

**Comment by a517363523** [comment]
> @a517363523你能提供更多关于你的问题的细节吗？我假设您正在使用 TimescaleDB 多节点设置并遵循[这些说明，](https://github.com/timescale/promscale/blob/4330f6ce02dd2f9c1f66b23cc8e2fe6de428661c/docs/multinode.md)但我不明白您遇到了什么问题。

**Comment by a517363523** [comment]
> @a517363523 could you provide more details on your issue? I assume you are using a TimescaleDB multi-node setup and following [these instructions](https://github.com/timescale/promscale/blob/4330f6ce02dd2f9c1f66b23cc8e2fe6de428661c/docs/multinode.md) but I don't understand what is the issue you are having.

I  addnodes to a TimescaleDB cluster that is already being written to by Promscale,
when I execute the add_prom_node command，It's return error

![image](https://user-images.githubusercontent.com/62454956/148354798-aa9bcc37-0127-40cb-a36f-9783210e6a74.png)

**Comment by VineethReddy02** [comment]
cc @cevian

**Comment by JamesGuthrie** [comment]
It seems as though this is just a documentation issue, `add_prom_node` is a procedure, not a function, so it can't be invoked with `SELECT`, instead it must be invoked with `CALL`. I've opened a PR addressing this.
