### ISSUE TITLE
Add headers support in Prom-migrator

### ISSUE THREAD

**Issue by VineethReddy02** [timescale/promscale#1020]
In prom-migrator add support for headers to writer URL, helps in configuring tenant and auth-related details through headers. 

```
./prom-migrator_0.0.3_Linux_x86_64 -start=1641486391
-reader-url=http://x.x.x.x:portnumber/prom/api/v1/read
-writer-url=http://y.y.y.y:portnumber/write -progress-enabled=false
**--headers="TENANT=<>"**
```

**Comment by jontran57** [comment]
Hello @VineethReddy02  and prom-migrator team,

Please let me know if this can be done ASAP so that we can try it out on our system.  Appreciate it.  What would be the timeline?

Thanks,
Jon

**Comment by VineethReddy02** [comment]
@jontran57 team is currently occupied with other priorities. We currently cannot get this fixed asap. It will take another release cycle for this to get fixed.

**Comment by jontran57** [comment]
@VineethReddy02 How long is the release cycle at Timescale?  Do you have the approximate date so I get the idea?

Thanks,
Jon

**Comment by VineethReddy02** [comment]
We do have any changes to the prom-migrator at the moment we are doing only the Promscale release this week. The prom-migrator release will be approximately 4 weeks from now. 

Btw can I understand the use-case with headers you are trying to achieve what is the source and destination that you are trying to migrate data from using prom-migrator?

**Comment by umakarnati** [comment]
Hi @VineethReddy02 ..   I am also facing this issue ..    my use-case is to migrate the data from cortex to victoria-metrics..
when I am trying to read the data from cortex  I am facing "returned HTTP status 401 Unauthorized: no org id".    as cortex expects tenant ID  in the header..   here is command I tried for getting the data from cortex to vm using prom-migrator 

 ```
docker run -it timescale/prom-migrator -start=1659395966 \
 -reader-url=http://host.docker.internal:8080/prometheus/api/v1/read \
 -reader-auth-username=metrics \
 -writer-url=http://host.docker.internal:8480/insert/1234/prometheus/api/v1/write  \
 -progress-enabled=false 

```
