### ISSUE TITLE
Expose state of connection pooling through metrics

### ISSUE THREAD

**Issue by VineethReddy02** [timescale/promscale#1023]
In Promscale we are not exposing any details on database connection pooling. This issue is to expose details of the runtime state of DB connections being used.

**Comment by paulfantom** [comment]
IMHO we need a broader overhaul of metrics exposed by promscale. Current ones are not easily understandable and sometimes violate best practices. I tried to gather all changes in https://docs.google.com/document/d/1Eff08z17Rssk5xz1YDAwXnxe9bVa0seEn_e0jLivExI/edit?usp=sharing so we can overhaul it in one sweep or start going towards a common goal.
