### ISSUE TITLE
[Feature Request] Add tablespace configuration options

### ISSUE THREAD

**Issue by tylerfontaine** [timescale/promscale#103]
https://github.com/timescale/timescale-prometheus/blob/master/docs/sql_api.md offers quite a few configuration options that one normally has for hypertable management, but tablespaces are missing.

Would be great if we could add tablespace configs via this API as well.

**Comment by VineethReddy02** [comment]
closing this request, As this doesn't align with the current roadmap of Promscale. Today Promscale has evolved to manage all database-specific logic using the Promscale extension.

However feel free to re-open the issue, If you think we should re-consider this request.
