### ISSUE TITLE
upgrade from 0.6.2 to 0.7.1 brake inserts

### ISSUE THREAD

**Issue by nbari** [timescale/promscale#1054]
I upgraded from `0.6.2` and postgres 13 to `0.7.1` and postrgres 14, but I can only read data, no inserts, in the postgres error logs regarding  `violates check constraint`, like:

```
 app=promscale@0.7.1, line=4 ERROR: new row for relation "node_exec_software_interrupts_total" violates check constraint "node_exec_software_interrupts_total_labels_check"
 app=promscale@0.7.1, line=4 ERROR: new row for relation "node_timex_pps_stability_hertz" violates check constraint "node_timex_pps_stability_hertz_labels_check"
 app=promscale@0.7.1, line=4 ERROR: new row for relation "go_memstats_heap_sys_bytes" violates check constraint "go_memstats_heap_sys_bytes_labels_check"
 app=promscale@0.7.1, line=4 ERROR: new row for relation "go_gc_duration_seconds" violates check constraint "go_gc_duration_seconds_labels_check"
 app=promscale@0.7.1, line=4 ERROR: new row for relation "go_memstats_heap_released_bytes" violates check constraint "go_memstats_heap_released_bytes_labels_check"
 app=promscale@0.7.1, line=4 ERROR: new row for relation "go_gc_duration_seconds_count" violates check constraint "go_gc_duration_seconds_count_labels_check"
 app=promscale@0.7.1, line=4 ERROR: new row for relation "go_memstats_heap_inuse_bytes" violates check constraint "go_memstats_heap_inuse_bytes_labels_check"
 app=promscale@0.7.1, line=4 ERROR: new row for relation "go_info" violates check constraint "go_info_labels_check"
```

Any ideas about how to fix this without deleting/dropping existing data?

I am using `Prometheus` ---> `promscale` ---> `timescale`

**Comment by jgpruitt** [comment]
@nbari in psql, please do `\d node_exec_software_interrupts_total` and copy the output here. The constraints that are being violated ensure the first entry in the `labels` array is the `label_id` corresponding to the name of the metric. I am wondering whether the ids referenced in the check constraint definitions still match the correct ids in the label table.

**Comment by nbari** [comment]
hi @jgpruitt here is the output:

```
promscale=# \d node_exec_software_interrupts_total
         View "prom_metric.node_exec_software_interrupts_total"
   Column    |           Type           | Collation | Nullable | Default
-------------+--------------------------+-----------+----------+---------
 time        | timestamp with time zone |           |          |
 value       | double precision         |           |          |
 series_id   | bigint                   |           |          |
 labels      | label_array              |           |          |
 instance_id | integer                  |           |          |
 job_id      | integer                  |           |          |
 node_id     | integer                  |           |          |
```

**Comment by ramonguiu** [comment]
@nbari is this from the current database or the one that was exhibiting the issue?

**Comment by nbari** [comment]
hi @ramonguiu the one having the issue, but the output is the same for both.

**Comment by VineethReddy02** [comment]
@nbari is this issue still relevant?

**Comment by nbari** [comment]
Hi @VineethReddy02 I would say that needs further tests (not production-ready yet) hopefully future versions will consider this but I think gives you the opportunity to increment your set of tests and consider these scenarios for new releases. From my side, this interrupted the ingestion of data and made me split the databases, (old data, new data) nothing critical but definitely not something you want to have in a prod environment.

**Comment by VineethReddy02** [comment]
@nbari Ideally the upgrade path shouldn't cause such issues. To be clear this was the release when we experimented with split releases as we had tracing beta support in Promscale during these releases. 

Now the upgrade paths are better handled and these cases are more aware to the team now! So we are positive that this shouldn't reoccur during the upgrades. 

closing this issue for now. But feel free to re-open in the future if you face any issues with Promscale upgrades. 

Thanks!
