### ISSUE TITLE
Better clarification for promscale metrics

### ISSUE THREAD

**Issue by Harkishen-Singh** [timescale/promscale#1058]
Some Prometheus metrics in promscale like `promscale_executed_queries_total` are generic. Even though it considers only promql queries, the naming leads to confusion of metrics + traces + SQL queries are being considered. Some metrics like this can be fixed by adding subsystem `Subsystem: "metrics"`.

We should investigate and fix such confusing metrics.

**Comment by paulfantom** [comment]
Partially related to https://github.com/timescale/promscale/issues/825.
Part of https://github.com/timescale/o11y-eng-private/issues/57
