### ISSUE TITLE
ipv4

### ISSUE THREAD

**Issue by peter-miroshnikov** [timescale/promscale#1064]
Hello,
I cant find any documentation about ipv4 vs ipv6.

I want to be able to use ipv4 to connect to my db but it seems that by default everything is setup to use ipv6.
I tried the docs, i tried previous issues but there is no information.

Because of limitations in Azure for basic Tier databases i cant configure them to use ipv6 so i need ipv4.

**Comment by ramonguiu** [comment]
@peter-miroshnikov could you provide more details of where you are forced to use ipv4? An example of the configuration or parameters you want to use would help.

**Comment by peter-miroshnikov** [comment]
I am sorry, it turns out that its an azure limitation.

If i am using timescale db on a `basic tier` Postgres `single-server instance` and I have configured my subnet with a service endpoint to  Microsoft.SQL (Which seemed to be the recommended way to do it from microsoft) i get an error that my postgres server is not configured to use IPV6.

After spending some time researching random places on the net i removed the Service Endpoint for Mirosoft.SQL i no longer get the error and the connection works.


The issue was between Promscale installed inside my k8s cluster and a managed Postgres Instance

**Comment by JamesGuthrie** [comment]
Thanks for the update @peter-miroshnikov. I'm glad that you got it working in the end!
