### ISSUE TITLE
flag provided but not defined: -high-availability

### ISSUE THREAD

**Issue by garlickim** [timescale/promscale#1073]
I upgraded promscale from 0.7.1 to 0.8 version.

it occured "flag provided but not defined: -high-availability" error..

The document(docs/high-availability/prometheus-HA.md) say 
> After Prometheus instances are configured to send the correct labels, Promscale simply needs to be started with the -high-availability CLI flag. Internally, Promscale will elect a single replica per cluster to be the current leader. Only data sent from that replica will be ingested. If that leader-replica stops sending data, then a new replica will be elected as the leader.

But I saw the history of code. I found changes.
If I use v0.8 of promscale, I have to change command from "-high-availability" to "-metrics.high-availability".

if i wasn't wrong, plz update the doc.

**Comment by antekresic** [comment]
Hi there. Thank you for letting us know! 

I've updated the doc and add an alias for the old flag (which is deprecated but should have still been supported until removal).

Thanks again!
