### ISSUE TITLE
Log the deprecated labels

### ISSUE THREAD

**Issue by VineethReddy02** [timescale/promscale#1114]
Log the depcrecated flags that are in use, stating in `0.X.0` (tbd) version will drop these flags.

**Comment by hvulin** [comment]
we are using ENV variables to configure promscale (0.10.0) but it's still complaining that we are using obsolete options.... so this isn't really fixed

**Comment by antekresic** [comment]
Hey @hvulin thanks for reporting this.

I'll take this on and make sure the issue is addressed for the future version. 

Thanks again!
