### ISSUE TITLE
how to change the interval for execute_maintenance_job

### ISSUE THREAD

**Issue by garlickim** [timescale/promscale#1138]
Hi, I use timescale 2.x and promscale 0.9 version.

In table of timescaledb_information.jobs, I saw "User-Defined Action[XXXX]" schedules.
I think that when promscale initializes, it seems to create two schedule(User-Defind Action ==> execute_maintenance_job).
The schedules has 30 mins interval.

I want to change the interval on initialize. But I can not manual for it.. 

And does the number of schedulers affect compression as well?
(I think yes,, so I also know how to increase the schedule on initialize. or after init)

**Comment by VineethReddy02** [comment]
More schedulers performing the compressor jobs will definitely result in high CPU usage. The general recommendation is to perform maintenance jobs every 30 mins from Promscale end. 

However, you can use this SQL cmd to add new maintenance job with the desired interval
```
PERFORM public.add_job('_prom_catalog.execute_maintenance_job', '30 min');
```

**Comment by VineethReddy02** [comment]
Closing this issue, As its a question and relevant details are already shared. Feel free to re-open the issue, if you still have questions around the change interval to `execute_miantenance_job`
