### ISSUE TITLE
FEATURE REQUEST: Having adapter import data that wasn't imported due to database being down

### ISSUE THREAD

**Issue by Atomicbeast101** [timescale/promscale#116]
I believe having a feature that allows the adapter to temporarily store metric data while it's unable to connect to the database and have it import that data once it reconnects back to the database. This would help for those who needs to perform maintenance to the database (ie upgrading PostgreSQL from v11 to v12 & migrating data to work with v12) without having to worry about losing data during the maintenance window.

This should also apply to multi-prometheus setups too.

I'm curious to hear what you guys think of this.

**Comment by Atomicbeast101** [comment]
@cevian Does Prometheus actually call the adapter after DB is back up and running to import the missing data?

**Comment by cevian** [comment]
So prometheus should retry the adapter indefinitely on recoverable errors https://github.com/prometheus/prometheus/blob/master/storage/remote/queue_manager.go#L839

All http 5XX errors are recoverable (https://github.com/prometheus/prometheus/blob/master/storage/remote/client.go#L147) so as long as the connector returns 500s when the DB is down (which it should), prometheus should retry with backoff logic. 

For this to work, Prometheus queues need to be configured correctly. Namely, the `capacity` parameter here: https://prometheus.io/docs/practices/remote_write/ needs to be able to absorb downtime to avoid blocking prometheus scrapes. But, I think implementing this in the connector would have to make the same tradeoffs.

**Comment by Atomicbeast101** [comment]
Is there a recommendation on how to properly tune the remote write for PostgreSQL database? This guide explains the different options for tuning the remote write system, however it mentioned that it should be tuned to work well with specific database sources: https://prometheus.io/docs/practices/remote_write/

**Comment by cevian** [comment]
moved to new issue #366
