### ISSUE TITLE
Drop tracing enabling flags, enable tracing by default

### ISSUE THREAD

**Issue by VineethReddy02** [timescale/promscale#1175]
Currently, Promscale requires additional flags to enable tracing. With tracing GA the tracing option should be enabled by default. This requires

1. OTLP endpoint enabled by default
2. Remove tracing from beta features flag

i.e. OTLP endpoint should be by default enabled with port `:9202` and using this feature shouldn'trequire `--enable-beta-feature=tracing` option. 

**Open Question**: Should we drop these drop flags or deprecate them?

**Comment by antekresic** [comment]
I'd say deprecate the enable-feature flag with logging that tracing is enabled by default. The OTLP flag should remain and will be always on.

**Comment by antekresic** [comment]
Done with https://github.com/timescale/promscale/pull/1213
