### ISSUE TITLE
Option to turn off Prometheus/OpenTelemetry

### ISSUE THREAD

**Issue by VineethReddy02** [timescale/promscale#1183]
Currently, The Prometheus endpoint is by default enabled, and post tracing GA OpenTelmetry will be also enabled by default. 

Provide an option i.e. flag, config option (in config.yaml) to disable to Prometheus, OpenTelemetry. If a user wants to use Promscale only for tracing not for metrics and vice versa. This option helps to disable the unused endpoint. 

**Note**: Expose Promscale metrics in the server that is running, currently we are exposing metrics only in `9201`.

Dependent task:

1. Expose metrics in port that's enabled: Expose Promscale metrics from the port which is enabled i.e. we should expose metrics from `9202` if only otel is enabled, in `9201` if only metrics is enabled and in `9201` as default if both are enabled.

**Comment by antekresic** [comment]
Blocked by #1213

**Comment by VineethReddy02** [comment]
We decided not to implement this at the moment. As Promscale will expose metrics in default HTTP server i.e. `9201`. So the option of turning off Prometheus under the hood means turning off the HTTP server. This isn't ideal UX.
