### ISSUE TITLE
Promscale fails to start with error: could not acquire schema version lease. is a migration in progress?

### ISSUE THREAD

**Issue by enidvrenozaj** [timescale/promscale#1190]
Hi,
Recently I updated my timescaledb+promscale packages from:
```
promscale_0.3.0_Linux_x86_64
postgresql_version: 12.6-1.pgdg100+1
timescaledb_version: 2.2.0~debian10
promscale_extension: 0.1.1
```

to
```
promscale_0.10.0_Linux_x86_64
postgresql_version: 12.10-1.pgdg100+1
timescaledb_version: 2.6.0~debian10
promscale_extension: 0.3.0
```
OS is Debian 10 and all packages are installed from apt repos except promscale_extension which is installed from source and promscale is downloaded as binary (Linux_x86_64)

Now trying to start promscale as before I get this error:
`Feb 23 17:31:25 timescaledb promscale_0.10.0_Linux_x86_64[15964]: level=error ts=2022-02-23T16:31:25.705Z caller=runner.go:101 msg="aborting startup due to error" err="could not acquire schema version lease. is a migration in progress?"`

And I see this long query stuck running on postgresql:
```

query | CALL _prom_catalog.execute_everywhere('create_prom_modifier', $ee$               +
      |     DO $$                                                                        +
      |         BEGIN                                                                    +
      |             CREATE ROLE prom_modifier;                                           +
      |         EXCEPTION WHEN duplicate_object THEN                                     +
      |             RAISE NOTICE 'role prom_modifier already exists, skipping create';   +
      |             RETURN;                                                              +
      |         END                                                                      +
      |     $$;                                                                          +
      | $ee$);                                                                           +
      |                                                                                  +
      | CALL _prom_catalog.execute_everywhere('create_prom_admin', $ee$                  +
      |     DO $$                                                                        +
      |         BEGIN                                                                    +
      |             CREATE ROLE prom_admin;                                              +
      |         EXCEPTION WHEN duplicate_object THEN                                     +
      |             RAISE NOTICE 'role prom_admin already exists, skipping create';      +
      |             RETURN;                                                              +
      |         END                                                                      +
      |     $$;                                                                          +
      | $ee$);                                                                           +
      |                                                                                  +
      | CALL _prom_catalog.execute_everywhere('create_prom_maintenance', $ee$            +
      |     DO $$                                                                        +
      |         BEGIN                                                                    +
      |             CREATE ROLE prom_maintenance;                                        +
      |         EXCEPTION WHEN duplicate_object THEN                                     +
      |             RAISE NOTICE 'role prom_maintenance already exists, skipping create';+
      |             RETURN;                                                              +
      |         END                                                                      +
      |     $$;                                                                          +
      | $ee$);                                                                           +
      |                                                                                  +
      | CALL _prom_catalog.execute_everywhere('grant_prom_reader_prom_writer',$ee$       +
      |     DO $$                                                                        +
      |     BEGIN                                                                        +
      |         GRANT prom_rea




```
Tried even with version 0.9.0 and it throws the same error.

Can you tell how to solve this issue?

Thanks

**Comment by enidvrenozaj** [comment]
I tried to stop/start this specific process and also the whole postgresql server, tried to use different promscale binary versions (e.g promscale_0.6.2_Linux_x64_64) and the executable seems to be stucked without listening to port 9201 and the same query can be shown on postgresql pg_stat_activity.
Is there any way to tell if this is a normal migration/upgrade process or if there is any issue?

**Comment by enidvrenozaj** [comment]
I used promscale_0.6.2_Linux_x86_64 and let it run for a long time (more than 8 hours) and afterwards promscale showed this error:

`Feb 24 05:39:20 timescaledb promscale_0.6.2_Linux_x86_64[16294]: level=error ts=2022-02-24T04:39:20.295Z caller=runner.go:50 msg="aborting startup due to error" err="migration error: Error while trying to migrate DB: Error encountered during migration: error executing migration script: name versions/dev/0.5.2-dev/1-downsampling.sql, err ERROR: deadlock detected (SQLSTATE 40P01)`

How can I ensure that the migration finishes successfully?

**Comment by antekresic** [comment]
Hey @enidvrenozaj just wanted to let you know we are looking into this issue, will try to get back to you as soon as possible.
Thanks!

**Comment by enidvrenozaj** [comment]
Hi @antekresic thank you for your feedback.
Just want to update on the issue that after leaving the promscale binary running without any output for more than 8 hours now I can see metrics being pushed to promscale v0.6.2.
I wonder if I can go directly to version 0.10.0 or should I use some intermediary versions?

**Comment by enidvrenozaj** [comment]
And after starting correctly version 0.6.2 I could just run version 0.10.0 without any issues and without waiting a long time.
I guess the issue was going from 0.3.0 to 0.6.x probably?

**Comment by antekresic** [comment]
Yeah, I think there was some issue going from lower versions to 0.6 . I suggest moving to 0.10 definitely and I would be surprised if you had any issues migrating to it. Do let us know if the issues persist.

**Comment by enidvrenozaj** [comment]
Yes indeed, seems to be ok until now. Will update you in case I encounter any issue.
Thank you
