### ISSUE TITLE
.../api/v1/label/__tenant__/values shows all tenants even though -multi-tenancy-valid-tenants=XYZ is set

### ISSUE THREAD

**Issue by oscni** [timescale/promscale#1194]
Is this some configuration issue, a bug or by design. I certainly don't want different tenants to be able to know about each other.
series/queries seems to work as expected.

Configuration options:
PROMSCALE_MULTI_TENANCY=true
PROMSCALE_MULTI_TENANCY_ALLOW_NON_TENANTS=false
PROMSCALE_MULTI_TENANCY_VALID_TENANTS=XYZ

**Comment by Harkishen-Singh** [comment]
Hey @oscni, they look like the right options. Are you facing any error? The mentioned way will keep data of XYZ separate from other tenants (which are not present in this case).

**Comment by oscni** [comment]
ok great then we know my fat fingers are not the problem :)
No errors is shown, and series queries seems to work in that sense that it only return data from the allowed tenant.
Problem in this issue is that when one customers lists all __tenant__ labels it return all the tenant/customer names and not only the one that is specified in valid_tenants option.

**Comment by Harkishen-Singh** [comment]
Yes, if labels like '__tenant__=".*"' is applied, then it will return all valid tenants since for that promscale instance, it has been asked to have complete authority over the mentioned valid tenants.

If you want the customer to only see their part of tenant, you should run different promscale instances with the valid tenant being the ones you want to be shared with them the maximum.

**Comment by oscni** [comment]
>If you want the customer to only see their part of tenant, you should run different promscale instances with the valid tenant being the ones you want to be shared with them the maximum.
Yepp read that in some documentation and that's what I've done. But it does only work the the actual data APIs, not when using the labels API and listing all the __tenant__ labels. In that case it shows all tenant names and not only the configured one.

>Seeing your recent comment, you mean that a promql query is returning more tenants than the ones specified in the valid tenants. Is this your point?
yes, data belonging to another tenant is correctly filtered out. But when listing all __tenant__ labels it show incorrectly all tenants names and not only the one configured.

**Comment by Harkishen-Singh** [comment]
Ah, I think you are right. The labels API does not respect the tenants and that is a bug.

Thanks for pointing it out. I will mark this as bug and track in the sprint plannings.

**Comment by oscni** [comment]
:+1: 
Thanks for the awesome work with promscale :)

**Comment by ramonguiu** [comment]
@oscni we have looked into this and unfortunately to filter labels for all tenants would require a significant effort to change the data model to make the API call execution performant. As a result we are leaving this in the backlog and will revisit again in the future once we have the bandwidth to look into it.

**Comment by ramonguiu** [comment]
[Release 0.12.0](https://github.com/timescale/promscale/releases/tag/0.12.0) includes a fix where the only the value for the current tenant will be returned by the labels API for the `__tenant__` label.
