### ISSUE TITLE
Prometheus API does not always return data when querying downsampled metrics

### ISSUE THREAD

**Issue by ostertagconrad** [timescale/promscale#1228]
First of all I want to say: Promscale is a awesome tool. It helps us to connect our long term data on our postgres systems with grafana. 
Thank you very much for developing and maintaining it.

With the 0.6.0 release we enabled downsampling for some metrics.
Exemplary for one metric:

```sql
CREATE MATERIALIZED VIEW ufz_downsample.postfix_smtpd_messages_processed_total_1hour( time, series_id, min, max, value )
WITH (timescaledb.continuous) AS
  SELECT
      time_bucket('1 hour', time) as time,
      series_id,
      min(value) as min,
      max(value) as max,
      avg(value) as value
    FROM prom_data.postfix_smtpd_messages_processed_total
    GROUP BY 1, 2
;

CREATE MATERIALIZED VIEW ufz_downsample.postfix_smtpd_messages_processed_total_1day( time, series_id, min, max, value )
WITH (timescaledb.continuous) AS
  SELECT
      time_bucket('1 day', time) as time,
      series_id,
      min(value) as min,
      max(value) as max,
      avg(value) as value
    FROM prom_data.postfix_smtpd_messages_processed_total
    GROUP BY 1, 2
;

SELECT register_metric_view('ufz_downsample', 'postfix_smtpd_messages_processed_total_1hour');
SELECT register_metric_view('ufz_downsample', 'postfix_smtpd_messages_processed_total_1day');
```

When we query them through the Prometheus API of Promscale, we do not always get data depending on the time range and `step` interval.

For debugging and reproducing we used the following curl command:

```
curl -sg -u user:password 'http://localhost:9201/api/v1/query_range?query=postfix_smtpd_messages_processed_total_1day{__schema__="ufz_downsample",__column__="value"}&start=2021-08-15T00:00:00.000Z&end=2022-02-15T00:00:00.000Z&step=7200' | jq '.data.result[].values | length'
```

With the following parameters the query returns no data points:
  - `start=2021-08-15T01:00:00.000Z&end=2022-02-15T01:00:00.000Z&step=7200`
  - `start=2021-08-15T01:00:00.000Z&end=2022-02-15T00:00:00.000Z&step=7200`
  - `start=2021-08-15T03:00:00.000Z&end=2022-02-15T03:00:00.000Z&step=7200`  

In turn this are working parameters:
  - `start=2021-08-15T00:00:00.000Z&end=2022-02-15T00:00:00.000Z&step=7200`
  - `start=2021-08-15T02:00:00.000Z&end=2022-02-15T02:00:00.000Z&step=7200`
  - `start=2021-08-15T00:00:00.000Z&end=2022-02-15T00:00:00.000Z&step=3600`
  - `start=2021-08-15T01:00:00.000Z&end=2022-02-15T01:00:00.000Z&step=3600`
  - `start=2021-08-15T02:00:00.000Z&end=2022-02-15T02:00:00.000Z&step=3600`
  - `start=2021-08-15T03:00:00.000Z&end=2022-02-15T03:00:00.000Z&step=3600`

Everything above only concerns the metric `postfix_smtpd_messages_processed_total_1day`.
If we query `postfix_smtpd_messages_processed_total_1hour` any parameters do work.

Our first guess was that if we divide the number of hours between start and end with `step` and the modulo is zero then it works.
If the modulo is not zero, it does not work.

But then we tried more combinations and found out that most likely the `start` and `step` only change the result of the query.

We use Promscale as a Prometheus data source in Grafana.
Since we live in CET timezone Grafana translates the time range `Last 6 Months` to `start=2021-08-15T01:00:00.000Z&end=2022-02-15T01:00:00.000Z&step=7200`.
We have no easy way to use always a working time range and step interval.

The production system uses:
  - PostgreSQL version: `13.3`
  - TimescaleDB version: `2.4.1`
  - Promscale version: `0.6.2`

We copied the database on a development server where we could update Promscale to version `0.10.0` easier.
Unfortunaly the issue still remains.
The same applies if we updated to a newer PostgreSQL version like `13.5` or TimesacleDB like `2.5.1`.

Did you already recognized such issues or some similiar behaviour? Is there anything we can improve or adjust to get it more reliable. If needed we will gladly provide more working and not working examples, config, logs or update the components of the (develop) system to identify the root cause. Any help will be appreciated.

**Comment by Harkishen-Singh** [comment]
Thank you for creating the issue.

@antekresic can you please take a look here?

**Comment by antekresic** [comment]
Hi there. 

Just wanted to let you know that I'm trying to investigate what might be causing this issue. I'll get back to you once I have some new info.

Thanks!

**Comment by Harkishen-Singh** [comment]
This is due to the way PromQL evaluation works.

When you create a cagg for 1 day interval, the samples are evaluated at midnight (12:00 am).
* If PromQL evaluates steps every hour, then it will consider the 12:00 am sample, which is why your 3600 step works
* If this is changed to 2 hours, then evaluation will miss the even hours (if executed at an odd hour), which is why queries done at 1:00 am, 3:00 am had no result. But when the same were done at 00:00 or 2:00 am, it got the same since 2 hour step will consider the sample at 00:00.

A good way to make the engine lookback to an hour of sample is to set `metrics.promql.lookback-delta=1h` but this should not be required as the above behavior is expected.

**Comment by antekresic** [comment]
@ostertagconrad I hope this helps you understand whats going on with the range queries. 

Would you mind reviewing the info and closing the issue if you have no further questions?

Thanks!

**Comment by ostertagconrad** [comment]
Thank you very much for the explanation.
