### ISSUE TITLE
Evaluate compression lib for http responses

### ISSUE THREAD

**Issue by antekresic** [timescale/promscale#123]
https://github.com/klauspost/compress is a drop in replacement for the Go standard library compression library which is supposed to perform better. 

We should try this library and use it if the performance impact is worthwhile.

**Comment by antekresic** [comment]
Another candidate for JSON handling perfomance improvement: 
https://github.com/segmentio/encoding

**Comment by cevian** [comment]
@antekresic do you think this is still worthwhile? Specifically the compression. We are now using github.com/NYTimes/gziphandler

For json we know manually compile it, which is faster than any general-purpose encoder see `marshalVectorResponse` and other functions in marshal.go

**Comment by ramonguiu** [comment]
@antekresic can this be closed?

**Comment by VineethReddy02** [comment]
closing this after discussion with Ante, as it's no more required.
