### ISSUE TITLE
Re-enable multinode e2e tests

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/promscale#1255]
In https://github.com/timescale/promscale/pull/1248 we've disabled the multinode e2e tests because they're failing against the latest (development) promscale extension version.

That issue is being tracked in https://github.com/timescale/promscale_extension/issues/138.

Once we have those issues fixed, we should come back and re-enable the multinode e2e tests.

**Comment by cevian** [comment]
Multinode not supported for now
