### ISSUE TITLE
Add the ability to print the connector version

### ISSUE THREAD

**Issue by JLockerman** [timescale/promscale#129]
Add a `--version` flag which prints out which version of the connector is running. This is useful when debugging.

**Comment by VineethReddy02** [comment]
Will a cmd like version work? i.e 
```
$ ./timescale-prometheus version
using patched pgconn
Version:  0.1.0-alpha.4.1
```

A simple way of achieving this would be to add a block like this in main.go 

```
	versionFlag := os.Args[1]
	if versionFlag == "version" {
		fmt.Println("Version: ", Version)
		os.Exit(1)
	}
```

OR 

we can use https://github.com/spf13/cobra (CLI library) for adding more cmds in timescale-prometheus like run, version, etc...

I'm open to suggestions & thoughts.

**Comment by Harkishen-Singh** [comment]
if we do `promscale -h`, we already get to know the version at the last line. So, not sure why we need this. Anyways, a `version` flag is common among binaries.
