### ISSUE TITLE
Table schema of metrics (prom_data."metric") -> Why no primary index?

### ISSUE THREAD

**Issue by thmang82** [timescale/promscale#1299]
Hello,

I am currently trying to understand a bit how the promscale data-storage works. We need to be able to update old measurements after some time without creating duplicates, because the values might change due to delayed data arriving (need to be re-computed). I know that Prometheus does not support this, but I thought Promscale/Timescale DB might offer a way to enables this (without re-inventing the wheel).

That's why I had a look how metric data is stored. Especially how the "real" data-tables for each metric are set up.

Here is the SQL code creating a metric, that I extracted via DBeaver:
<pre><code>
CREATE TABLE prom_data.process_cpu_seconds_total (
	"time" timestamptz NOT NULL,
	value float8 NOT NULL,
	series_id int8 NOT NULL
)
WITH (
	autovacuum_vacuum_threshold=50000,
	autovacuum_analyze_threshold=50000
);
CREATE UNIQUE INDEX data_series_id_time_56 ON prom_data.process_cpu_seconds_total USING btree (series_id, "time") INCLUDE (value);
</code></pre>

What I am wondering: why are you only using secondary index? But not a primary one?
A primary index on series_id,time would allow duplicate elimination. But it should also allow for speeding up queries, as the data would be aligned on disk with regards to the b-tree.
Is there anything that speaks against using a primary index? Some penalty on inserting data? 

Best regards,
Thomas

**Comment by cevian** [comment]
Hey @thmang82 sorry for the late reply. In PostgreSQL, primary keys are actually /not/ clustered on disk (data is not ordered by primary key in the heap). So there is no difference in terms of on-disk organization between the UNIQUE index above and a PRIMARY KEY index, it's all syntactic sugar. I don't remember why we chose one syntax over the other, honestly.
