### ISSUE TITLE
Steps to set timescaleDB on existing postgresDB

### ISSUE THREAD

**Issue by asharabu** [timescale/promscale#131]
Hi,

can you please provide the exact steps to setup timescaleDB in the existing Postgres database Docker container?

**Comment by antekresic** [comment]
You can try installing it from source, if you want to use an existing Postgres Docker container.

Here is how you can do that: https://docs.timescale.com/latest/getting-started/installation/ubuntu/installation-source

**Comment by cevian** [comment]
I assume this is resolved. Please re-open if this issue is not resolved.
