### ISSUE TITLE
Low cache hit ratio for `metric_name` cache

### ISSUE THREAD

**Issue by paulfantom** [timescale/promscale#1356]
It appears that `metric_name` cache is not reaching high levels of cache hits. To my knowledge cache hit ratios for postgres should be usually in high 90s and we are experiencing a hit ratio of ~84%.

![Screenshot from 2022-05-12 12-03-36](https://user-images.githubusercontent.com/3531758/168046310-5fc1a829-6a11-450d-ab56-6c637b921392.png)

**Comment by JamesGuthrie** [comment]
Do you have statistics on cache invalidations? Or cache fullness?

**Comment by paulfantom** [comment]
This is from our demo environment to which team has access :)

**Comment by paulfantom** [comment]
Bumping this as it starts to be a problem in very basic deployments. Just after 6h of running default tobs installation we get a `PromscaleCacheTooSmall` alert firing due to a problem described in this issue. Since it is not acceptable to ship a default installation that is immediately firing alerts it would be good to raise the priority of this investigation. However, if there is no fix or time to investigate, we'll need to consider dropping this alert.

cc'ing @VineethReddy02 for visibility

**Comment by arajkumar** [comment]
I can work on this.
