### ISSUE TITLE
Migrate from pg_prometheus to promscale

### ISSUE THREAD

**Issue by nikhil-postgres** [timescale/promscale#1369]
Hi Team,

We have been using pg_prometheus for sometime and we would like to move to promscale as pg_prometheus is no longer active.

Is there any document to refer to on how to move to promscale and which version of promscale?

pg_prometheus version - 0.2.2

Thanks

**Comment by ramonguiu** [comment]
@nikhil-postgres you should follow the standard installation instructions for Promscale to get a Promscale (Connector + Database) instance up: https://docs.timescale.com/promscale/latest/installation/

Once it's up, migrate the existing Prometheus data as explained in https://docs.timescale.com/promscale/latest/installation/prom-migrator/

And finally, configure Prometheus to send data to Promscale:
https://docs.timescale.com/promscale/latest/send-data/prometheus/

Check this document to confirm hardware requirements: 
https://docs.timescale.com/promscale/latest/installation/recomm-guide/

**Comment by nikhil-postgres** [comment]
Sure, I will check this. Thanks!

**Comment by nikhil-postgres** [comment]
@ramonguiu  which promscale version would be better for migration from pg_prometheus version - 0.2.2?

Postgres Version - 11.7
TimescaleDB version - 2.3.1

**Comment by ramonguiu** [comment]
@nikhil-postgres that version of Postgres is quite old and not supported. The latest version of Promscale also requires a more recent version of TSDB but previous ones should be fine.

Do you have plans to upgrade to more recent versions?

**Comment by ramonguiu** [comment]
@nikhil-postgres I am closing this issue. Please re-open if you have any further questions.

**Comment by nikhil-postgres** [comment]
Apologies, I missed to update. 

Yes, we have plans to upgrade both Postgres and TSDB to 13.6 and 2.3.1 respectively. But before that, we would need to upgrade pg_prometheus (0.2.2) to some version of promscale.

Current settings
PostgreSQL - 11.7
TSDB - 1.6
pg_prometheus - 0.2.2

We are thinking of going with below method:

1. Upgrade/Migrate pg_prometheus to promscale (some version)
2. Upgrade TSDB to 2.3.1
3. Upgrade Postgres to 13.4

For point 1, we don't know which version of promscale we should upgrade/migrate to, that would be compatible with PostgreSQL 11.7 and TSDB 1.6.
