### ISSUE TITLE
Error querying for traces

### ISSUE THREAD

**Issue by omkar-yb** [timescale/promscale#1379]
I am using [jaeger-query](https://www.jaegertracing.io/docs/1.34/deployment/#query-service--ui) with Promscale to query the trace data. I have configured it to use Promscale as outlined here - https://docs.timescale.com/promscale/latest/visualize-data/jaeger/.

On running the query, I get this error:

Status | 500
-- | --
Status text | Internal Server Error
URL | /api/traces
Query | end=1653499946841000&limit=20&lookback=1h&maxDuration&minDuration&operation=test&service=jenkins&start=1653496346841000
Response body | {   "data": null,   "total": 0,   "limit": 0,   "offset": 0,   "errors": [     {       "code": 500,       "msg": "stream error: rpc error: code = Unknown desc = error scanning trace: populate span error: making span tags: unknown tag type []interface {}"     }   ] }

Any idea how to fix this?

**Comment by ramonguiu** [comment]
@omkar-yb what versions of Jaeger and Promscale are you using?

**Comment by omkar-yb** [comment]
@ramonguiu I am using Jaeger v1.34 and the [latest Promscale docker image](https://hub.docker.com/r/timescale/promscale/tags) , which is suppose is v0.11.

**Comment by ramonguiu** [comment]
Ok, so latest versions. Let me run a test and see if I can reproduce.

**Comment by ramonguiu** [comment]
I've tested and I am not getting any errors so I guess there must be something special about your environment, maybe something related to the data in the database.

Could you try running the same http request directly against Promscale? We implement that API as well.

So something like `http://promscale-host:9201/end=1653499946841000&limit=20&lookback=1h&maxDuration&minDuration&operation=test&service=jenkins&start=1653496346841000`

(replace promscale-host with the actual host where Promscale is running).

**Comment by jgpruitt** [comment]
@ramonguiu It looks like it may be coming from this line of code: https://github.com/timescale/promscale/blob/master/pkg/jaeger/query/trace_scan.go#L292

It looks like it does not handle tag values which are arrays of values.

**Comment by jgpruitt** [comment]
@omkar-yb Would you mind running this query? I'd like to know what kinds of tag values you have.

`select distinct jsonb_typeof(value) from _ps_trace.tag;`

**Comment by ramonguiu** [comment]
@omkar-yb sorry, it's late where I am and I pasted the wrong url. Regardless, it looks like @jgpruitt has some pointers as to where the problem may be coming from.

**Comment by omkar-yb** [comment]
@ramonguiu no worries, appreciate the help! I get the same error by calling fixed url as well.

@jgpruitt This is what I get back from the query
>postgres=# select distinct jsonb_typeof(value) from _ps_trace.tag;
 jsonb_typeof
--------------
>boolean
 array
 string
 number
(4 rows)
postgres=#

**Comment by jgpruitt** [comment]
Thank you, @omkar-yb. That confirms it for me. You have some tags of type array, and this particular code path doesn't support it. Would you mind running one more query? I'd like to see some examples of the tags in question.

`select key, value from _ps_trace.tag where jsonb_typeof(value) = 'array' limit 10;`

**Comment by omkar-yb** [comment]
@jgpruitt sure thing, here it is:


| key        | value           |
| ------------- |:-------------:|
query.$class                    | ["hudson.views.StatusColumn", "hudson.views.WeatherColumn", "hudson.views.JobColumn","hudson.views.LastSuccessColumn", "hudson.views.LastFailureColumn","hudson.views.LastDurationColumn", "hudson.views.BuildButtonColumn"]
 query.stapler-class             | ["hudson.views.StatusColumn", "hudson.views.WeatherColumn","hudson.views.JobColumn", "hudson.views.LastSuccessColumn", "hudson.views.LastFailureColumn", "hudson.views.LastDurationColumn", "hudson.views.BuildButtonColumn"]
 ci.pipeline.run.cause           | ["TimerTriggerCause"]
 ci.pipeline.run.committers      | []
 ci.pipeline.parameter.name      | ["PACKAGE_ALL"]
 ci.pipeline.parameter.sensitive | [false]
 ci.pipeline.parameter.value     | ["false"]
 ci.pipeline.run.cause           | ["ParameterizedTimerTriggerCause"]
 ci.pipeline.parameter.sensitive | [false, false, false, false, false, false, false, false, false, false, false, false]                                                              
 ci.pipeline.parameter.value     | ["458c00148d06f0c9e25d17993832fc260234c673", "master", "0", "3", "0", "false", "false", "", "", "", "", "1"]

@niksajakovljevic sounds good, thanks for jumping on this!

**Comment by ramonguiu** [comment]
[Release 0.12.0](https://github.com/timescale/promscale/releases/tag/0.12.0) includes this fix

**Comment by omkar-yb** [comment]
It seems to work in the 0.12 release. Thanks for getting this fixed!
