### ISSUE TITLE
Filtering by tag in Jaeger (or Grafana's distributed tracing UI) does not work

### ISSUE THREAD

**Issue by ramonguiu** [timescale/promscale#1380]
When adding filters in the Tags field in the Jaeger those don't seem to work and always return 0 results. Setting other fields does filter traces accordingly.

**Comment by ramonguiu** [comment]
This was user error. Filtering by span or resource tags works correctly but I've found one case where it doesn't work.

Using the [opentelemetry-demo](https://github.com/timescale/opentelemetry-demo), filtering traces from the generator service that have the tag `http.status_code=200` returns no results even though there are many that match. Filtering using `http.method=GET` does work.

**Comment by mlvzk** [comment]
Hi, I have the same problem. Filtering only seems to work on string values, not on booleans or integers.

**Comment by ramonguiu** [comment]
[Release 0.12.0](https://github.com/timescale/promscale/releases/tag/0.12.0) includes this fix

**Comment by ramonguiu** [comment]
There seems to still be an issue with booleans that will be tracked in https://github.com/timescale/promscale/issues/1447
