### ISSUE TITLE
Tweak default values in Promscale connector for best performance

### ISSUE THREAD

**Issue by peppercoffee** [timescale/promscale#1391]
Promscale project has a lot of knobs a user can turn to their specific needs. However, we should at least improve the defaults we provide so that users are not necessary to start tuning as soon as they start using Promscale.

As part of this task, we should also review some of the major settings for Timescale/Postgres that impact Promscale performance the most and make note of necessary changes with specific details of their impact on the system.

**Comment by peppercoffee** [comment]
[(Placeholder) document](https://docs.google.com/document/d/1S7c1JhlqYElDdywomSTFGFriNta6V4Kr_R14V_Kso9M/edit)

**Comment by peppercoffee** [comment]
By now only reviews are on the Applications' team side.

**Comment by ssola** [comment]
Closing this issue, as this falls under the Better defaults initiative.
