### ISSUE TITLE
Local go bench for ingest

### ISSUE THREAD

**Issue by peppercoffee** [timescale/promscale#1398]
- https://github.com/timescale/promscale/pull/1279
- Run benchmark in CI and compare with previous results. https://github.com/timescale/promscale/pull/1511
- Benchmarking cases:
  - Ideal: Ingest data from prometheus block in regular intervals of time
  - Slow startup: Regularly ingest set of series with 1 sample only, so the allocs collected is purely series dependent https://github.com/timescale/promscale/pull/1522

**Comment by niksajakovljevic** [comment]
Potentially add a bench test that only does metadata ingest.

**Comment by Harkishen-Singh** [comment]
@niksajakovljevic `only metadata ingest` is basically the `slow startup` case mentioned in the issue.
