### ISSUE TITLE
Add a slack notifier for master build failures

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/promscale#1406]
We recently had the problem that master builds were failing for about a week, without anybody noticing.

We should add a slack notifier which posts to the #eng-observability channel when the master build is unsuccessful.

**Comment by paulfantom** [comment]
Some possible solutions/implementations/ideas:
- github action with slack notifier - https://github.com/marketplace/actions/slack-notify-build
- workflow used by database team - https://github.com/timescale/timescaledb/blob/main/.github/workflows/ci_summary.yaml
