### ISSUE TITLE
Separate db connection pools for better ingest performance

### ISSUE THREAD

**Issue by Harkishen-Singh** [timescale/promscale#1419]
At present, the db connection pool is shared between query and ingest components.
If there happens a heavy query, it will take lot of time to execute, leading to the connection
from the pool being occupied. This affects the ingest performance under heavy queries.

We should segregate the db connection pools between ingest and write.

**Comment by peppercoffee** [comment]
[Document with more information](https://docs.google.com/document/d/11bIF7YHMYlodvPLIITQ6cSaK1A6HqWpIsR_WYySmbI0)
