### ISSUE TITLE
/api/v1/labels should only return metric labels for the specified tenants in the Promscale multi-tenancy configuration

### ISSUE THREAD

**Issue by ramonguiu** [timescale/promscale#1428]
In a multi-tenant setup where Promscale has been configured to only return data for a specific set of tenants, the labels API (/api/v1/labels) doesn't respect that setting. It currently returns label data for all labels in the system which is wrong.

Currently all labels for all tenants are stored together. Separating them by tenant requires a change in the data model to make the API call execution performant.

**Comment by JosefPihrt** [comment]
@ramonguiu ping

**Comment by Harkishen-Singh** [comment]
I think we could simply filter the tenants not permitted in multi-tenancy after fetching from the db before replying to the Api request. That should work as a quick fix to this issue.

@JosefPihrt sorry for the delay. I will give this issue a try sometime today and see if it can be fixed without major changes. If so, then we can target this in the next release.

**Comment by JosefPihrt** [comment]
@Harkishen-Singh Thanks in advance!

**Comment by ramonguiu** [comment]
@JosefPihrt so sorry I missed your mentions in this ticket. I would love to understand more about your use case. If you would be open to a discussion please drop me an email (ramon at timescale.com).
