### ISSUE TITLE
Filtering true/false boolean tags doesn't work

### ISSUE THREAD

**Issue by mlvzk** [timescale/promscale#1447]
For example: `isExpired=true`, `isExpired=false` finds no spans, even though there are spans with those tags.

Promscale Version: 0.12.0, same issue was in 0.11.0

**Comment by ramonguiu** [comment]
@mlvzk are you running that query in Jaeger? If you are, could you attach a screenshot of how that tag shows in Jaeger for a span that has it?

How are the traces generated? Do you use OpenTelemetry client libraries or Jaeger client libraries?

**Comment by mlvzk** [comment]
> @mlvzk are you running that query in Jaeger? If you are, could you attach a screenshot of how that tag shows in Jaeger for a span that has it?
> 
> How are the traces generated? Do you use OpenTelemetry client libraries or Jaeger client libraries?

Yes, jaeger-query 1.35.0. I already switched back to jaeger+elasticsearch (I'm eager to switch to promscale) so I don't have a screenshot.

Traces were generated with the Go OpenTelemetry client and using a Jaeger Exporter.

**Comment by ramonguiu** [comment]
Thanks for the additional details. We'll do some tests on our side.

**Comment by niksajakovljevic** [comment]
This seems like a bug on our end. We need to take a special care of boolean values here (the same like we do for ints) https://github.com/timescale/promscale/blob/master/pkg/jaeger/query/trace_query.go#L244

**Comment by VineethReddy02** [comment]
@mlvzk The issue has been fixed and merged to master. The patch release should be out later this week. I will update you once the release is cut. :)

Thanks!

**Comment by VineethReddy02** [comment]
@mlvzk the `0.12.1` [patch release](https://github.com/timescale/promscale/releases/tag/0.12.1) is out. Feel free to test it out and share your feedback!

**Comment by ramonguiu** [comment]
@mlvzk please let us know if the fixe worked for you.

I would also like to connect to understand better your use cases and problems you are trying to solve to help us make our product better.

**Comment by mlvzk** [comment]
> @mlvzk please let us know if the fixe worked for you.
> 
> I would also like to connect to understand better your use cases and problems you are trying to solve to help us make our product better.

Hello, yes, it worked. Thank you. I did find another problem, but I will open a new Github issue for it.

We can connect on email if you want (mlvzk at protonmail.com).

**Comment by ramonguiu** [comment]
@mlvzk thanks. I dropped you an email on Friday. Did you get it?

**Comment by mlvzk** [comment]
@ramonguiu yes, sorry, I've been busy lately. I'll send you a reply soon.
