### ISSUE TITLE
Does promscale extension support Microsecond precision?

### ISSUE THREAD

**Issue by brandys11** [timescale/promscale#1477]
Hi, we are looking into adopting TimescaleDB & promscale seems like "easy" way to get data in there quickly. I would like to clarify timestamp precision handling.

- Would we be able to ingest individual datapoints with more than 1ms precission?
- According to docs the schema is using `timestamptz`, which has microsecond precision. How would promescale / timescaleDB handle multiple data points with same timestamp?

Thank you for clarification.

**Comment by ramonguiu** [comment]
The Prometheus data model uses millisecond  resolution. Our APIs are based on that and I'm not sure what would happen today if you try to send microseconds resolution instead even though the database may support it.

How do you intend to send data and query data?

**Comment by ramonguiu** [comment]
Oh, and regarding your other question I believe that if the metric name, labels and timestamp are the same, it would be treated as a duplicate data point but I will double check.

**Comment by ramonguiu** [comment]
@brandys11 I've confirmed that our APIs only support milliseconds resolution and that if you send multiple datapoints with the same labels and timestamp only the first one will be kept.

**Comment by brandys11** [comment]
Thank you for clarification :) We use InfluxDB line protocol -> Prometheus atm and loosing precision. I was hoping we could change it directly in promscale. But we will try to come up with different way of data ingestion :)
