### ISSUE TITLE
Improve transaction burn rate

### ISSUE THREAD

**Issue by pgnickb** [timescale/promscale#1489]
With help from Niksa we discovered that currently there are several hardcoded valules around transaction handling in metric ingestion code.
Alongside with this, we received a number of customer reports of high transaction ID consumption rate. A review of codepaths involved hinted that our approach might be faulty and we might want to reconsider the way transactions are handled. At the very least it'd make sense to make `batch timeout` and `batch size` configurable, as now they're hardcoded to `20ms` and `1000` respectively.

**Comment by cevian** [comment]
https://github.com/timescale/promscale/pull/1462/files May have already partially addressed this since it gets rid of a server-side try-catch block which burns a txn id. This should be measured.
