### ISSUE TITLE
Do not enable compression in connector (make ApacheOnly compatible)

### ISSUE THREAD

**Issue by prime-minister-of-fun** [timescale/promscale#150]
Hi, 

I am experiencing the "err starting ingestor" bug/feature and it's not clear to me how to disable compression.

Downloading the pre-built timescale-prometheus shows no options to disable compression on runtime.  Reading your very thorough documentation on compression, it seems like:

ALTER TABLE <table_name> SET (timescaledb.compress = false);

Should work..  Is this correct?

**Comment by cevian** [comment]
yes, that's the way to disable compression but can you provide more info about the error you are getting and the version of the connector you are using?

**Comment by prime-minister-of-fun** [comment]
I downloaded the pre-built  timescale-prometheus_0.1.0-alpha.4.1_Linux_x86_64.tar.gz.

The first time I run the binary with database login options it works as expected.  Restart the app and I get the following:
using patched pgconn
{"caller":"main.go:151","level":"info","msg":"Version:0.1.0-alpha.4.1; Commit Hash: ","ts":"2020-07-17T16:25:22.028Z"}
{"caller":"main.go:152","config":"&{listenAddr::9201 telemetryPath:/metrics pgmodelCfg:{host:localhost port:5432 user:prometheus_user password:**** database:timescale sslMode:disable dbConnectRetries:3 AsyncAcks:false ReportInterval:0} logLevel:debug haGroupLockID:0 restElection:false prometheusTimeout:-1 electionInterval:5000000000 migrate:true}","level":"info","ts":"2020-07-17T16:25:22.037Z"}
{"caller":"main.go:164","level":"warn","msg":"No adapter leader election. Group lock id is not set. Possible duplicate write load if running adapter in high-availability mode","ts":"2020-07-17T16:25:22.038Z"}
{"caller":"client.go:68","level":"info","msg":"host=localhost port=5432 user=prometheus_user dbname=timescale password='****' sslmode=disable connect_timeout=10","ts":"2020-07-17T16:25:22.139Z"}
{"caller":"client.go:81","err starting ingestor":"ERROR: functionality not supported under the current license \"ApacheOnly\", license (SQLSTATE 0A000)","level":"error","ts":"2020-07-17T16:25:22.198Z"}
{"ERROR: functionality not supported under the current license \"ApacheOnly\", license (SQLSTATE 0A000)":"(MISSING)","caller":"main.go:189","level":"error","ts":"2020-07-17T16:25:22.198Z"}


While my org probably won't be a paying customer, we are mostly a Postgresql shop, so this product is a great fit.

**Comment by cevian** [comment]
ahh this is the error ```ERROR: functionality not supported under the current license "ApacheOnly", license ```.  So that's the reason to turn off compression

**Comment by cevian** [comment]
Currently there is no way for the connector not to enable compression. But I will convert this to a feature request not to enable compression in the connector.

**Comment by cevian** [comment]
There is a "workaround" of using the TSL (full) version of timescaleDB. Leaving this up for people that may. encounter this issue.
