### ISSUE TITLE
Operations caches not cleared when ps_trace.delete_all_traces() run?

### ISSUE THREAD

**Issue by hashcutdev** [timescale/promscale#1518]
Hello, I'm just getting promscale up and running, and so far it's been working really well. I'm using v0.12.1 with promscale-extension v0.5.2.1 with postgresql 14.

After a few test runs, I ran ``SELECT ps_trace.delete_all_traces()`` to clear the database and start accepting production data. I didn't actually shut down promscale though. What I noticed then was that the span_name field was messed up, usually pointing to an incorrect span_name.

Looking at the SQL schema, I see that the span view gets span_name from the operations table, and I noticed that 1) the operation_id pointed to the wrong operation and 2) several operation_id's didn't have any entries in the operations table.

I let this run for several hours ingesting several hundred spans and the new span names never got entered into the operations table.

At that point, I shut down the promscale process, and then repeated the process (running delete_all_traces()), then started promscale up again. This time, the operations table populated right away with the new spans that were coming in, and the operation_id pointed to the correct entry.

It seems that somewhere within promscale, the operations table is being cached, and so even though delete_all_traces() does delete all of the entries in all of the postgresql tables, my guess is that promscale itself, if it's still running, doesn't clear its caches? And using that old cache, it selects the wrong operation_id (and doesn't add new entries to the operations table because it thinks those entries already exist).

If this is correct, I would suggest either updating the delete_all_traces() to also clear all caches, or updating the documentation to indicate that you should stop promscale before running the function, and then start afterwards to ensure everything is in sync.

**Comment by JamesGuthrie** [comment]
@hashcutdev thanks for submitting this issue. You're right, this is a bug, and your diagnosis about it being related to caches is correct. We will fix this.
