### ISSUE TITLE
Promscale restarted in k8s and failed to start

### ISSUE THREAD

**Issue by korjavin** [timescale/promscale#1520]
Looks like somewhere the tag of docker image wasn't pinned.

Now I am getting 
```
error while checking for supported and available promscale extension versions: The promscale extension is not available at the right version
```

which is pretty sad.

How to fix?

**Comment by ramonguiu** [comment]
Do you know what version of the Promscale Connector you were using before?

You should be able to fix by deploying the right version tag from https://hub.docker.com/r/timescale/promscale/tags . If you don't know what version to try you I think 0.10.0 should work.

Starting with 0.11.0 is when we require the Promscale extension: https://github.com/timescale/promscale/releases/tag/0.11.0

**Comment by korjavin** [comment]
Thank you, I upgraded to random version from dockehub, it started to work.

I still think that using no tag in helm chart is a mistake.

**Comment by ramonguiu** [comment]
I think our helm charts are always pinned to a version.

@paulfantom

**Comment by nhudson** [comment]
@ramonguiu looks like we do not pin the Promscale tag in the helm chart properly.  I'll get that corrected.

**Comment by VineethReddy02** [comment]
@nhudson If the version isn't specified by default docker pulls the latest tag right?

**Comment by korjavin** [comment]
Yes, latest

**Comment by nhudson** [comment]
@VineethReddy02 correct, it will try to pull the `latest` image tag.
