### ISSUE TITLE
Product Feedback Wanted: Support for multi-tenant queries

### ISSUE THREAD

**Issue by cevian** [timescale/promscale#153]
Today you can already write data from multiple tenants to timescale-prometheus. You'd just have to set up relabel configs https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config on the prometheus server to add labels indicating the tenant.

However it is not clear how to give single-tenant access to only their own metrics right now. We need more feedback from the community about how this should look?

PromQL: Should this be done with separate connectors for each tenant where we add a config to a connector that says that only results with a particular label are returned on all queries? If these are not separate connectors, how do we tell from a promQL query who the tenant making the query is? 

Do we need single-tenant SQL access? Should this use Row-level-security?

What types of queries do individual tenants make? Do we need to have performance isolation on the read or write side? 

Are their  cross-tenant queries? Who makes them? How do they look? 

Are there any existing projects in the Prometheus ecosystem that does this particularly well? Why do people like their approach?

**Comment by ksten-ab** [comment]
I've set up `Remote Write > Write Relabel configs` in my multi-tenant setup (where each tenant is a "uniquely named" k8s cluster).

WRT. PromQL my intention is 100% to perform "cross-tenant" queries from a Graphana instance, as I use TimescaleDB to aggregate from multiple clouds (e.g. AWS + Azure tenants).  That said, I'd be ok with having "cross-tenant PromQL reading" be a configuration property that can be turned on-off or equivalent.

If I were to attempt to implement this type of security could, my default instinct is to make the TimescalePrometheus connector configurable with a label name-value pair(s?) and add it as a default filter argument at the Remote Reader / PromQL level.   IMO, if you want security at the SQL level, it'd be easier to just configure that tenant to talk to a different Postgres database.

**Comment by wenerme** [comment]
Maybe let timescale-prometheus support multi db first ? We setup tenant by different db, have to run multi instance, if timescale-prometheus support multi db, for multi tenant, I think timescale-prometheus can expose different like
