### ISSUE TITLE
how to properly setup retention policy?

### ISSUE THREAD

**Issue by zongjiasushi** [timescale/promscale#1541]
We noticed that the retention policy is default to 90 days.

We use this SELECT prom_api.set_default_retention_period(%d * INTERVAL '1 day') to set up global retention policy.

A few moments ago, we experienced a GCP issue and some of our tables (not ALL??) retention policy is set back to default 90 days, thus we had a data loss.

Can someone help pointing out what could be the root cause on this? 
And, is there a recommended way of setting up and persist retention policy? Thanks!

**Comment by ramonguiu** [comment]
@zongjiasushi this is strange and sorry for the inconvenience this has caused.

If you set retention as explained in [our documentation](https://docs.timescale.com/promscale/latest/manage-data/retention/) like you did, then that retention should persist.

There are two other ways to configure retention for metrics:
- Configure retention for as specific metric using the `prom_api.set_metric_retention_period` also explained in the docs linked above. If you change the default retention, a metric that has been configured to use a specific retention using that function would keep the specific retention. You would have to use `prom_api.reset_metric_retention_period` to remove the specific retention and go back to using the default retention for that metric.
- Configuring default retention via configuration when the promscale process is started. See [this](https://github.com/timescale/promscale/blob/master/docs/dataset.md).

Given what you are seeing (the default retention has changed and only for some metrics), then my only guess is that someone would have configured specific metric retention for some metrics and also someone may have changed the default retention either by using the function or by passing it as a configuration parameter when the promscale process is started.

You can use `SELECT prom_api.get_default_metric_retention_period()` to get the default retention currently configured. You can use it after setting it to confirm it has worked correctly if you have some doubts. And you can use `prom_api.get_metric_retention_period('your_metric_name')` to check if there is a specific retention set for a metric.

**Comment by zongjiasushi** [comment]
Thanks for the explanation! We will try the approach you recommended, and reopen the issue if it happens again!
