### ISSUE TITLE
advice on metrics schema (large number of metric names v.s. large number of label values) 

### ISSUE THREAD

**Issue by qiaokan** [timescale/promscale#1565]
Hi, our design goal is to support a query semantics of balance of a given user, bank, currency, etc, over time.

We think there might be roughly 3 possible solutions to solve this:
1. have one metric for every possible combination, for example Balance_Joe_Chase_USD
2. Put all possible variables in the labels, then you query it like Balance[user='Joe', bank='Chase', currency='USD']
3. Have some manual shardings on top of option 1 to reduce the size of label values.

The most friendly way for us is definitely option 2. Timescale does have partitioning on any dimension, not just time.
I wonder if this is a viable solution, or do you see any issues of large number of label values.

If large number of label values is really a concern, we will probably go with option 3. 

Thanks!

**Comment by ramonguiu** [comment]
@qiaokan sorry for the late answer. Are you considering using Promscale for this data? I'm not entirely sure it makes sense to model this data using Promscale.

All that said, if you still wanted to use Promscale, I wouldn't recommend 1. It will create one hypertable for every unique combination of metric name and labels which would not work great.

2 may work but it will depend on the amount of data points you expect and cardinality (total unique different combinations of labels). Can you share some estimates?

**Comment by Harkishen-Singh** [comment]
Option 2 definitely is better to me. That said, the worst thing in option 2 would be slow queries due to PromQL semantics. You can use a reliable workaround of that, by using SQL for querying. You can directly query the series id (labels belonging to the user) and that should be good (we use an index on series_id and timestamp).

**Comment by qiaokan** [comment]
thanks!
