### ISSUE TITLE
Filtering by tags does not work.

### ISSUE THREAD

**Issue by sliat3pm** [timescale/promscale#1568]
We know that there exists one trace with tag key "payload.id" and value "304602898452"

![image](https://user-images.githubusercontent.com/110883585/185621082-a19691ed-6e82-4728-a0ee-19fe94fb000d.png)

But when we try to search for it with the filter by tag, we can't find it.
<img width="633" alt="image" src="https://user-images.githubusercontent.com/110883585/185621275-c0bec919-bf5d-4f91-bda8-62563cf34116.png">
<img width="631" alt="image" src="https://user-images.githubusercontent.com/110883585/185621430-cb7dde5f-3c6f-44b9-a65a-40e3c1810f5d.png">

We are aware of the [this similar issue](https://github.com/timescale/promscale/issues/1467),  but we have a problem with non-numerical values as well. Filtering doesn't work at all regardless of the type of the tag value.

**Comment by cevian** [comment]
#1566 should address the problems with using indexes for tag-based searches for both numeric and non-numeric tags. We expect it to be merged soon

**Comment by ramonguiu** [comment]
Fixed in Promscale 0.14.0
