### ISSUE TITLE
Undocumented configuration values in helm chart

### ISSUE THREAD

**Issue by Yamakaky** [timescale/promscale#1569]
(Opening it here since I assume the doc need to be updated) The helm chart defines `default_retention_period` and `compress_data` but they are not defined in the promscale doc linked.

https://github.com/timescale/helm-charts/blob/main/charts/promscale/values.yaml#L61

https://github.com/timescale/promscale/blob/master/docs/configuration.md

**Comment by jgpruitt** [comment]
In the [main configuration doc](https://github.com/timescale/promscale/blob/master/docs/configuration.md) that you reference, find `startup.dataset.config`. It will point you to [another doc](https://github.com/timescale/promscale/blob/master/docs/dataset.md) that details these configuration settings.

![Screen Shot 2022-08-22 at 2 52 48 PM](https://user-images.githubusercontent.com/4974668/186006965-a1d198d4-a71f-4286-a35d-4bc0878cb2c4.png)

https://github.com/timescale/promscale/blob/master/docs/dataset.md

**Comment by Yamakaky** [comment]
Oh, I see, thanks

**Comment by jgpruitt** [comment]
You are welcome!
