### ISSUE TITLE
Easy to have bad link query performance

### ISSUE THREAD

**Issue by Yamakaky** [timescale/promscale#1570]
```
select
  linked_start_time as "Time",
  span.span_name as "Test",
  span.status_code as "Test status",
  link.span_name as "SCAR action",
  replace(link.linked_status_code::text, 'unset', '') as "Action status",
  replace(linked_trace_id::text, '-', '') as valid_trace_id,
  replace(link.trace_id::text, '-', '')  as scar_trace_id
from link
join span on (linked_parent_span_id = span.span_id)
where 
  $__timeFilter(link.start_time) and $__timeFilter(link.linked_start_time) and $__timeFilter(span.start_time) and span.span_tags->'code.function' is not null
order by linked_start_time;
```
Removing one of these `$__timeFilter` gives bad performance with full table scan on the associated hypertable. Even simple queries to `link` can give bad performance if one timeFilter is omitted, for example `select * from link where start_time > now() - interval '1 hour'` gives https://explain.dalibo.com/plan/l0D with 16s of execution even though I don't have links for this time period.

I assume that's because `link` uses left joins and doesn't expose its `_ps_trace.link.span_start_time`. Maybe expose it in the view and update the doc with a warning about this performance trick?

**Comment by Yamakaky** [comment]
Now that I think of it, why does `link` does a `left join` on `span` and `linked_span`? Is there a case where `span` would be null? I don't think that's possible in otel, the links are defined in a list of the span, there is no separate Link message. https://opentelemetry.io/docs/reference/specification/trace/api/#span

**Comment by jgpruitt** [comment]
`link` in your query and questions is referring to the view `ps_trace.link`, correct?

No, the span_id cannot be null. A link must point to two spans. The left join is used in the view as an optimization. If you only select columns from one span or the other, postgres will omit the work of joining the one that was not referenced since it is left joined. An inner join would force it to join whether or not the output is used.

I see your point though. You have no way of filtering on the start time of the link table itself, which causes a full table scan.

Thank you for pointing this out!

**Comment by jgpruitt** [comment]
I've created an issue for this in the promscale extension repo as that's where it will be fixed. I am going to close this issue; feel free to follow the work there.

**Comment by Yamakaky** [comment]
I see. Did you confirm this is the case? Aren't view inlined at query time in postgres? Did you try adding a foreign key to link, so that postgresql knows there is an associated span for every link? Not sure if that would work, I'll test.

**Comment by Yamakaky** [comment]
Hum, so postgresql does scan the joined table even if there is a foreign key, which is odd but ok.

I'm wondering if this optimization is needed. Are there cases where you want to query `link` but not query any column from `span`?

**Comment by jgpruitt** [comment]
You may want to return columns from the linked span but not the source span or vice versa.

I think exposing the start_time of the link table should be sufficient. This will allow you to filter each hypertable on the time column and avoid the full table scans.

**Comment by Yamakaky** [comment]
In fact, it's required since there is no foreign key and `span` may not have the same data retention time as `link`

**Comment by jgpruitt** [comment]
Yes. Agreed.
