### ISSUE TITLE
Regression of #1176

### ISSUE THREAD

**Issue by oliora** [timescale/promscale#1573]
There was a bug https://github.com/timescale/promscale/issues/1176 that was fixed by upgrading PGX from **v4.15.0** to **v4.15.1-0.20220219175125-b6b24f9e8a5d**. Later if was upgraded further to **v4.16.0** (I haven't followed the reason though). Later the PGX upgrades were reverted by https://github.com/timescale/promscale/commit/c7acfc8f897bc2c72b39db73584ab3c16ceb7eb6 which most probably the reason why I see crashes similar to #1176 happening to me.

**Comment by jgpruitt** [comment]
We have upgraded the pgx libraries. It ought to go out with the next release.
