### ISSUE TITLE
Close method in Proxy may have a hanging go routine bug

### ISSUE THREAD

**Issue by 9iang22** [timescale/promscale#1604]
[pkg/jaeger/proxy/proxy.go:81](https://github.com/timescale/promscale/blob/master/pkg/jaeger/proxy/proxy.go)

Receiving unbuffered `errChan` in a select block. That may cause a [hanging go routine](https://github.com/trailofbits/semgrep-rules/blob/main/go/hanging-goroutine.yml). Maybe should change `errChan` to a buffered one. 
```
func (p *Proxy) Close(ctx context.Context, _ *storage_v1.CloseWriterRequest) (*storage_v1.CloseWriterResponse, error) {
	errChan := make(chan error)
	go func() {
		errChan <- p.conn.Close()
		close(errChan)
	}()
	var err error
	select {
	case err = <-errChan:
	case <-ctx.Done():
		err = ctx.Err()
	}
	if err != nil {
		err = fmt.Errorf("error closing connection to Promscale GRPC server: %w", err)
	}
	return nil, err
}
```
If no influence, please ignore this.

**Comment by arajkumar** [comment]
Hmm, I don't think it is a problem here as the go routine which writes doesn't do anything significant after writing to the channel.
