### ISSUE TITLE
Cache hit ratio dashboard panel should use rate

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/promscale#1607]
The `Hit ratio (metrics)` panel is driven by the following query:

```
promscale_cache_query_hits_total{type="metric"} / promscale_cache_queries_total{type="metric"}
```

This counts the total number of hits compared to the total queries issued against the cache. This means that the more cache queries are performed, the less "visible" cache misses become.

For example, consult the following graphs:

<img width="705" alt="image" src="https://user-images.githubusercontent.com/1117749/187676502-701f66b5-d778-4758-a739-c95020176d1f.png">

The top graph shows:

```
rate(promscale_cache_query_hits_total{type="metric"}[$__rate_interval]) / rate(promscale_cache_queries_total{type="metric"}[$__rate_interval])
```

Here it is immediately obvious that the cache hit ratio dropped considerably.

The bottom graph shows Promscale's `Hit ratio (metrics)` panel. It is possible to see that _something_ changed, but it's not possible to see the extent of the change in hit ratio.

One wrinkle to using rate, which I have glossed over here, is that not all caches are constantly in use. The following graphs show the difference between using rate (top) and not (bottom). Note the gaps, where the cache is not in use.

<img width="705" alt="image" src="https://user-images.githubusercontent.com/1117749/187677113-a5b79d50-e51a-43d7-954f-8c8c6689fff3.png">

**Comment by Harkishen-Singh** [comment]
I agree, this should have been `rate` Thank you for pointing this out.
