### ISSUE TITLE
tracing: StreamingSpanWriter doesn't seem to improve ingestion throughput 

### ISSUE THREAD

**Issue by arajkumar** [timescale/promscale#1632]
Currently there are 2 ways to get asynchronous ingestion behaviour in jager span ingestion.

1. Launch promscale with `--tracing.async-acks`
2. Use StreamingSpanWriter (enabled by default in latest the jaeger:main for grpc plugin, provided `StreamingImpl` in the server side)

But option 2 doesn't behave like a streaming writer when I benchmarked. Let's revisit the implementation to find the reason and fix it.

**Comment by cevian** [comment]
Related thought: So I think our tracing async-acks stuff is right now a bit suboptimal. Right now tracing.async-acks is a boolean and false by default. But this setting is suboptimal for jaeger in terms of performance and doesn't actually help with data safety at all. I suggest making tracing.asyn-ack a three-valued variable (on, off, auto) - defaults to auto.
Auto mode would keep sync acks for otel, but have async acks for jaeger (both regular and streaming).

**Comment by ramonguiu** [comment]
Why not make it on by default?
