### ISSUE TITLE
metrics metadata gc

### ISSUE THREAD

**Issue by qiaokan** [timescale/promscale#1729]
Hi, I found timescale db often has a lot of left over metadata (e.g. prom_data, prom_catalog, internal chunk tables) after we delete the series.

How do I properly cleanup these data? thanks

**Comment by alejandrodnm** [comment]
If you want to completely delete a metric you can use the `prom_api.drop_metric('container_cpu_load_average_10s')`. Take into account that the function won't run if the Promscale connector is running. You can find more information [here](https://docs.timescale.com/promscale/latest/manage-data/delete-data/#deletion-by-metric-name) 

If you're interested on what the function does, you can look at the source code here:

https://github.com/timescale/promscale_extension/blob/3087f70d18f158b0af1531a778360e7ec997a165/migration/idempotent/001-base.sql#L1000-L1029

Cheers
