### ISSUE TITLE
Errors during the Docker build

### ISSUE THREAD

**Issue by win32nipuh** [timescale/promscale#216]
I run docker-compose, it start to build the Docker and the result

PS D:\_Docker\TSPR\timescale-prometheus-master> docker-compose up
Creating network "timescale-prometheus-master_default" with the default driver
Building timescale-prometheus-connector
Step 1/11 : FROM golang:1.14.1-alpine AS builder
1.14.1-alpine: Pulling from library/golang
aad63a933944: Pull complete
c732a2540651: Pull complete
7b2225181d6b: Pull complete
c8dae7ec6990: Pull complete
08684ee472f3: Pull complete
Digest: sha256:244a736db4a1d2611d257e7403c729663ce2eb08d4628868f9d9ef2735496659
Status: Downloaded newer image for golang:1.14.1-alpine
 ---> 760fdda71c8f
Step 2/11 : COPY ./.git timescale-prometheus/.git
ERROR: Service 'timescale-prometheus-connector' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder265680322/.git: no such file or directory
PS D:\_Docker\TSPR\timescale-prometheus-master>

**Comment by antekresic** [comment]
Looks like its missing the `.git` folder. Did you use `git checkout` to fetch the code?

**Comment by win32nipuh** [comment]
> Looks like its missing the `.git` folder. Did you use `git checkout` to fetch the code?

No, I run docker-compose only, it uses docker-compose.yml file etc. I did add nothing. 
What I need to do to run it correctly?

**Comment by cevian** [comment]
docker compose now tested in #477
