### ISSUE TITLE
dial tcp: lookup prometheus_postgresql_adapter: No such host

### ISSUE THREAD

**Issue by win32nipuh** [timescale/promscale#217]
I run the docker-compose and receive: 

timescale-prometheus-connector_1  | {"addr":":9201","caller":"main.go:280","level":"info","msg":"Listening","ts":"2020-08-27T14:15:17.645Z"}
prometheus_1                      | ts=2020-08-27T14:17:38.800Z caller=dedupe.go:112 component=remote level=warn remote_name=686501 url=http://prometheus_postgresql_adapter:9201/write msg="Failed to send batch, retrying" err="Post \"http://prometheus_postgresql_adapter:9201/write\": dial tcp: lookup prometheus_postgresql_adapter on 127.0.0.11:53: no such host"
    
My prometheus.yml file
global:
 scrape_interval:     10s
 evaluation_interval: 10s
scrape_configs:
 - job_name: prometheus
   static_configs:
     - targets: ['node_exporter:9100']
remote_write:
 - url: "http://prometheus_postgresql_adapter:9201/write"
remote_read:
 - url: "http://prometheus_postgresql_adapter:9201/read"

How to fix it?

**Comment by antekresic** [comment]
Looks like you are using the wrong remote read and write URLs. 

Can you try changing it to `http://timescale-prometheus-connector:9201`?

**Comment by win32nipuh** [comment]
> Looks like you are using the wrong remote read and write URLs.
> 
> Can you try changing it to `http://timescale-prometheus-connector:9201`?

I have modified the prometheus.yml file

run and receive 
...
prometheus_1                      | ts=2020-08-28T14:07:33.809Z caller=dedupe.go:112 component=remote level=warn remote_name=380fe3 url=http://timescale-prometheus-connector:9201/write msg="Failed to send batch, retrying" err="Post \"http://timescale-prometheus-connector:9201/write\": dial tcp: lookup timescale-prometheus-connector on 127.0.0.11:53: no such host"

The docker-compose.yml is the same as here, I modified only 
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

because of it is Windows.

===================
prometheus.yml
------
global:
 scrape_interval:     10s
 evaluation_interval: 10s
scrape_configs:
 - job_name: prometheus
   static_configs:
     - targets: ['node_exporter:9100']
remote_write:
 - url: "http://timescale-prometheus-connector:9201/write"
remote_read:
 - url: "http://timescale-prometheus-connector:9201/read"
==================

**Comment by cevian** [comment]
The docker compose has been fixed and tested in #477
