### ISSUE TITLE
Make sure docker-compose works with SSL require 

### ISSUE THREAD

**Issue by cevian** [timescale/promscale#225]
This is a followup to #224 originally reported by @clementDele  We need to make sure our docker compose works with the SSL require change.

**Comment by JLockerman** [comment]
Looks like the issue isn't the SSL mode; it fails with the mode set to `prefer` as well. I suspect the issue is the race condition between connector start and database start: if the database isn't ready yet when the connector tries to connect, the connection will fail.

**Comment by JDTX** [comment]
@JLockerman It's a combination of both. I had to revert the commit that set `sslMode` to `require` ([here](https://github.com/timescale/timescale-prometheus/commit/e62d9f1432812397522e8588ea2e56a2edc59f85#diff-21adc0276abcfb544d5cf5dc2dbe5da3)) but that alone wasn't enough.

After reverting that, it still failed to start. I had to manually start up the timescale-prometheus-db, wait about 10 seconds, then start the connector. It started fine after that.

**Comment by JLockerman** [comment]
(wow this really fell of my radar)
@JDTX note that you can just fix it in the command passed in by docker compose, as we do in https://github.com/timescale/promscale/commit/f0452e4d3d4f5af1950b5a8effb457bf158b98ef
in fact, @cevian are we good to close this?

**Comment by cevian** [comment]
should be fixed and tested in #477
