### ISSUE TITLE
The series containment operator query example is invalid

### ISSUE THREAD

**Issue by timflannagan1** [timescale/promscale#265]
I was poking around the [series containment operator documentation](https://github.com/timescale/timescale-prometheus/blob/master/docs/sql_schema.md#containment) and noticed that the following query would produce a syntax error:

```sql
...
WHERE labels @> jsonb '{"namespace":"dev", "node": "pinky"'}
```

If you update that query example to use `... "node": "pinky"}'` that syntax error would be resolved.

**Comment by Harkishen-Singh** [comment]
Thanks for pointing it out. Do you want to submit a PR for this? Should be straight forward.
