### ISSUE TITLE
Customize generated prom_data tables

### ISSUE THREAD

**Issue by franck102** [timescale/promscale#281]
To try and account for Prometheus counter resets I would like to add a column to each metric table created by promscale.Trying to do so after the hypertable has been created fails because of compression:

```
alter table prom_data."service:applications:joined" add column increase float8 default null;
SQL Error [0A000]: ERROR: operation not supported on hypertables that have compression enabled
```

Is there any workaround that you can suggest? A feature allowing us to specify extra columns to create would be great!

**Comment by Harkishen-Singh** [comment]
AFAIK, you cannot update the schema that is created/managed by promscale.

**Comment by franck102** [comment]
Makes sense; can this be recorded as a feature request? I can imagine quite a few use cases where have calculated columns stored alongside the rest of the data in the original hypertable would be really useful.

Thanks!

**Comment by Harkishen-Singh** [comment]
That will be useful. I will let you know by commenting here after discussing with the team.

**Comment by cevian** [comment]
@franck102 can you give more details here? How do you plan to update the column (since the adapter will not automatically write to this column)?

**Comment by franck102** [comment]
I plan to use a before insert trigger, roughly something like this (pseudo sql code):

lastVal := select last(value,time) from TG_TABLE_NAME where series_id=NEW.series_id;
NEW.increase := case 
    when NEW.value >= lastVal THEN NEW.value - lastVal
    ELSE NEW.value;

return NEW;

**Comment by cevian** [comment]
This should be supported after #291 lands. You will be able to turn off compression, alter table, reenable compression.

**Comment by cevian** [comment]
This particular issue is now resolved by supporting turning off compression on tables. See #291 .

**Comment by franck102** [comment]
Thanks @cevian , I am getting back to this, so if I understand correctly the workflow would be something like:

<Trigger on insert in _prom_catalog.metric, do nothing unless creation_complete==true>:
  - disable compression on prom_data.<NEW.table_name>
  - alter table prom_data.<NEW.table_name> add column xyz
  - re-enable compression on the table

Is that how that would work?
Franck
