### ISSUE TITLE
Relationship between set_[default|metric]_retention_period and timescaleDB policies is unclear

### ISSUE THREAD

**Issue by franck102** [timescale/promscale#294]
** Version:
plpgsql,"1.0"
timescaledb,"1.7.4"
promscale,"0.1.1"

After calling both set_default_retention_period,  and set_metric_retention_period on some tables, the tables don't appear to have any Timescale drop chunk policies installed (SELECT * FROM _timescaledb_config.bgw_policy_drop_chunks returns nothing).

How will those retentions be applied, is promscale using its own mechanism? If so why?
We have non-promscale hypertables and having two mechanisms to manage retention would be a pain.

**Comment by cevian** [comment]
The drop chunks stuff is not handled through policies. It's handled by the `execute_maintenance()` procedure called by CRON. The reason is we need additional cleanup when dropping chunks: namely, we need to delete no-longer-used series and labels. This is handled in procedures called by `execute_maintenance()`

**Comment by franck102** [comment]
Makes sense, thanks!

I assume that the same rules as timescaledb's apply w.r.t. ignore_invalidation_older_than for continuous aggregates created on top of promscale hypertables? 
Meaning execute_maintenance will refuse to drop chunks if that were to cause a materialized CT to lose materialized data?

**Comment by cevian** [comment]
@franck102 yes that is correct. The underlying call is `PERFORM drop_chunks(table_name=>metric_table, schema_name=> 'SCHEMA_DATA', older_than=>older_than, cascade_to_materializations=>FALSE);`

Note this may change a bit once we move things to timescaledb 2.0
