### ISSUE TITLE
promscale-drop-chunk cronjob fails to schedule; and logs nothing

### ISSUE THREAD

**Issue by franck102** [timescale/promscale#299]
The Kubernetes cronjob installed by the helm chart doesn't specify a startingDeadlineSeconds. As a result after any kind of outage the job is never scheduled again, the Kubernetes controller considers that:
```
I1012 09:29:38.863619       1 event.go:274] Event(v1.ObjectReference{Kind:"CronJob", Namespace:"dmp-monitoring", Name:"dms-timescaledb-promscale-drop-chunk", UID:"0dbf45c1-f8ca-4129-bf3b-70b1798bdff8", APIVersion:"batch/v1beta1", ResourceVersion:"2761540", FieldPath:""}): type: 'Warning' reason: 'FailedNeedsStart' Cannot determine if job needs to be started: too many missed start time (> 100). Set or decrease .spec.startingDeadlineSeconds or check clock skew
```

After fixing this problem, the scheduler schedules the job but the job pod's log contains a single word:
```
km logs dms-timescaledb-promscale-drop-chunk-1602495360-2mmxt
CALL
```

I would help to know if the job actually called something, and what happened...

**Comment by cevian** [comment]
not to whoever picks this up: Also see #191, which needs to be redone
