### ISSUE TITLE
Document compatibility with dependencies in README and Release Notes (PostgreSQL+TimescaleDB+Promscale extension)

### ISSUE THREAD

**Issue by pocman** [timescale/promscale#302]
It would be great to add the supported postgresql version in the Readme and the release notes.

**Comment by Harkishen-Singh** [comment]
This https://github.com/timescale/promscale/pull/273 PR does that work from the promscale's side. Further, we will have this mentioned in the upcoming docs/website.

**Comment by VineethReddy02** [comment]
closing this issue, as its duplicate of #1408
