### ISSUE TITLE
Highly Available promscale with Helm

### ISSUE THREAD

**Issue by jpigree** [timescale/promscale#307]
Hi. I wanted to test Promscale HA capabilities with the Helm chart. I tried to just up the number of replicas but I saw a warning saying that my setup wasn't HA. So I read this [document](https://blog.timescale.com/blog/prometheus-ha-postgresql-8de68d19b6f5/) and from what I understand I need to pass those arguments to the PromScale command-line:
 `-leader-election.pg-advisory-lock-id=1 -leader-election.pg-advisory-lock.prometheus-timeout=6s`

However, there is [no way](https://github.com/timescale/promscale/blob/master/helm-chart/templates/deployment-connector.yaml#L24-L49) currently to pass command-line arguments to the container with the chart.

I can create a PR to fix this but I have a few questions first:
- Is there any more prerequisites to an HA setup? 
- Is it safe to use in production? How mature is it?
- Are there any drawbacks currently when using HA? From what I read, we may experience data loss if one of the replica crash. It will still be better than 1 replica though.
- When I submit the PR, should I automatically add the `leader-election` argument when the `replicaCount` is more than 1 or should I just give access to an `extraArgs` arguments. Perhaps, we should have both.

Thanks

**Comment by Harkishen-Singh** [comment]
Thank you for this. I feel the mentioned things should be enough for the proposed PR, along with some carefulness while implementing.

However, @JLockerman any views?

**Comment by jpigree** [comment]
@Harkishen-Singh , @JLockerman , I created a PR for this feature. I tested it. The arguments are correctly propagated to the Promscale pods and I successfully configured an HA setup with it.

After the merge, I think I will need to update the tobs chart aswell to be able to access this feature.
