### ISSUE TITLE
Prometheus fails to see new timescaledb metrics after 4 hours of service

### ISSUE THREAD

**Issue by jpigree** [timescale/promscale#308]
Hi. I have a setup like the following:
![setup](https://user-images.githubusercontent.com/3977280/96197017-92a09400-0eec-11eb-8ebc-0912771231c1.png)

It works fine but, as soon as I add alerts on the reader Prometheus, I start to have a weird behavior. After 4 hours of service, it stops to see any new metrics.
![missing_data](https://user-images.githubusercontent.com/3977280/96184958-e901d880-0ed4-11eb-9c3b-1cb7bb601cfe.png)

I just installed Promscale + Timescaledb + reader Prometheus using the **Tobs Helm chart version 0.1.0** from scratch (deleting all my previous data first). However, I used before the `0.1.0-beta-3` and `0.1.0-beta-4` versions and the bug was already there. At the time, I just disabled alerting.

When checking the Prometheuses monitoring dashboard, I can't see any suspicious activity except that we can't see any data after the first 4 hours. The only data that continues to show is the one from the reader itself which also use promscale as remote storage (the red line on the top left graph, red and yellow line on "memory usage" graph).
![Grafana_prometheuses_monitoring](https://user-images.githubusercontent.com/3977280/96185154-32522800-0ed5-11eb-85fc-d3c281686253.png)

From my perspective, it is as if, Prometheus decides, after 4 hours, to stop querying the db and just do as if those metrics aren't there. This looks like a timeout of some sort. There is no error anywhere in the logs(even when activating debug level in prometheus) or huge spike in requests or resources consumption. It just stops fetching the new data. At first, I only had a `remote_read` setup on the reader Prometheus: no `remote_write` and no scrape targets.

Then, I decided to send metrics from the reader Prometheus instance itself just to see how it will behave. As we see on the screenshot above, the reader prometheus metrics are available(the red line on the top left graph, red and yellow line on "memory usage" graph).

Restarting the reader Prometheus solves the issue and all the data is actually there (the 4 other prometheuses still send their data in the db) but the issue will re happen again after the same duration.
![prometheus_data_after_a_restart](https://user-images.githubusercontent.com/3977280/96198433-84547700-0ef0-11eb-8087-bcd1fbc1b99d.png)

Currently I can't identify the problem between Promscale or Prometheus. I didn't see a misconfiguration on my part, moreover, without the alerts the setup worked fine. I also tried to greatly increase the resources on the DB, promscale and the reader prometheus without any effects.

I have an archive with all the data I could get for troubleshooting (resources consumption, logs, prometheus configuration extracted from container). I can send it in private message if needed.

**Comment by jpigree** [comment]
Found a workaround, with a cronjob restarting my failing prometheus reader instance every 4 hours. Not clean but functional.

**Comment by cevian** [comment]
@jpigree have you tried connecting Grafana directly to Promscale? Promscale now supports all of the PromQL endpoint so a separate reader prometheus shouldn't be necessary. The newest tobs helm charts should already do that.

**Comment by jpigree** [comment]
@cevian, I didn't know we could do that. Great idea and it was so easy to do.

I had a bit more work since I moved my alert rules to the Prometheus instances in the swarm clusters, but, for now, everything works fine and I have one less component to maintain. Thank you so much.
