### ISSUE TITLE
Multinode compression policies

### ISSUE THREAD

**Issue by JLockerman** [timescale/promscale#347]
In PR #334 we added support for multinode metrics tables. However, these aren't yet ready for primetime as we do not yet support compression policies for distributed hypertables. This issue tracks that feature.

Open Questions:

- [x] do we implement our own compression policies or wait for upstream? (currently intend to implement our own)
- [ ] do we migrate non-multinode tables to use our custom policy?

**Comment by cevian** [comment]
This is done
