### ISSUE TITLE
Textual timestamps for JSON writes

### ISSUE THREAD

**Issue by JLockerman** [timescale/promscale#352]
Our current JSON write endpoint added in PR #345 uses integer timestamps as in
```JSON
{
    "labels":{"__name__": "cpu_usage", "namespace":"dev", "node": "brain"},
    "samples":[[1577836800000, 100],[1577836801000, 99],[1577836802000, 98]]
}
```
for human readability and writability it might pay to also accept textual timestamps in one of the go formats, e.g. (note times are different)
```JSON
{
    "labels":{"__name__": "cpu_usage", "namespace":"dev", "node": "brain"},
    "samples":[["2020/11/08 01:00:00", 100],["2020/11/08 01:00:30", 99],["2020/11/08 01:00:30", 98]]
}
```
This issue exists to track that potential feature.

**Comment by VineethReddy02** [comment]
closing this issue, as it's not a priority. :)
