### ISSUE TITLE
Implement metric metadata ingestion in catalog

### ISSUE THREAD

**Issue by Harkishen-Singh** [timescale/promscale#363]
The recent PR (#6815) at prometheus upstream adds support for sending prometheus metric metadata (metric type, unit, help text) over remote write component (via promb, see integration PR: #361 ). We should implement the same in our catalog or in hypertables.

cc @cevian

**Comment by franck102** [comment]
We would love to see this, we need the metric type to automate aggregation in Timescale.
We also need it to properly deal with counter resets for counters.

Currently we have a dedicated process looking up the metric types from Prometheus and injecting them into timescale.

**Comment by Harkishen-Singh** [comment]
This issue is being fixed by #624
