### ISSUE TITLE
Avoid possible loss of resolution when switching leaders

### ISSUE THREAD

**Issue by Harkishen-Singh** [timescale/promscale#369]
The current leader-election for HA configuration is such that once the leader stops receiving the samples from prometheus instance for a period of the timeout, it gives up the advisory-lock and the non-leader then after receiving its samples from its corresponding Prometheus attempts and takes the lock. This means the samples between the fall of leader to the rise of the non-leader are dropped.

We should prevent this by buffering possibly the samples in the non-leader instance for the time that is (timeout + prometheus scrape interval (assuming 30 seconds as ideal in clusters)) the timeout given for a shift of leader. This will assure that no samples are dropped.

**Comment by cevian** [comment]
Needs planning as depends on other HA features/considerations, like whether we will support label-based HA switchover like cortex

**Comment by VineethReddy02** [comment]
As this advisory lock-based HA approach is deprecated. closing this issue. @Harkishen-Singh feel free to re-open the issue. If you think this needs to be addressed.
