### ISSUE TITLE
Support Reading Prometheus WAL directly instead of Remote Write as a Sidecar to reduce memory usage

### ISSUE THREAD

**Issue by mitchellmaler** [timescale/promscale#370]
Today using the remote_write to promscale works but it does require prometheus to use more memory and direct network calls. One option seen with other similar projects is to read the Prometheus TSDB WAL directly to then process and ship out to an external store (here would be timescaledb). 

Do you think this is something that could be added to make deploying promscale as a sidecar easier and reduce prometheus resource usage?

remote_write memory usage: https://prometheus.io/docs/practices/remote_write/#memory-usage

**Comment by Harkishen-Singh** [comment]
Thank you for sharing your views @mitchellmaler. 25% increase in memory is significant. I will discuss this with the team.

**Comment by Harkishen-Singh** [comment]
@mitchellmaler we discussed about this. This method has possibilities of loosing data in case of a crash, which is something not desirable. Still, I think is something `nice to have` in future if more people request for it. Thank you very much for giving your suggestion.

**Comment by mitchellmaler** [comment]
I am curious on how this differs from today using remove_write, where if Prometheus crashed that promscale would not get the data. Reading the WAL would give you the most us to date data up to the point of Prometheus stopped and in that case it is up to the user to make sure they have it deployed HA so it can tolerate crashes.

Using https://github.com/prometheus/prometheus/tree/master/tsdb/wal you could read the TSDB and keep it in memory/disk to be sent to Timescaledb. This would reduce the memory usage of Prometheus substantially and if it crashed you would be able to read up to the last write to the TSDB (using shared volume) and another HA Prometheus could take over if the threshold is met.

**Comment by Harkishen-Singh** [comment]
> Reading the WAL would give you the most us to date data up to the point of Prometheus stopped

WALs are flushed at a regular interval. If Prometheus comes down before that, then it will lose the data again. Remote-write works using wal reader, which means, as soon as a segment is written, it is streamed. This means that both have almost similar chances of loosing data and its amount.

> keep it in memory/disk to be sent to Timescaledb

I agree, this has some advantages as well (low mem usage). Would be definitely good to have once we have the bandwidth.

**Comment by VineethReddy02** [comment]
closing this issue for now, as we haven't received multiple user requests. Sending data using `remote_write` has been the most widely used integration with Prometheus. 

Would consider adding this to our backlog, if we receive more user requests/feedback to support reading from Prometheus WAL.

Thanks!
