### ISSUE TITLE
duplicate data in sample

### ISSUE THREAD

**Issue by jmvizcainoio** [timescale/promscale#371]
Hi I have deployed timescaledb using the helm chart and promscale also.
the values are by default 

When the installation is completed a can show metrics, after a fews minutes the ingest stops and promscale log this. 

```
...
level=warn ts=2020-12-04T11:55:16.545Z caller=sql_ingest.go:657 msg="duplicate data in sample" table=deployment_controller_rate_limiter_use duplicate_count=1 row_count=1
level=warn ts=2020-12-04T11:55:16.545Z caller=sql_ingest.go:657 msg="duplicate data in sample" table=cloudprovider_aws_api_request_duration_seconds_bucket duplicate_count=24 row_count=24
level=warn ts=2020-12-04T11:55:16.545Z caller=sql_ingest.go:657 msg="duplicate data in sample" table=pv_collector_unbound_pv_count duplicate_count=1 row_count=1
level=warn ts=2020-12-04T11:55:16.554Z caller=sql_ingest.go:657 msg="duplicate data in sample" table=cloudprovider_aws_api_request_duration_seconds_bucket duplicate_count=48 row_count=48
level=warn ts=2020-12-04T11:55:16.567Z caller=sql_ingest.go:657 msg="duplicate data in sample" table=rest_client_request_duration_seconds_bucket duplicate_count=8 row_count=8
...
```

The timescaled log this.
```
2020-12-04 12:05:33 UTC [31502]: [5fca260d.7b0e-4] postgres@prometheus,app=[unknown] [22021] STATEMENT:  SELECT * FROM _prom_catalog.get_or_create_series_id_for_kv_array($1, $2, $3)
2020-12-04 12:05:33 UTC [31505]: [5fca260d.7b11-3] postgres@prometheus,app=[unknown] [22021] ERROR:  invalid byte sequence for encoding "UTF8": 0x00
2020-12-04 12:05:33 UTC [31505]: [5fca260d.7b11-4] postgres@prometheus,app=[unknown] [22021] STATEMENT:  SELECT * FROM _prom_catalog.get_or_create_series_id_for_kv_array($1, $2, $3)
2020-12-04 12:05:33 UTC [31502]: [5fca260d.7b0e-5] postgres@prometheus,app=[unknown] [00000] LOG:  disconnection: session time: 0:00:00.030 user=postgres database=prometheus host=100.100.0.4 port=39916
2020-12-04 12:05:33 UTC [31505]: [5fca260d.7b11-5] postgres@prometheus,app=[unknown] [00000] LOG:  disconnection: session time: 0:00:00.024 user=postgres database=prometheus host=100.100.0.4 port=39922
2020-12-04 12:05:33 UTC [31503]: [5fca260d.7b0f-3] postgres@prometheus,app=[unknown] [22021] ERROR:  invalid byte sequence for encoding "UTF8": 0x00
2020-12-04 12:05:33 UTC [31503]: [5fca260d.7b0f-4] postgres@prometheus,app=[unknown] [22021] STATEMENT:  SELECT * FROM _prom_catalog.get_or_create_series_id_for_kv_array($1, $2, $3)
2020-12-04 12:05:33 UTC [31503]: [5fca260d.7b0f-5] postgres@prometheus,app=[unknown] [00000] LOG:  disconnection: session time: 0:00:00.030 user=postgres database=prometheus host=100.100.0.4 port=39918
2020-12-04 12:05:33 UTC [31463]: [5fca260b.7ae7-3] postgres@prometheus,app=[unknown] [22021] ERROR:  invalid byte sequence for encoding "UTF8": 0x00
2020-12-04 12:05:33 UTC [31463]: [5fca260b.7ae7-4] postgres@prometheus,app=[unknown] [22021] STATEMENT:  SELECT * FROM _prom_catalog.get_or_create_series_id_for_kv_array($1, $2, $3)
2020-12-04 12:05:33 UTC [31498]: [5fca260d.7b0a-3] postgres@prometheus,app=[unknown] [22021] ERROR:  invalid byte sequence for encoding "UTF8": 0x00
2020-12-04 12:05:33 UTC [31498]: [5fca260d.7b0a-4] postgres@prometheus,app=[unknown] [22021] STATEMENT:  SELECT * FROM _prom_catalog.get_or_create_series_id_for_kv_array($1, $2, $3)
2020-12-04 12:05:33 UTC [31498]: [5fca260d.7b0a-5] postgres@prometheus,app=[unknown] [00000] LOG:  disconnection: session time: 0:00:00.277 user=postgres database=prometheus host=100.100.0.4 port=39906
2020-12-04 12:05:33 UTC [31463]: [5fca260b.7ae7-5] postgres@prometheus,app=[unknown] [00000] LOG:  disconnection: session time: 0:00:01.528 user=postgres database=prometheus host=100.100.0.4 port=39840
```

the logs was crazy printing the same output. 

If the data are duplicated is not inserted in timescale ? why i can`t see more data ? all samples are duplicated?

Thanks

**Comment by blagojts** [comment]
Hi, can you clear up some things for us:
1. Does ingest fail or you manually stop it?
2. Does promscale log any errors or just the duplicate warnings?
3. Where can't you see more data?

Regarding the duplicates, no they are not inserted, just the warning is logged

**Comment by jmvizcainoio** [comment]
Hi @blagojts 


> Hi, can you clear up some things for us:
> 
> 1. Does ingest fail or you manually stop it?

The ingest fail, i think that the problem is that promscale detect the duplicates and discard.

> 2. Does promscale log any errors or just the duplicate warnings?

Promscale just print duplicate and some

`level=warn ts=2020-12-04T14:00:50.750Z caller=write.go:81 msg="Error sending samples to remote storage" err="ERROR: invalid byte sequence for encoding \"UTF8\": 0x00 (SQLSTATE 22021)" num_samples=100`

> 3. Where can't you see more data?
When i deploy the timescale and promscale this work fine only few minutes,  after this promscale detect  duplicates and discard data.

For example in grafana i can only see 5 minutes of data. 

![image](https://user-images.githubusercontent.com/44993815/101172712-d472ce80-3641-11eb-823b-35f3e3cbc65f.png)

No more data is logged into timescaled when promscale detect the duplicates.

> Regarding the duplicates, no they are not inserted, just the warning is logged


Many thanks

**Comment by Harkishen-Singh** [comment]
Hey @jmvizcainoio , thank you for mentioning this. Are you ingesting into Promscale via Prometheus or you are using some other way for ingestion?

**Comment by Alaith** [comment]
I am experiencing the same promscale warnings. Prometheus has promscale configured as remote-storage; deployed with docker-compose. Hundreds of "duplicate data in sample" warnings per second from promscale.

I followed this docker-compose https://github.com/timescale/promscale/blob/master/build/docker-compose.yml

**Comment by jmvizcainoio** [comment]
> Hey @jmvizcainoio , thank you for mentioning this. Are you ingesting into Promscale via Prometheus or you are using some other way for ingestion?

Hi @Harkishen-Singh, yes i'm ingesting data from prometheus.

If I restart Prometheus everything seems to be working, but the duplicate data warning appears after a few seconds.

This is the log of promscale

```
level=info ts=2020-12-09T08:29:30.541Z caller=write.go:96 msg="Samples write throughput" samples/sec=966
level=info ts=2020-12-09T08:29:31.267Z caller=write.go:96 msg="Samples write throughput" samples/sec=41285
level=info ts=2020-12-09T08:29:31.327Z caller=write.go:96 msg="Samples write throughput" samples/sec=389
level=info ts=2020-12-09T08:29:31.506Z caller=write.go:96 msg="Samples write throughput" samples/sec=397
level=info ts=2020-12-09T08:29:35.692Z caller=write.go:96 msg="Samples write throughput" samples/sec=6563
level=info ts=2020-12-09T08:29:36.528Z caller=write.go:96 msg="Samples write throughput" samples/sec=31608
level=info ts=2020-12-09T08:29:36.794Z caller=write.go:96 msg="Samples write throughput" samples/sec=145
level=info ts=2020-12-09T08:29:36.858Z caller=write.go:96 msg="Samples write throughput" samples/sec=146
level=info ts=2020-12-09T08:29:37.643Z caller=write.go:96 msg="Samples write throughput" samples/sec=143
level=info ts=2020-12-09T08:29:38.754Z caller=write.go:96 msg="Samples write throughput" samples/sec=869
level=warn ts=2020-12-09T08:29:39.357Z caller=sql_ingest.go:657 msg="duplicate data in sample" table=ALERTS duplicate_count=1 row_count=3
level=info ts=2020-12-09T08:29:39.607Z caller=write.go:96 msg="Samples write throughput" samples/sec=3515
level=warn ts=2020-12-09T08:29:40.274Z caller=sql_ingest.go:657 msg="duplicate data in sample" table=ALERTS_FOR_STATE duplicate_count=1 row_count=1
level=info ts=2020-12-09T08:29:40.528Z caller=write.go:96 msg="Samples write throughput" samples/sec=431
level=info ts=2020-12-09T08:29:41.770Z caller=write.go:96 msg="Samples write throughput" samples/sec=3284
level=info ts=2020-12-09T08:29:42.653Z caller=write.go:96 msg="Samples write throughput" samples/sec=6538
level=info ts=2020-12-09T08:29:44.097Z caller=write.go:96 msg="Samples write throughput" samples/sec=551
level=info ts=2020-12-09T08:29:44.928Z caller=write.go:96 msg="Samples write throughput" samples/sec=626
level=info ts=2020-12-09T08:29:45.662Z caller=write.go:96 msg="Samples write throughput" samples/sec=337
level=info ts=2020-12-09T08:29:46.711Z caller=write.go:96 msg="Samples write throughput" samples/sec=982
level=info ts=2020-12-09T08:29:47.767Z caller=write.go:96 msg="Samples write throughput" samples/sec=385
level=info ts=2020-12-09T08:29:48.547Z caller=write.go:96 msg="Samples write throughput" samples/sec=4275
level=warn ts=2020-12-09T08:29:49.224Z caller=write.go:81 msg="Error sending samples to remote storage" err="ERROR: invalid byte sequence for encoding \"UTF8\": 0x00 (SQLSTATE 22021)" num_samples=539
level=warn ts=2020-12-09T08:29:49.225Z caller=write.go:81 msg="Error sending samples to remote storage" err="ERROR: invalid byte sequence for encoding \"UTF8\": 0x00 (SQLSTATE 22021)" num_samples=545
level=warn ts=2020-12-09T08:29:49.226Z caller=write.go:81 msg="Error sending samples to remote storage" err="ERROR: invalid byte sequence for encoding \"UTF8\": 0x00 (SQLSTATE 22021)" num_samples=543
level=warn ts=2020-12-09T08:29:49.235Z caller=write.go:81 msg="Error sending samples to remote storage" err="ERROR: invalid byte sequence for encoding \"UTF8\": 0x00 (SQLSTATE 22021)" num_samples=542
level=warn ts=2020-12-09T08:29:49.333Z caller=sql_ingest.go:657 msg="duplicate data in sample" table=kubelet_pod_worker_start_latency_microseconds duplicate_count=1 row_count=1
level=warn ts=2020-12-09T08:29:49.335Z caller=sql_ingest.go:657 msg="duplicate data in sample" table=node_filesystem_free_bytes duplicate_count=1 row_count=1
level=warn ts=2020-12-09T08:29:49.335Z caller=sql_ingest.go:657 msg="duplicate data in sample" table=kube_deployment_metadata_generation duplicate_count=1 row_count=1
level=warn ts=2020-12-09T08:29:49.336Z caller=sql_ingest.go:657 msg="duplicate data in sample" table=node_network_device_id duplicate_count=1 row_count=1
level=warn ts=2020-12-09T08:29:49.336Z caller=sql_ingest.go:657 msg="duplicate data in sample" table=pg_settings_default_with_oids duplicate_count=1 row_count=1
level=warn ts=2020-12-09T08:29:49.337Z caller=sql_ingest.go:657 msg="duplicate data in sample" table=node_memory_Hugepagesize_bytes duplicate_count=1 row_count=1
level=warn ts=2020-12-09T08:29:49.338Z caller=sql_ingest.go:657 msg="duplicate data in sample" table=kubelet_container_log_filesystem_used_bytes duplicate_count=1 row_count=1
level=warn ts=2020-12-09T08:29:49.338Z caller=sql_ingest.go:657 msg="duplicate data in sample" table=etcd_mvcc_hash_duration_seconds_bucket duplicate_count=1 row_count=1
level=warn ts=2020-12-09T08:29:49.339Z caller=sql_ingest.go:657 msg="duplicate data in sample" table=prometheus_http_request_duration_seconds_bucket duplicate_count=2 row_count=2
level=warn ts=2020-12-09T08:29:49.339Z caller=sql_ingest.go:657 msg="duplicate data in sample" table=kube_secret_created duplicate_count=6 row_count=6
``` 

Prometheus log 

```
ts=2020-12-09T08:34:49.570Z caller=dedupe.go:112 component=remote level=warn remote_name=20ab66 url=http://promscale-connector.promscale.svc.cluster.local:9201/write msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: ERROR: invalid byte sequence for encoding \"UTF8\": 0x00 (SQLSTATE 22021)
```

Thanks

Juanma

**Comment by cevian** [comment]
I think the underlying error is `ERROR: invalid byte sequence for encoding \"UTF8\": 0x00 (SQLSTATE 22021)` Can @VineethReddy02 or @Harkishen-Singh or @antekresic take a look?

**Comment by Harkishen-Singh** [comment]
@jmvizcainoio and @Alaith for informing and providing the details. We will take a look into this shortly. Thank you very much.

**Comment by Harkishen-Singh** [comment]
Not sure, but I feel like there is some issue with the source of data.

**Comment by Alaith** [comment]
> Not sure, but I feel like there is some issue with the source of data.

I'm not familiar enough with how Prometheus scrapes data and ships it to remote storage to judge.

My prometheus.yml was simply statically configured to monitor: itself, node-exporter, and cAdvisor. I'm using the latest version of Prometheus, latest node_exporter, and cAdvisor v0.38.6.

```
remote_write:
    - url: "http://promscale-connector:9201/write"
remote_read:
    - url: "http://promscale-connector:9201/read"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'cAdvisor'
    static_configs:
      - targets: ['cadvisor:8080']
```

**Comment by jmvizcainoio** [comment]
> @jmvizcainoio and @Alaith for informing and providing the details. We will take a look into this shortly. Thank you very much.

@Harkishen-Singh Great, If you need more info about the prometheus / promscale config let me know. 

Thanks

**Comment by VineethReddy02** [comment]
Hi @jmvizcainoio 

We think that the labels you are ingesting aren't UTF-8 encoding. Can you please ensure that all the label keys, label values  & metric names are UTF-8 encoded.

**Comment by jmvizcainoio** [comment]
Hi @VineethReddy02 


I checked all job_names in prometheus and the error was on `kube-controller-manager` metrics.

Kube controller manager are exposing a metric with a incorrect value. 

```
# HELP node_collector_evictions_number [ALPHA] Number of Node evictions that happened since current instance of NodeController started.
# TYPE node_collector_evictions_number counter
node_collector_evictions_number{zone="eu-central-1:�:eu-central-1a"} 69
# HELP node_collector_unhealthy_nodes_in_zone [ALPHA] Gauge measuring number of not Ready Nodes per zones.
# TYPE node_collector_unhealthy_nodes_in_zone gauge
node_collector_unhealthy_nodes_in_zone{zone="eu-central-1:�:eu-central-1a"} 0
# HELP node_collector_zone_health [ALPHA] Gauge measuring percentage of healthy nodes per zone.
# TYPE node_collector_zone_health gauge
node_collector_zone_health{zone="eu-central-1:�:eu-central-1a"} 100
# HELP node_collector_zone_size [ALPHA] Gauge measuring number of registered Nodes per zones.
# TYPE node_collector_zone_size gauge
node_collector_zone_size{zone="eu-central-1:�:eu-central-1a"} 16
```

I have disabled the controller metrics and now promscale works perfect.
Thanks

**Comment by VineethReddy02** [comment]
We noticed the root cause of `level=warn ts=2020-12-09T08:29:49.339Z caller=sql_ingest.go:657 msg=" duplicate data in sample" table=kube_secret_created duplicate_count=6 row_count=6`

This is because of cAdvisor exposes the timestamps along with values whereas other exporters will handover the task of attaching timestamps to Prometheus. When prometheus scrapes the cAdvisor target there can be a case where cAdvisor exposes the same samples which is causing a `duplicate samples` warning log at promscale level.  But this shouldn't be an issue as it just logs warnings (we will be addressing this soon).

**Comment by heigumjo** [comment]
Hi,
just want to inform you of a dirty fix that seem to work in case that helps in any way.

We are experiencing this issues as well. I have tried omitting various metrics to no avail. We have tried running timescale both internally and in a separate vm. Currently running timescale in a vm external from the cluster.

The cluster is small (3 vms, 60 ish pods running at any given time)

What we have observed is the duplicate warnings (a lot of them) and in the various dashboards in Grafana we see large gaps in the timeseries for all the metrics.

However after observing this for some time I noticed that PromScale starts quite quickly and seems to exit gracefully when you stop it. I made a cron job that redeploys PromScale every 5 minutes.

I have had this running now for a week, and everything seem to be working just fine.

I have installed everything through [tobs](https://github.com/timescale/tobs) whit some minor modifications (0.1.4).

**Comment by Harkishen-Singh** [comment]
@heigumjo, just wanted to inform you that the release 0.2.0 solves for too much logging. I don't know about exits but we prevent duplicate data in the table at all cost. So, if there are gaps, then I guess it is a duplicate and maybe, you may check if honor_timestamps is false or not.

**Comment by heigumjo** [comment]
@Harkishen-Singh I'll upgrade later this week and give it a try, thanks for the tip.

**Comment by Harkishen-Singh** [comment]
@jmvizcainoio can you please try to use the release 0.2.0 and see whether issues are still being faced? We did fix too much duplicate logging issue.

**Comment by Alaith** [comment]
Hello,
With the latest updates I am no longer experiencing this issue. Thank you for the fix!
