### ISSUE TITLE
promscale has problems checking some postgresql versions

### ISSUE THREAD

**Issue by hacker** [timescale/promscale#372]
namely, if a version component consists solely of zeroes it strips one too many zeroes leaving nothing to parse. The fix would be for instance this:

```diff
diff --git a/pkg/pgmodel/extension.go b/pkg/pgmodel/extension.go
index 5009a91..a5d93ae 100644
--- a/pkg/pgmodel/extension.go
+++ b/pkg/pgmodel/extension.go
@@ -289,5 +289,9 @@ func getNewExtensionVersion(extName string,

 // trimLeadingZeros removes the leading zeros passed in the version number.
 func trimLeadingZeros(s string) string {
-       return strings.TrimLeft(s, "0")
+       rv := strings.TrimLeft(s, "0")
+       if rv == "" {
+               rv = "0"
+       }
+       return rv
 }
```

Or, given the component is at most two digits, `.TrimPrefix(s,"0")` could be used, but then the `trimLeadingZeros()` name would be inaccurate.

**Comment by cevian** [comment]
@Harkishen-Singh since you wrote this code can you take a look?

**Comment by Harkishen-Singh** [comment]
@hacker thank you for pointing this out. The solution that you suggested is good. Would you like to submit a PR for this?

**Comment by hacker** [comment]
Sure, here you go #392

**Comment by antekresic** [comment]
PR merged, issue resolved. Thanks again!
