### ISSUE TITLE
reset_metric_retention_period updates all records in metric table, not only specified metric

### ISSUE THREAD

**Issue by DMOsipov** [timescale/promscale#401]
`SELECT id FROM SCHEMA_CATALOG.get_metric_table_name_if_exists(metric_name)`

`metric_name` should be prefixed with function name. Otherwise the column `metric_name` is used here and all rows in the table are updated.

`SELECT id FROM SCHEMA_CATALOG.get_metric_table_name_if_exists(reset_metric_retention_period.metric_name)`

**Comment by VineethReddy02** [comment]
Hi @DMOsipov 

To reset metric retention specific to a metric use the below SQL cmd

`SELECT prom_api.reset_metric_retention_period(container_cpu_usage_seconds_total)`

TO update retention specific to a metric use

`SELECT prom_api.set_metric_retention_period(container_cpu_usage_seconds_total, INTERVAL '1 day' * 2)`

**Comment by cevian** [comment]
Hi @DMOsipov I found the issue and solve it in #414. Thanks a lot for the report
