### ISSUE TITLE
Promscale extension version is behind TimescaleDB version

### ISSUE THREAD

**Issue by ali-ghasempor** [timescale/promscale#402]
Hello,

I recently updated my TimescaleDB to [latest available version](https://github.com/timescale/timescaledb/releases/tag/2.0.0) (2.0.0), and I'm running on promscale version 0.1.3. However Promscale is unable to update extension and migrate data in TimescaleDB. I suspected that, new release of Promscale is needed to be compatible with TSDB v2.0.0. 
Following are details of setup:
Timescale extension version on TSDB:
Using image: timescale/timescaledb:2.0.0-pg12
```    
                                  List of installed extensions
    Name     | Version |   Schema   |                            Description                            
-------------+---------+------------+-------------------------------------------------------------------
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 2.0.0   | public     | Enables scalable inserts and complex queries for time-series data
```
Promscale connector output:
Using image: timescale/promscale:0.1.3
```
level=info ts=2020-12-29T07:18:20.504Z caller=runner.go:125 msg="Version:0.1.3; Commit Hash: "
level=info ts=2020-12-29T07:18:20.504Z caller=runner.go:126 config="&{ListenAddr::9201 TelemetryPath:/metrics PgmodelCfg:{Host:**** Port:**** User:***** password:**** Database:**** SslMode:disable DbConnectRetries:10 AsyncAcks:false ReportInterval:0 LabelsCacheSize:10000 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:4 MaxConnections:-1 UsesHA:false} LogCfg:{Level:debug Format:logfmt} HaGroupLockID:0 PrometheusTimeout:-1ns ElectionInterval:5s Migrate:true StopAfterMigrate:false UseVersionLease:true CorsOrigin:^(?:.*)$ InstallTimescaleDB:true ReadOnly:false AdminAPIEnabled:false}"
level=error ts=2020-12-29T07:18:20.559Z caller=runner.go:136 msg="aborting startup due to error" err="could not install timescaledb: the extension at a greater version than supported by the connector: 2.0.0 > 2.0.0-rc4"
```
For reproduce error, basically just install TSDB v2.0.0 and try connect with promscale v0.1.3.

**Comment by VineethReddy02** [comment]
Hi @ali-ghasempor 

We have noticed this issue recently. For now, promscale doesn't support TimescaleDB 2.0.0 multi-node so this needs some work that needs to get into promscale. I would suggest you to use a lower version of timescaleDB for time being. We will be releasing the promscale soon with the fix.

**Comment by VineethReddy02** [comment]
Promscale **0.1.4** is released it addresses this issue https://github.com/timescale/promscale/releases/tag/0.1.4 

I am closing the issue for now.
