### ISSUE TITLE
The timescaledb is the same as promscale-extension, right?

### ISSUE THREAD

**Issue by max-tian** [timescale/promscale#418]
`timescaledev/promscale-extension:latest-pg12`
and
`timescale/timescaledb:latest-pg12`

Are they the same one?

**Comment by VineethReddy02** [comment]
Hi @max-tian 

The `timescale/timescaledb:latest-pg12` only contains TimescaleDB extension whereas `timescaledev/promscale-extension:latest-pg12` contains the TimescaleDB along with Promscale extension (the promscale ext is optional but we recommend to use it, as it contains support functions to improve the performance of Promscale.) 

More details on Promscale extension can be found [here](https://github.com/timescale/promscale_extension)

**Comment by max-tian** [comment]
> Hi @max-tian
> 
> The `timescale/timescaledb:latest-pg12` only contains TimescaleDB extension whereas `timescaledev/promscale-extension:latest-pg12` contains the TimescaleDB along with Promscale extension (the promscale ext is optional but we recommend to use it, as it contains support functions to improve the performance of Promscale.)
> 
> More details on Promscale extension can be found [here](https://github.com/timescale/promscale_extension)

Thank you very much! 👍
