### ISSUE TITLE
Custom metrics support

### ISSUE THREAD

**Issue by pratapagiri** [timescale/promscale#421]
> [Question]

 Is it possible to ingest and query custom metrics in Promscale?

**Comment by Harkishen-Singh** [comment]
@pratapagiri, yes it is possible. You can directly push your metrics manually via https://github.com/timescale/promscale/blob/master/docs/writing_to_promscale.md or configure Prometheus to scrape and push metrics for you via remote-write.

**Comment by pratapagiri** [comment]
Thanks @Harkishen-Singh
