### ISSUE TITLE
Parser error on TimescaleDB extension when installed from source

### ISSUE THREAD

**Issue by k-rus** [timescale/promscale#436]
When TimescaleDB is built from source it might contain versions, which don't follow semver. For example, I built master and 1.7.x branches and installed them, and as result the extension versions are:
```
select version FROM pg_available_extension_versions where name = 'timescaledb';
   version
-------------
 2.0.0-dev
 mock-broken
 1.7.5
 2.1.0-dev
 2.0.0
 0.0.0
 mock-5
 mock-6
 mock-3
 mock-4
 mock-1
 mock-2
(12 rows)
```
This results in a parser error when I try to run a test:
```
main_test.go:120: could not install timescaledb: Could not parse available extra extension version mock-broken: No Major.Minor.Patch elements found
```
In my case I was running local installation of TimescaleDB from source and tried to reproduce an issue according https://github.com/timescale/timescaledb/issues/2575#issuecomment-763618127
The command was:
```
go test -run TestSQLDrop ./pkg/pgmodel/end_to_end_tests -use-docker=false -use-extension=false
```

**Comment by cevian** [comment]
mock-broken is not a valid semver version. This only comes up if you have a dev version of timescaledb installed. But we should make exceptions for these

**Comment by k-rus** [comment]
@cevian Thank you for checking. So I incorrectly identified the version, which caused the parser error. The list of version of timescaledb when I install from source:
```
 2.0.0-dev
 mock-broken
 1.7.5
 2.1.0-dev
 2.0.0
 0.0.0
 mock-5
 mock-6
 mock-3
 mock-4
 mock-1
 mock-2
(12 rows)
```
My apology for the confusion. I will update my issue.
