### ISSUE TITLE
Cache Metrics Should Be Gauges

### ISSUE THREAD

**Issue by jnadler** [timescale/promscale#437]
Promscale exposes metrics for the number of cached metric names and labels.   These are currently counters, but should probably be gauges:

https://github.com/timescale/promscale/blob/f6a700b19f78be5f1499567a7d98028475e7a64f/pkg/pgclient/metrics.go#L25

https://github.com/timescale/promscale/blob/f6a700b19f78be5f1499567a7d98028475e7a64f/pkg/pgclient/metrics.go#L41

**Comment by jnadler** [comment]
i'm happy to PR this if you all agree

**Comment by Harkishen-Singh** [comment]
@jnadler thank you for pointing this out. We would be happy to receive PR from you. Thank you very much.

**Comment by cevian** [comment]
Thanks!
