### ISSUE TITLE
Problem accepting data from netdata

### ISSUE THREAD

**Issue by oleotiger** [timescale/promscale#441]
Promscale is metioned to be an excellent adapter for prometheus remote write to timescaledb in netdata document. When I use timescaledb as database to store metrics through promscale, I get error message like:
```
level=error ts=2021-01-15T06:20:50.557Z caller=write.go:239 msg="Write header validation error" err="unsupported data format (not protobuf or json)"
```

How could I debug this error?

**Comment by cevian** [comment]
@oleotiger this error implies that netdata isn't sending a `"Content-Type": "application/x-protobuf"` header. Can you point me to the netdata prometheus remote_write sending code?

**Comment by oleotiger** [comment]
> @oleotiger this error implies that netdata isn't sending a `"Content-Type": "application/x-protobuf"` header. Can you point me to the netdata prometheus remote_write sending code?

This is how I set netdata export:
```
[prometheus_remote_write:netdata_remote_write]
    enabled = yes
    destination = localhost:9201
    remote write URL path = /metrics
    data source = as collected
    prefix = netdata
    hostname = xxx
    update every = 1
    buffer on failures = 10
```

And how I start promscale:`./promscale -db-user postgres -db-name netdata -db-password xxx --db-ssl-mode allow -db-port 5432 -db-host 127.0.0.1`

I didn't get what you mean by 'the netdata prometheus remote_write sending code'. The source code or the metrics send by netdata?

If source code, netdata is an open-source project in github which collect metrics  of the system. You can find exporting source code here: https://github.com/netdata/netdata/tree/master/exporting

If metrics, I have no idea how to print debug info of the sending metrics to screen.

**Comment by cevian** [comment]
FYI this was fixed by netdata https://github.com/netdata/netdata/pull/10560. Thank you @oleotiger for reporting this issue to them.
