### ISSUE TITLE
dial error (dial tcp 127.0.0.1:5432: connect: connection refused)

### ISSUE THREAD

**Issue by XiaoyuZhann** [timescale/promscale#448]
`level=error ts=2021-01-25T07:37:06.957Z caller=runner.go:110 msg="aborting startup due to error" err="failed to connect to 'host=localhost user=postgres database=timescale': dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"
level=info ts=2021-01-25T07:37:20.435Z caller=runner.go:103 msg="Version:0.1.1; Commit Hash: "
level=info ts=2021-01-25T07:37:20.435Z caller=runner.go:104 config="&{ListenAddr::9201 TelemetryPath:/metrics PgmodelCfg:{Host:localhost Port:5432 User:postgres password: **** SslMode:require DbConnectRetries:0 AsyncAcks:false ReportInterval:0 LabelsCacheSize:10000 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:4 MaxConnections:-1} LogCfg:{Level:debug Format:logfmt} HaGroupLockID:0 RestElection:false PrometheusTimeout:-1ns ElectionInterval:5s Migrate:true StopAfterMigrate:false UseVersionLease:true CorsOrigin:^(?:.*)$ InstallTimescaleDB:true}"`

[docker-compose.txt](https://github.com/timescale/promscale/files/5871844/docker-compose.txt)

**Comment by VineethReddy02** [comment]
Hi @XiaoyuZhann 
Do you mind sharing the above docker-compose file with the correct indentation? To try out your setup.  Also, the issue looks like a problem in your configuration as `Promscale` couldn't reach `TimescaleDB`. So can you re-verify the network configuration?

**Comment by XiaoyuZhann** [comment]
> 嗨@XiaoyuZhann
> 您是否介意使用正确的缩进共享上述docker -compose文件？尝试设置。此外，这个问题看起来像你的配置问题，因为`Promscale`无法达到`TimescaleDB`。那么您可以重新验证网络配置吗？

version: '3.0'

services:
  timescaledb:
    container_name: timescaledb
    image: timescaledev/promscale-extension:latest-pg12
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: timescale
    networks:
      prometheus_environment:
        ipv4_address: 172.20.0.2
        aliases:
          - timescaledb

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090/tcp
    volumes:
      - /home/prometheus:/etc/prometheus
    networks:
      prometheus_environment:
        aliases:
          - prometheus

  pushgateway:
    container_name: pushgateway
    image: prom/pushgateway:latest
    ports:
      - 9091:9091
    networks:
      prometheus_environment:
        aliases:
          - pushgateway

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000/tcp
    networks:
      prometheus_environment:
        aliases:
          - grafana

  timescale-promscale:
    container_name: timescale-promscale
    image: timescale/promscale:latest
    ports:
      - 9201:9201/tcp
    build:
      context: .
    restart: on-failure
    depends_on:
      - timescaledb
      - prometheus
    environment:
      PROMSCALE_DB_CONNECT_RETRIES: 10
      PROMSCALE_DB_HOST: 172.20.0.2:5432
      PROMSCALE_DB_PASSWORD: password
      PROMSCALE_DB_SSL_MODE: allow
    networks:
      prometheus_environment:
        aliases:
          - timescale-promscale

networks:
  prometheus_environment:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

**Comment by XiaoyuZhann** [comment]
> 嗨@XiaoyuZhann
> 您是否介意使用正确的缩进共享上述docker -compose文件？尝试设置。此外，这个问题看起来像你的配置问题，因为`Promscale`无法达到`TimescaleDB`。那么您可以重新验证网络配置吗？



> Hi @XiaoyuZhann
> Do you mind sharing the above docker-compose file with the correct indentation? To try out your setup. Also, the issue looks like a problem in your configuration as `Promscale` couldn't reach `TimescaleDB`. So can you re-verify the network configuration?

Sorry, I uploaded the file, you can help me see

**Comment by XiaoyuZhann** [comment]
> Hi @XiaoyuZhann
> Do you mind sharing the above docker-compose file with the correct indentation? To try out your setup. Also, the issue looks like a problem in your configuration as `Promscale` couldn't reach `TimescaleDB`. So can you re-verify the network configuration?

Sorry, I uploaded the file, you can help me see
