### ISSUE TITLE
ARM docker image

### ISSUE THREAD

**Issue by Samaaraam** [timescale/promscale#460]
I'm using promscale in a AMD machine and wanted to run in in a ARM machine too but I couldn't find an ARM docker image,

**Comment by cevian** [comment]
I believe there is a community image provided here https://hub.docker.com/r/fibbsanton/promscale/tags?page=1&ordering=last_updated 

We'll look into creating an official one for the next release

**Comment by mrMoe** [comment]
Hi. This seems to be only an arm64 image. Is there any change you'd provide an normal arm v6 or v7 image like timescaledb?

**Comment by chintanp** [comment]
@cevian any suggestions about how to make this work on armv7 as requested by @mrMoe ? 

@mrMoe were you able to make this work? I have a similar requirement.

**Comment by mrMoe** [comment]
nah I switched back to a amd64 architecture because of memory issues with timescale itself
