### ISSUE TITLE
How to set retention period to infinite?

### ISSUE THREAD

**Issue by oleotiger** [timescale/promscale#464]
As described in [Data Model Schema](https://github.com/timescale/promscale/blob/master/docs/sql_schema.md), I can change retention period to 180 days with `SELECT set_default_retention_period(180 * INTERVAL '1 day')`.

What value can I set if retention period is infinite? -1?

**Comment by cevian** [comment]
We don't have an infinite setting right now. would something like `SELECT prom_api.set_default_retention_period(INTERVAL '10000 years')` not work for you?

**Comment by oleotiger** [comment]
Yeah,it works for me. Hahahaha

**Comment by Harkishen-Singh** [comment]
Closing this.
