### ISSUE TITLE
Expose prom-migrator version

### ISSUE THREAD

**Issue by VineethReddy02** [timescale/promscale#472]
While using prom-migrator. I do not see any version in prom-migrator. 

Exposing the current prom-migrator version would be great to understand issues faced by the users in a specific version.   

Suggestions:
1. Log version on migration startup. 
2. Also, add a version flag or CMD i.e `./prom-migrator --version` or `./prom-migrator version` which exposes the version of prom-migrator.

**Comment by niconosenzo** [comment]
Hi @VineethReddy02 , I'm wondering if it should match the `promscale` cli pattern of printing out the version when no argument is passed, or it should implement the `--version` flag.
