### ISSUE TITLE
Too many open file

### ISSUE THREAD

**Issue by oleotiger** [timescale/promscale#479]
When exporting metrics of netdata with promscale (time interval = 1s), I got errors `too many open file`.

There are 8 nodes exporting metrics with prometheus remote write with promscale to timescaledb. And metrics are collected and exported at 1Hz at all nodes.

Promscale works well for a while and errors occur.

I find the process and count fd of promscale. It's 1025.

`ulimit -a` shows 
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1537338
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1537338
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

I can set larger open fd number. But I don't think it's the proper solution. The file descriptor used by promscale is increasing until it reaches the limit.

When there are lots of node exporting metrics, how can I control the pressure of promscale?

Is there any distributed/load-balance way  to deploy promscale and timescaledb?

**Comment by cevian** [comment]
In general golang programs tend to use a lot of fds. This isn't an issue on modern systems. But we will look more into whether it's possible to reduce this
