### ISSUE TITLE
Implement a way to rename ingested metric

### ISSUE THREAD

**Issue by deathwarrior60** [timescale/promscale#493]
Hello,

We added a metrics with the wrong metric name, we put "my.awesome.metric{}" instead of "my_awesome_metrics{}".

Is there any ways in timescale to rename "my.awesome.metric" in "my_awesome_metrics" ? so we won't loose all data that were already sent with the wrong metric name.

If it is not possible,  is there a way to simply delete "my.awesome.metric" (delete all views, table, ...) ?

Regards

**Comment by Harkishen-Singh** [comment]
Hey @deathwarrior60, as of now, if you rename via SQL, there would be inconsistency with Promscale cache and the SQL db. But you can always delete the metric using the delete API. Please refer [here](https://github.com/timescale/promscale/blob/master/docs/metric_deletion_retention.md#deleting-data) for more information.

Maybe, renaming a metric can be a feature addition. I will put a label for this and if someone gets time, they can implement it.

**Comment by VineethReddy02** [comment]
closing this issue, as it doesn't align with the roadmap of Promscale, and we haven't seen the request to modify metric-name/value from a broader set of audiences.
