### ISSUE TITLE
Deleting a metrics via HTTP API

### ISSUE THREAD

**Issue by deathwarrior60** [timescale/promscale#494]
Hello,

I followed this [doc ](https://github.com/timescale/promscale/blob/master/docs/metric_deletion_retention.md#deleting-data) to delete a metric.
But only the data have been removed from timescale. 
Is there a way to also suppress all tables and views for that metric ?

Regards

**Comment by Harkishen-Singh** [comment]
This PR takes care of that. https://github.com/timescale/promscale/pull/420 (You can run those SQL queries from the PR if its urgent for you).
 
However, I think the delete HTTP API of Promscale should take care of this as well. Marking this as TODO.

**Comment by nohack** [comment]
@Harkishen-Singh Can I work on this ?

**Comment by Harkishen-Singh** [comment]
@nohack please feel free to go head. If you need any help, let me know.

**Comment by VineethReddy02** [comment]
closing this issue, as we haven’t received multiple requests from users for this feature and it's quite stale! :)

If you still have a need for this, Please open a new issue. If somebody is happy to contribute to this we are happy to accept the PR. 

Thanks!
