### ISSUE TITLE
Implement execute_maintenance through Promscale API?

### ISSUE THREAD

**Issue by deathwarrior60** [timescale/promscale#495]
Hello,

Is there a way to call execute_maintenance through the promscale http API instead of having to make a db connection to timescale ?

Regards

**Comment by Harkishen-Singh** [comment]
Right now there isn't any such way, but implementing it should be pretty simple. 
Please note that TimescaleDB 2.0 does not require this. It handles the maintenance without the need of cronjobs.

**Comment by zornwal** [comment]
>  Please note that TimescaleDB 2.0 does not require this. It handles the maintenance without the need of cronjobs.  

This might be worth mentioning in the [docker installation docs](https://github.com/timescale/promscale/blob/master/docs/docker.md)

**Comment by VineethReddy02** [comment]
Ideally, Promscale users do not have to run the `execute_maintenance` jobs anymore from TimescaleDB `2.0`, which is almost a year old. So now the maintenance jobs are executed automatically. 

closing this issue, as the users do not have to explicitly run the maintenance job.
