### ISSUE TITLE
Replace existing value in timescale

### ISSUE THREAD

**Issue by deathwarrior60** [timescale/promscale#497]
Hello,

Is there a way to replace an existing value in timescale ?

Use case :
Every 5 minutes, we compute the value of several metrics for the current day and we want to store it by day.
For example : we are the 2021-02-17 at 15h00.
So we sum all the data of metric1, metric2, metric3 from the 2021-02-17 at 00h00 to the 2021-02-17 at 15h00 and send the result to promscale : 2021-02-17T00:00:00.000Z res my_result_metric{}
Then at 15h05 : 
we sum all the data of metric1, metric2, metric3 from the 2021-02-17 at 00h00 to the 2021-02-17 at 15h05 and send the result to promscale : 2021-02-17T00:00:00.000Z res my_result_metric{}

But currently promscale doesn't insert the metric if it already exists so we can't do that :/

Regards

**Comment by cevian** [comment]
That is currently not possible but we will keep this open as a feature request.

**Comment by VineethReddy02** [comment]
closing this issue, as it doesn't align with the roadmap of Promscale, and haven't heard this kind of metric use-cases from a broader audience.
