### ISSUE TITLE
Handling of encoding errors from PostgreSQL

### ISSUE THREAD

**Issue by mjf** [timescale/promscale#518]
*Promscale* should at least ignore errors from *PostgreSQL* or otherwise handle the cases when `NUL` (`0x00`) character is obtained from *Prometheus*. *Prometheus* accepts `NUL`s and stores them in its *WAL*. When you are in need to backfill data from the *Prometheus* *WAL* using *Prom-migrator*, *Promscale* dies providing the corresponding *PostgreSQL* error (i.e. `ERROR: invalid byte sequence for encoding \"UTF8\": 0x00 (SQLSTATE 22021)"` via *Promscale*). It also dies if `NUL` is written by *Prometheus* itself via remote write. While there is neither an easy way to erase data with `NUL`s from the *Prometheus* *WAL* nor any possibility to filter them out on *Promscale* or *Prom-migrator* side the errors from *PostgreSQL* about encoding errors should be ignored. There may be many exporters or tools that can potentionally write `NUL`s into *Prometheus* out there. It is therefor for further discussion whether the *UTF8* is the very best encoding for ingesting data that can potentionally contain `NUL`s anytime.

**Comment by cevian** [comment]
This should be fixed in #530 . WIll be in next (0.3.0) release

**Comment by Harkishen-Singh** [comment]
@mjf the 0.3.0 is out with the fix for null chars. Can you please update the issue whether you are facing the problem in the new release as well?
