### ISSUE TITLE
Missing SQLs files under extension folder

### ISSUE THREAD

**Issue by hserna74** [timescale/promscale#522]
Hello

I've got some problems trying to execute promscale

I've installed on CentOS 7.7 the next packages

timescaledb-tools-0.11.0-0.el7.x86_64
timescaledb-2-loader-postgresql-13-2.1.0-0.el7.x86_64
timescaledb-2-oss-postgresql-13-2.1.0-0.el7.x86_64
postgresql13-13.2-1PGDG.rhel7.x86_64
postgresql13-server-13.2-1PGDG.rhel7.x86_64
postgresql13-libs-13.2-1PGDG.rhel7.x86_64

The response when I execute promscale_0.2.0_Linux_x86_64 is:
./promscale_0.2.0_Linux_x86_64 -db-ssl-mode allow
...
...
InstallExtensions:true UpgradeExtensions:true UpgradePrereleaseExtensions:false}"
level=error ts=2021-03-10T12:33:04.931Z caller=runner.go:43 msg="aborting startup due to error" **err="could not install timescaledb: The timescaledb extension is not available at the right version, need version: >=1.7.3 <2.1.0 || >=1.7.0 <1.7.3 and the default version is 2.1.0 "**

The files that are under /usr/pgsql-13/share/extension/ only have timescaledb--2.1.0.sql or incremental sql files to upgrade from older versions to 2.1.0.

When I try to create an extension from pgsql with older versions than 2.1.0, that SQL file cannot be found

I tried to find a full sql file with right version (>=1.7.3 <2.1.0), to upload manually under extension folder, but I couldn't find it

I would be pleased if somebody could assist me with it.

Best regards

**Comment by cevian** [comment]
Release 0.2.1 should fix this issue. Please let us know if it did.

**Comment by hserna74** [comment]
Confirmed that the issue has been fixed.

Thanks
