### ISSUE TITLE
timescale/promscale:latest docker image is not version 0.2.1 but 0.2.0

### ISSUE THREAD

**Issue by Pizzahd88** [timescale/promscale#528]
After your release 8 hours ago I want to update to be able to use the newer timescaleDB 2.1.0.

I have tried to pull the promscale docker by the command: 'docker pull timescale/promscale:latest'
It resulted in the docker image running 0.2.0.
I have tried to pull the promscale docker by the command: 'docker pull timescale/promscale:0.2'
It resulted in the docker image running 0.2.0.

If I run the command 'docker pull timescale/promscale:0.2.1' 
It results in the correct 0.2.1 version.

To debug I tried on a clean install on a newly configured pc on another network (to eliminate caching in my internal network) running the command 'docker pull timescale/promscale:latest'
It resulted in image version 0.2.0.

It seems like the :latest and the :0.2 runs with image version 0.2.0.

Might it be that there is something finnicky with the :latest image? or is it on purpose it runs 0.2.0?
![image](https://user-images.githubusercontent.com/29568847/110777541-846b5f80-8261-11eb-8d8a-6ade45aba938.png)

**Comment by slavitch** [comment]
I have the same issue.  I replaced the contents in docker-compose as shown:

  promscale:
    image: timescale/promscale:0.2.1
    ports:
      - 9201:9201/tcp
#    build:
#      context: .
    restart: on-failure
    depends_on:
      - db
      - prometheus
    environment:
      PROMSCALE_DB_CONNECT_RETRIES: 10
      PROMSCALE_WEB_TELEMETRY_PATH: /metrics-text
      PROMSCALE_DB_URI: postgres://postgres:password@db:5432/postgres?sslmode=allow

**Comment by VineethReddy02** [comment]
Thanks for reporting this. We are looking into this issue.

**Comment by Pizzahd88** [comment]
This has been solved in the latest Docker version.
