### ISSUE TITLE
It takes less time to read remotely through Prometheus than through a connector

### ISSUE THREAD

**Issue by iwctwbai** [timescale/promscale#538]
<img width="468" alt="截屏2021-03-19 20 52 26" src="https://user-images.githubusercontent.com/48517790/111783435-31467c00-88f5-11eb-8246-ddfebefbbf9d.png">

Prometheus port is 9090 

The connector port is 9201 

But strangely enough, it takes less time to get through port 9090 than port 9021 

Prometheus' remote reading will return the original data and Prometheus will do the final aggregation. Why is 9090 less time consuming? 

The same request for port 9090 takes 500ms, and port 9021 takes 2500ms

Here is my request 

```
curl --location --request POST 'http://localhost:9090/api/v1/query_range' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'query=sum(ifHCOutOctets) by (__name__)' \
--data-urlencode 'start=2021-03-05T00:00:00+08:00' \
--data-urlencode 'end=2021-03-30T23:59:59+08:00' \
--data-urlencode 'step=5m' \
--data-urlencode 'timeout=5m' \
--data-urlencode '='
```
Thank you for your reply!

**Comment by iwctwbai** [comment]
<img width="468" alt="截屏2021-03-19 20 52 26" src="https://user-images.githubusercontent.com/48517790/111783435-31467c00-88f5-11eb-8246-ddfebefbbf9d.png">
I found it
Prometheus port is 9090
The connector port is 9201
But strangely enough, it takes less time to get through port 9090 than port 9021
Prometheus' remote reading will return the original data and Prometheus will do the final aggregation. Why is 9090 less time consuming?
Here is my request
```
curl --location --request POST 'http://localhost:9090/api/v1/query_range' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'query=sum(ifHCOutOctets) by (__name__)' \
--data-urlencode 'start=2021-03-05T00:00:00+08:00' \
--data-urlencode 'end=2021-03-30T23:59:59+08:00' \
--data-urlencode 'step=5m' \
--data-urlencode 'timeout=5m' \
--data-urlencode '='
```
Thank you for your reply!

**Comment by iwctwbai** [comment]
@Harkishen-Singh

**Comment by Harkishen-Singh** [comment]
@iwctwbai do you have read_recent enabled in Prometheus?

(Just to solve the speed thing. Will Investigate if Promscale is slow or not)

**Comment by iwctwbai** [comment]
@Harkishen-Singh  
I've already enabled it
The results should be very fast after aggregation,Look forward to your survey results.

**Comment by iwctwbai** [comment]
Did you find the problem @Harkishen-Singh

**Comment by Harkishen-Singh** [comment]
@iwctwbai I haven't had the chance to look into it. I will take a look soon and update it here, by this week or early next week. Really sorry for keeping you waiting.

**Comment by iwctwbai** [comment]
thank you @Harkishen-Singh

**Comment by Harkishen-Singh** [comment]
@iwctwbai I couldn't get any slowness (infact for me, Promscale was faster by few milliseconds).

Can you re-run that query using promtool?

Example:

For Prometheus
```shell
time ./promtool query range --start=1616919856 --end=1616923456 --step=1s http://localhost:9090 "sum(ifHCOutOctets) by (__name__)"
```

For Promscale
```shell
time ./promtool query range --start=1616919856 --end=1616923456 --step=1s http://localhost:9201 "sum(ifHCOutOctets) by (__name__)"
```

You can download promtool for Prometheus releases page. Please paste the value of  real in something like `real    0m0.100s`.

**Comment by iwctwbai** [comment]
@Harkishen-Singh 
Small data may not yield results

I think as opposed to Prometheus returning the raw data to the client for aggregation

In the case of big data, Promscale method of returning aggregate results directly should be much faster than Prometheus's

**Comment by Harkishen-Singh** [comment]
@iwctwbai yes that is true. Aggregations on our side should be fast (using push downs) but right now we do not have that enabled for all prom aggregation functions. This is a todo task and in near future, we will implement this. Right now, only delta has pushdowns support. This is the reason why it's almost same. In the slow ones should not be true as they are probably noise, which happens on prom side as well.
