### ISSUE TITLE
Authentication for Remote write is parsed but not processed with prom-migrator

### ISSUE THREAD

**Issue by lkashiwa** [timescale/promscale#553]
When migrating Prometheus to InfluxDB or Cortex with Authentication needed, the parameters are read and parsed but config ignores that.

~/prom-migrator$ ./prom-migrator -mint=1616997627 -progress-enabled=false -read-url=http://localhost:9090/api/v1/read -write-url=https://xxxxx/write -write-auth-username=xxxx -write-auth-password=yyyyyyy
level=info ts=2021-03-29T10:46:20.158Z caller=main.go:60 msg="&{prom-migrator 1616997627000 1616997627 1617014780000 1617014780 524288000 500MB 1 1 http://localhost:9090/api/v1/read https://xxxxx/write prom_migrator_progress  false {  } {xxxx yyyyyyy }}+"
level=info ts=2021-03-29T10:46:20.158Z caller=planner.go:78 msg="Resuming from where we left off is turned off. Starting at the beginning of the provided time-range."
level=info ts=2021-03-29T10:46:20.158Z caller=writer.go:74 msg="writer is up"
level=info ts=2021-03-29T10:46:20.158Z caller=shards.go:100 msg="shard-0 is active"
level=info ts=2021-03-29T10:46:20.158Z caller=reader.go:61 msg="reader is up"
progress: 0.350% | block-1 time-range: 1 mins | mint: 1616997627 | maxt: 1616997687 | time-range: 1 mins 100% |██████████████████████| ( 4/ 4B, 34.630 kB/s)
progress: 1.049% | block-1 time-range: 2 mins | mint: 1616997687 | maxt: 1616997807 | time-range: 2 mins 100% |██████████████████████| ( 4/ 4B, 22.119 kB/s):0s]
progress: 2.099% | block-1 time-range: 3 mins | mint: 1616997807 | maxt: 1616997987 | time-range: 3 mins 100% |██████████████████████| ( 4/ 4B, 47.988 kB/s):0s]
progress: 3.498% | block-1 time-range: 4 mins | mint: 1616997987 | maxt: 1616998227 | time-range: 4 mins 100% |██████████████████████| ( 4/ 4B, 50.016 kB/s):0s]
progress: 5.247% | block-1 time-range: 5 mins | mint: 1616998227 | maxt: 1616998527 | time-range: 5 mins 100% |██████████████████████| ( 4/ 4B, 62.400 kB/s):0s]
progress: 9.794% | block-2 time-range: 7 mins | mint: 1616998887 | maxt: 1616999307 | pulling (0/1) ...  28% |███████████                             |  [0s:0s]level=info ts=2021-03-29T10:46:20.605Z caller=shards.go:98 msg="shard-0 is inactive"
level=info ts=2021-03-29T10:46:20.605Z caller=writer.go:71 msg="writer is down"
level=error ts=2021-03-29T10:46:20.605Z caller=main.go:121 msg="running writer: remote-write run: server returned HTTP status 401 Unauthorized: {\"status\": \"error\", \"error\": \"no credentials provided\"}"

**Comment by grzesuav** [comment]
Fixed in https://github.com/timescale/promscale/pull/555

**Comment by Harkishen-Singh** [comment]
This should work after the merge of #555. @lkashiwa can you try again with the build from master? Feel free to re-open this issue if it still does not behave well.
