### ISSUE TITLE
Helm 2 support

### ISSUE THREAD

**Issue by oliverpjames** [timescale/promscale#56]
The `apiVersion` in `Chart.yaml` is set to `v2 `. This stops people with Helm 2 from using this chart.

When I change it to `v1` and use the chart seems to work. Is there a reason why it has been set to `v2`?
Could we change it to `v1` so people stuck on Helm 2 can use the chart?

**Comment by oliverpjames** [comment]
I would like to push a branch to fix this, and possibly some other bits, but I'm getting 

```
$ git push --set-upstream origin allow-helm-2
remote: Permission to timescale/timescale-prometheus.git denied to oliverpjames.
fatal: unable to access 'https://github.com/timescale/timescale-prometheus.git/': The requested URL returned error: 403
```

**Comment by blagojts** [comment]
@oliverpjames you need to open a PR from your own repo. You don't have permission to push directly to this repo

**Comment by cevian** [comment]
Sorry for letting this issue stagnate. Helm 3 has been out for a year so I am gonna close this issue. If people feel strongly please re-open this issue or file a new one.
