### ISSUE TITLE
Promscale + prom-migrator fails to compress chunks

### ISSUE THREAD

**Issue by bobobo1618** [timescale/promscale#561]
Steps to reproduce:

- Set up promscale (my particular command line is `./promscale -db-name prometheus -db-ssl-mode disable --upgrade-prerelease-extensions true`)
- Point Prometheus `remote_write` at promscale
- Run prom-migrator (my command line is `./prom-migrator -mint 1566619200 -read-url 'http://localhost:8086/api/v1/prom/read?db=prometheus' -write-url 'http://localhost:9201/write' -progress-metric-url 'http://localhost:9201/read' -concurrent-pulls 4 -concurrent-push 10`)
- Check compression: `SELECT COUNT(*), is_compressed FROM timescaledb_information.chunks GROUP BY is_compressed;`

Expected result: Most chunks are compressed.

Actual result: ~1000 out of 270000 chunks are compressed.

I'd like to check if there's a compression policy applied but as far as I can tell, there's no way to do so.

**Comment by bobobo1618** [comment]
Ah, I see that compression is enabled: `SELECT COUNT(*), compression_enabled FROM timescaledb_information.hypertables GROUP BY compression_enabled;`

But I can't see any way to determine the interval. It's been ~48h since most of my chunks were added but this is several years of data and my disk isn't large enough to support these data uncompressed.

**Comment by Harkishen-Singh** [comment]
Maybe, you can begin with `call execute_maintenance()`. This will start data compression and retention policies on existing data. (Provided you have sufficient background workers)

The manual way:

I think you can manually compress chunks that belong to a Metric table via `select compress_chunk(show_chunks('prom_data.<metric_name>'))`. This will compress all the chunks belonging to that metric hypertable.

If your metric name is too long, then you can fetch the actual table_name from `select table_name from _prom_catalog.metric where metric=<metric_name>` and supply the table_name in place of metric_name in the above compression query.

**Comment by bobobo1618** [comment]
Thanks for responding!

> Maybe, you can begin with call execute_maintenance(). This will start data compression and retention policies on existing data. (Provided you have sufficient background workers)

Unfortunately no luck there. It completed but there is no apparent effect on chunk compression.

> I think you can manually compress chunks that belong to a Metric table via select compress_chunk(show_chunks('prom_data.<metric_name>')). This will compress all the chunks belonging to that metric hypertable.

My tables are too big to do that unfortunately, the query runs out of shared memory.

I've settled with using GNU parallel to feed queries that compress individual chunks to psql. That worked.

This still leaves the problem that compression wasn't performed by default though. It's weird, because it seemed like it was and then it stopped (the following is a screenshot of my disk usage while the import was running):

![image](https://user-images.githubusercontent.com/707839/113436005-353dc800-93e4-11eb-8782-ed1d03a40af4.png)

**Comment by Harkishen-Singh** [comment]
I am not sure but it feels like background workers didn't do the job as they weren't fed with sufficient memory. With the shared parallel memory, that problem should resolve by itself in future.

cc @cevian

**Comment by cevian** [comment]
@bobobo1618 Thanks for the report. One initial question: What version of TimescaleDB are you using?

**Comment by bobobo1618** [comment]
I'm running Git master from a few days ago: https://github.com/timescale/timescaledb/commit/5c525bbf310b1712c55f07ee0d9065534f602202

A necessity since I'm also running PG13.

**Comment by Harkishen-Singh** [comment]
@bobobo1618 is this issue still valid?

**Comment by bobobo1618** [comment]
I suspect it was a result of https://github.com/timescale/promscale/issues/596
