### ISSUE TITLE
Non-superuser setup problems

### ISSUE THREAD

**Issue by andrejpodzimek** [timescale/promscale#562]
I have a PostgreSQL setup that serves multiple webs and other hobby projects. I’d like to use it for `promscale` as well, without running an extra PostgreSQL instance. Unfortunately, it seems that `promscale` assumes superuser privileges way too often. It also appears to assume unrestricted access to the whole cluster (instead of being constrainted to a specific database).

### It requires the `CREATEROLE` privilege (at least for initialization)

```
promscale[2505103]: level=error ts=2021-04-04T05:55:52.831Z caller=runner.go:43 msg="aborting startup due to error" err="migration error: Error while trying to migrate DB: Error encountered during migration: error executing migration script: name preinstall/001-users.sql, err ERROR: permission denied to create role (SQLSTATE 42501)"
```

So I gave it the `CREATEROLE` privilege. It apparently insisted on creating `prom_reader` and `prom_writer`. No problem with that, in general, but such initialization might be better suited for a separate tool or script rather than for the main “production” binary startup.

Also, it didn’t give the new roles (`prom_{reader,writer}`) any permissions on the database it was logging into (`db_promscale`) or any membership in the login role (`pguser_promscale`). Not sure how that’s supposed to work then. :question:

### It could not execute `CREATE EXTENSION` for some reason

The documentation [says](https://github.com/timescale/promscale_extension#installation) one should *not* create the extension manually. The extension was installed, configured in `postgresql.conf` and loaded. Nonetheless, I had to manually call `CREATE EXTENSION IF NOT EXSISTS promscale;`, because otherwise I was getting this:

```
promscale[2505119]: level=warn ts=2021-04-04T05:55:58.142Z caller=extension.go:58 msg="could not install promscale: ERROR: permission denied to create extension \"promscale\" (SQLSTATE 42501). continuing without extension"
```

The role `pguser_promscale` (the login role) has `CREATE` permissions on `db_promscale` (the database for `promscale` to use), so it should be able to create extensions.

(Or does one need to mark extensions *trusted* somehow somewhere? [This is mentioned](https://www.postgresql.org/docs/current/sql-createextension.html) in the docs, but it’s unclear to me what exactly needs to be done.)

Also, should one give the new roles, `prom_reader` and `prom_writer`, membership in the default role (`pguser_promscale` in my case)? Or vice versa?

**Comment by Harkishen-Singh** [comment]
cc @cevian

**Comment by andrejpodzimek** [comment]
With `0.3.0` it finally connects to PostgreSQL 13 and doesn’t fail. However, there’s yet another “non-superuser” issue (in addition to the two reported above):

```
promscale[1583049]: level=warn ts=2021-04-08T19:27:12.678Z caller=client.go:132 msg="Maximum background worker setting is too low for the number of databases in your system. Please increase your timescaledb.max_background_workers setting. See https://docs.timescale.com/latest/getting-started/configuring#workers for more information."
```

I don’t understand this log message. There is exactly one Promscale database. The (tens of) other databases on the same PostgreSQL instance are none of Promscale’s business. :wink:

I have `timescaledb.max_background_workers = 16` in my `postgresql.conf`, but apparently that’s not enough. (This is a 32-CPU machine, but because it serves many different purposes and the Promscale load will be negligible compared to the other running tasks, I don’t fancy setting all thread pools arbitrarily big.)

The following might be also related:

```
promscale[1583049]: level=warn ts=2021-04-08T19:27:12.687Z caller=config.go:162 msg="had to reduce the number of copiers due to connection limits: wanted 128, reduced to 25"
```

I’m not sure what “connection limits” are meant here. In particular, `max_connections` in `postgresql.conf` happens to be set to 128 in this case, but this may be referring to a different limit.

**Comment by cevian** [comment]
We'll put these issue on the plan for 0.4.0

**Comment by cevian** [comment]
Fix started in #587

**Comment by cevian** [comment]
Last PR resolving this should be #616 it will be included in the next release

**Comment by andrejpodzimek** [comment]
Thanks a lot for working on this. Is there any documentation on how to migrate from the old setup (the one with two roles that required a bit of manual tweaking) to the new setup? I assume I’ll need to give Promscale (temporarily) some extra `CREATEROLE` permissions so that it can update its configuration.

Also, #616 and related changes (still) seem to be using hardcoded database role names (e.g. `prom_admin`). This is rather inflexible on a PostgreSQL instance that serves tens of non-Promscale databases and uses a set of role naming conventions to make management easier. Something like a `role_name_prefix` parameter would be very helpful in this regard.

A fully fledged non-superuser setup should (also) make it possible to run multiple Promscale instances on one and the same PostgreSQL instance. This would be rather cumbersome with hardcoded role names. It may be feasible by manually grant the `prom_.*` roles permissions on multiple Promscale databases, but one could definitely achieve better isolation among PostgreSQL users (Promscale or other) by using distinct roles.

**Comment by cevian** [comment]
@andrejpodzimek All the role migration stuff should happen automatically when you upgrade Promscale and migrate the schema.

Hmm the role name prefix idea is an interesting one and I do see why it may be useful. It also doesn't quite seem straightforward to implement since we'd have to have protections against people accidentally trying to use different prefixes on different promscale instances, across migrations etc. Let me think about this.

**Comment by cevian** [comment]
Let's do the role prefix in a separate issue. Feel free to open a new issue for discussion of that feature request.
