### ISSUE TITLE
Database URIs are interpreted incorrectly

### ISSUE THREAD

**Issue by andrejpodzimek** [timescale/promscale#563]
### The Problem

The `dbname` item in a database URI appears to be ignored. The URI looks like this:

```
postgres:///?dbname=db_promscale&user=pguser_promscale&password=<CENSORED>&host=/run/postgresql/&port=5432&sslcert=/etc/promscale/postgres_client.crt&sslkey=/etc/promscale/postgres_client.key&sslmode=verify-full
```

(Side note: Yes, I do know that the SSL settings do **nothing** when combined with UNIX domain sockets (`host=/run/postgresql/`), but the setup will be moved to a separate system eventually, so I have proper client authentication ready. This is also why the `SSL off` note in log messages below is benign.)

The `error` message reveals a great deal of chaos:

```
promscale[2502030]: level=error ts=2021-04-04T05:43:34.048Z caller=runner.go:43 msg="aborting startup due to error" err="failed to connect to `host=/run/postgresql/ user=pguser_promscale database=`: server error (FATAL: no pg_hba.conf entry for host \"[local]\", user \"pguser_promscale\", database \"pguser_promscale\", SSL off (SQLSTATE 28000))"
```

* The URI says it clear: `dbname=db_promscale&user=pguser_promscale`
* Yet the `error` message says: **`user \"pguser_promscale\", database \"pguser_promscale\"`**.
  * `dbname` and `user` are (incorrectly) assumed to be the same.
  * There is a string manipulation issue in the error message, starting from `database=`.

### The Partial Workaround

I eventually managed to connect to the database by **not** using `PROMSCALE_DB_URI`. I set this instead:

```
PROMSCALE_DB_HOST="/run/postgresql/"
PROMSCALE_DB_PORT="5432"
PROMSCALE_DB_NAME="db_promscale"
PROMSCALE_DB_USER="pguser_promscale"
PROMSCALE_DB_PASSWORD="<CENSORED>"
PROMSCALE_DB_SSL_MODE="verify-full"
```

Unlike `PROMSCALE_DB_URI`, this^^^ works as expected and gets the `dbname` right (`Database:db_promscale`):

```
promscale[2512474]: level=info ts=2021-04-04T06:24:13.302Z caller=runner.go:33 config="&{ListenAddr::9201 PgmodelCfg:{AppName:promscale@0.2.1 Host:/run/postgresql/ Port:5432 User:pguser_promscale password:**** Database:db_promscale SslMode:verify-full DbConnectRetries:0 DbConnectionTimeout:1m0s AsyncAcks:false ReportInterval:0 LabelsCacheSize:10000 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:4 MaxConnections:-1 UsesHA:false DbUri:} LogCfg:{Level:debug Format:logfmt} APICfg:{AllowedOrigin:^(?:.*)$ ReadOnly:false AdminAPIEnabled:false TelemetryPath:/metrics Auth:0xc0000cf8b0 EnabledFeaturesList:[] MaxQueryTimeout:2m0s SubQueryStepInterval:1m0s} ConfigFile:config.yml TLSCertFile:/etc/promscale/fullchain.pem TLSKeyFile:/etc/promscale/privkey.pem HaGroupLockID:0 PrometheusTimeout:-1ns ElectionInterval:5s Migrate:true StopAfterMigrate:false UseVersionLease:true InstallExtensions:true UpgradeExtensions:true UpgradePrereleaseExtensions:false}"
```

The problem with this workaround is that (unlike `PROMSCALE_DB_URI`) it has *no way* to set `sslcert` and `sslkey` (for client certificate authentication), which will become an issue once I move the setup from local UNIX domain sockets to the network.

### The Ultimate Disappointment

* It connected at last. :+1:
* But then it didn’t work at all because of #542 (and also #562). :-1:

**Comment by VineethReddy02** [comment]
Hii @andrejpodzimek 

The DB-URI format provided isn't correct from your end. We expect the `--db-uri` flag value to be in this format `postgres://postgres:password@localhost:5432/timescale?sslmode=require` (the PostgreSQL official db-uri formats)

However, I tried to connect to DB using the similar to the db-uri you shared it worked with a small change in dbname parameter i.e. `--db-uri postgres:///postgres?user=postgres&password=password&host=localhost&port=5432`  

The format you provided isn't supported in the official [PostgreSQL docs ](https://www.postgresql.org/docs/9.3/libpq-connect.html#:~:text=31.1.,-1.2.&text=The%20general%20form%20for%20a,param1%3Dvalue1%26...%5D&text=Percent%2Dencoding%20may%20be%20used,words%20listed%20in%20Section%2031.1.)

In my local testing, the URI connection attempt (we use https://github.com/jackc/pgx as PostgreSQL go driver) is failed due to an invalid `dbname` parameter in the URI you shared. Below is the error noticed.

```
"failed to connect to `host=localhost user=postgres database=`: server error (FATAL: unrecognized configuration parameter \"dbname\" (SQLSTATE 42704))"
```

**Comment by Harkishen-Singh** [comment]
@andrejpodzimek we will be releasing 0.3.0 most probably this Tuesday. The issue related to 542 will be solved with that and for 562, we will update you.

**Comment by andrejpodzimek** [comment]
> The DB-URI format provided isn't correct from your end. We expect the `--db-uri` flag value to be in this format `postgres://postgres:password@localhost:5432/timescale?sslmode=require` (the PostgreSQL official db-uri formats)

According to [the documentation](https://www.postgresql.org/docs/current/libpq-connect.html), the URI syntax I’m using looks correct and no less “official” than its other forms. The key statement in the documentation:

> *Values that would normally appear in the hierarchical part of the URI can alternatively be given as named parameters.*

In particular, it does **not** say that the “hierarchical” part of the URI must be non-empty or that the `dbname` parameter must be in it (and not in the named parameters).

The “hierarchical” format happens to be more popular, but it has a flaw: It doesn’t support UNIX domain sockets too well. Section *31.1.1.2. Connection URIs* gives two examples of URIs with UNIX domain sockets, one with the “hierarchical” syntax and one with named parameters. Only the latter usually works: The need for `%2F` in the “hierarchical” URI will make it fail in certain implementations, because URL escapes in the URI are disallowed (at least in Go and Rust, IIRC).

> However, I tried to connect to DB using the similar to the db-uri you shared it worked with a small change in dbname parameter i.e. `--db-uri postgres:///postgres?user=postgres&password=password&host=localhost&port=5432`

So this basically leaves `dbname` in the “hierarchical” part of the URI and puts everything else into the named parameters. Yes, that appears to work for me, e.g. like this:

```
postgres:///db_promscale?user=pguser_promscale&password=<CENSORED>&host=/run/postgresql/&port=5432&...
```

> The format you provided isn't supported in the official [PostgreSQL docs ](https://www.postgresql.org/docs/9.3/libpq-connect.html#:~:text=31.1.,-1.2.&text=The%20general%20form%20for%20a,param1%3Dvalue1%26...%5D&text=Percent%2Dencoding%20may%20be%20used,words%20listed%20in%20Section%2031.1.)

And yet the exact same section you link to mentions that format (and named parameters in general). :wink: There is nothing on that page to suggest that named parameters are unsupported.

> In my local testing, the URI connection attempt (we use https://github.com/jackc/pgx as PostgreSQL go driver) is failed due to an invalid `dbname` parameter in the URI you shared. Below is the error noticed.

Interesting. Yet the `dbname` named parameter is documented by PostgreSQL and recognized without issues (at least) by
* Grafana
* Prometheus PostgreSQL Exporter
* courier-authlib (user account manager for Courier-MTA)
* JDBC

Anyway, keeping the `dbname` in the hierarchical part of the URI looks like a reasonable workaround.

**Comment by andrejpodzimek** [comment]
Maybe I should have filed this in [jackc/pgx](https://github.com/jackc/pgx) rather than here, because the “driver” library is responsible for the URI parsing.

I think I’ve found the bug. [It’s right here.](https://github.com/jackc/pgconn/blob/5daa019e4eb52df3409ebf17c83116b7c0e827e5/config.go#L253) That named parameter is called **`dbname`, not `database`**, according to PostgreSQL’s URI specification.

And indeed, this “works” (but it’s an invalid URI, with `database` instead of `dbname`):

```
postgres:///?database=db_promscale&user=pguser_promscale&password=<CENSORED>&host=/run/postgresql/&port=5432...
```

**Comment by andrejpodzimek** [comment]
But then what is [this](https://github.com/jackc/pgconn/blob/5daa019e4eb52df3409ebf17c83116b7c0e827e5/config.go#L445-L447) and [this](https://github.com/jackc/pgconn/blob/5daa019e4eb52df3409ebf17c83116b7c0e827e5/config.go#L525-L527)? There seem to be some explicit mappings between `database` and `dbname`. Surprising.

**Comment by andrejpodzimek** [comment]
So this is probably [a known issue](https://github.com/jackc/pgconn/issues/69#issuecomment-813084702) and not a timescale/promscale bug. I’ve just added a comment upstream then.
