### ISSUE TITLE
timescale/promscale:latest docker image is not version 0.3.0 but 0.2.1

### ISSUE THREAD

**Issue by Pizzahd88** [timescale/promscale#576]
Just as previous release of 0.2.1 https://github.com/timescale/promscale/issues/528

The latest docker image is version 0.2.1 instead of 0.3.0. It seems like previous version is kept in the image or something.
I cannot get docker to run the latest version 0.3.0 while using :latest it keeps using 0.2.1.

The docker package seems to contain too many files - Red arrows on the image shows files from version 0.2.1 while the two other files are 0.3.0.
![image](https://user-images.githubusercontent.com/29568847/114369821-12977600-9b7f-11eb-8f51-316e76d4287c.png)

**Comment by Harkishen-Singh** [comment]
cc @cevian @VineethReddy02

**Comment by VineethReddy02** [comment]
We noticed a similar issue on `0.2.1` release too. @cevian fixed Promscale `:latest` image to point to the latest release.

**Comment by cevian** [comment]
Thanks, @Pizzahd88 for pointing out the issue. It is fixed now. In the future, this should be fixed by https://github.com/goreleaser/goreleaser/pull/2130.
