### ISSUE TITLE
Is promscale horizontally scalable?

### ISSUE THREAD

**Issue by edwmurph** [timescale/promscale#591]
README states promscale is "horizontally scalable" but it looks like promscale only enables "high availability" through leadership election? i see that the promscale sidecar improves performance by ensuring only the leader prometheus instance sends metrics to postgres. however, i interpret horizontal scalability to mean that requests can be distributed among prometheus instances so a single instance doesn't need to handle the full workload. and in the leadership election model the leader and the replicas are still each handling the full workload and will only allow vertical scaling right? i currently don't see a way to deploy promscale such that it supports horizontal scalability? am i missing something?

**Comment by Harkishen-Singh** [comment]
When we say horizontal scalability, I think we mean leveraging Timescaledb's multinode capabilities, unless I am wrong. Please correct me @cevian.

> requests can be distributed among prometheus instances

Can you say which requests are you talking about?
I
f you mean from Prometheus to Promscale as remote write request, then yes, more than one Prometheus servers can send data to single Promscale instance and promscale can handle the cardinality easily. You can do the same in HA if you deploy the two sets in similar fashion.

**Comment by cevian** [comment]
Yes when we say horizontally scalable we mean [multinode](https://blog.timescale.com/blog/timescaledb-2-0-a-multi-node-petabyte-scale-completely-free-relational-database-for-time-series/) ([docs](https://docs.timescale.com/latest/getting-started/setup-multi-node-basic)). Multinode timescaleDB can receive data from many Promscale and Prometheus nodes.

**Comment by edwmurph** [comment]
thanks for the quick response!

> i interpret horizontal scalability to mean that requests can be distributed among prometheus instances so a single instance doesn't need to handle the full workload
>> Can you say which requests are you talking about?

sorry for the confusion, i meant [custom write requests](https://github.com/timescale/promscale/blob/master/docs/writing_to_promscale.md). ultimately im just trying to understand if this prometheus solution can scale to support 500k+ metrics/min

> Yes when we say horizontally scalable we mean multinode (docs). Multinode timescaleDB can receive data from many Promscale and Prometheus nodes.

do you have any benchmarks for how many metrics this architecture can process?

it looks like metrics can be ingested in two ways: prometheus can scrape endpoints or [metrics can be sent directly to promscale instances over http](https://github.com/timescale/promscale/blob/master/docs/writing_to_promscale.md). im mostly interested in benchmarks for pushing metrics to promscale but would greatly appreciate any benchmarks you can offer

**Comment by Harkishen-Singh** [comment]
500k should be an easy number to reach per min. I have seen way more than that being ingested per sec.

A lot of users use Promscale's push functionality as well, so this should be simple.

@cevian can you please point to the benchmarks here?

**Comment by Harkishen-Singh** [comment]
@edwmurph we have benchmarks of TimescaleDB as of now. Benchmarking Promscale is on our todo but I do think you can use it since people are ingesting much more than what you asked.

**Comment by edwmurph** [comment]
great thank you for all the information!
