### ISSUE TITLE
Performance between Grafana datasource (promscale connector vs postgresql )

### ISSUE THREAD

**Issue by hserna1974** [timescale/promscale#599]
Hello

I've got a strange situation about retrieval performance from grafana.

When I execute the same query using PromQL and SQL, always the PromQL retrieve the data faster than SQL.

The query is not complex, is just access to one table and retrieve data between a period.

When I choose longer periods, the SQL reponse time takes about 30 seconds, but PromQL takes 1 second.
Ex.: 
PromQL:  cpmcputotal1min{instance="10.100.1.251"}
SQL: SELECT time,value as "CPU 1min" FROM "cpmcputotal1min" WHERE $__timeFilter("time") and val("instance_id") = '10.100.1.251'

The PromQL takes about 1 sec, but SQL takes more time about 60 secs

The attached picture shown the graph from PromScale connector has finished, but the same query using Postgres Datasource is still retrieving data.

Maybe is someting normal but I'm not sure, that I could have wrong configuration about data store layer.

I would pleased if somebody could assistme about my issue, or in case that the current situation is normnal, explain why?

Best regards

![imagen](https://user-images.githubusercontent.com/83003475/115683082-61e75e80-a356-11eb-9b63-d3e33a8fb94f.png)

**Comment by Harkishen-Singh** [comment]
Thank you for reporting this.

cc @cevian

**Comment by cevian** [comment]
Can you try [filtering with label matchers](https://github.com/timescale/promscale/blob/master/docs/sql_schema.md#filtering-series)? So for example, rewrite the above query as:
```
 SELECT time,value as "CPU 1min" FROM "cpmcputotal1min" WHERE $__timeFilter("time") and labels ? ( 'instance_id' == '10.100.1.251' )
```

I think that should significantly improve performance.

**Comment by mjf** [comment]
@cevian I see the very same performance issue with direct *SQL* queries into the *PostgreSQL* datasource in comparison to *PromQL* queries using the *Promscale* datasource in *Grafana*. For instance this *PromQL*

```awk
cpu_usage_system{__database__="$database_prom",host=~"$host",cpu="cpu-total"}
```

is much much faster than this *SQL* (not measured exactly but the difference is very obvious, at least 3x faster on 1 hour time range)
```pgsql
SELECT time_bucket('$__interval', "time") AS "time",
       AVG("value") AS "system"
  FROM "cpu_usage_system"
 WHERE $__timeFilter("time") AND
       "labels" ? ('host' == '$host') AND
       "labels" ? ('cpu' == 'cpu-total')
 GROUP BY 1
 ORDER BY 1;
```

The larger time scale I query the larger the difference is (but it **does not** seem to grow *exponentially* too).

-----

Also (an issue that is unrelated to this precise one as such but still may have something to do around it too) that on larger time scales (cca 3 hours and more) there is a slight difference in graphs (they are not **exactly** the same, at least *visually*).

**Comment by Harkishen-Singh** [comment]
I haven't checked out, but it seems like SQL results more data points (which means better granularity) than PromQL and hence grafana takes time to fetch these points. The raw SQL query from psql remains sufficiently fast (might be better than promql) since there is no time involved in transferring too many data points.

The points received from promql can be less detailed since promql engine selectively chooses samples (from underlying layer of Promscale's SQL queries) and hence can be a bit different. However, you get direct samples in SQL.

**Comment by hserna1974** [comment]
Hello again

Does that mean that PromQL are doing data sampling and does not show all collected data, only some of it?

That would mean that a PromQL query would be less reliable than SQL query and however, like you can see in next screenshot, comparing charts in Grafana it seems that same data is shown exactly:
![Comp](https://user-images.githubusercontent.com/83003475/116247443-293af100-a76b-11eb-931a-bbabfd9e27cb.jpg)

The same query filtered with label matchers like  labels ? ( 'instance' == '10.100.1.251' )  instead value filtering like  val("instance_id") = '10.100.1.251'  shows the same data:
![Graf2](https://user-images.githubusercontent.com/83003475/116247566-466fbf80-a76b-11eb-930a-aa608a849146.jpg)
 

The response time is lower than the value filtering query, but it is still significantly higher than PromQL (although it shows better). 

Correct me if i'm wrong

Best regards

**Comment by cevian** [comment]
Hmm the results from labels ? ( 'instance' == '10.100.1.251' )  and val("instance_id") = '10.100.1.251' should be exactly the same, so I am not positive what's going on. What is the query time for the labels ? ( 'instance' == '10.100.1.251' )  query?

**Comment by hserna1974** [comment]
Hello

These are the test that I did

![Test1](https://user-images.githubusercontent.com/83003475/117670275-061b3300-b1a8-11eb-9c84-53b0c5884d54.jpg)
![Test2](https://user-images.githubusercontent.com/83003475/117670287-07e4f680-b1a8-11eb-8de4-3a7690770209.jpg)
![Test3](https://user-images.githubusercontent.com/83003475/117670292-07e4f680-b1a8-11eb-8213-e07ed1c69427.jpg)

**Comment by Harkishen-Singh** [comment]
PromQL returns data based on resolution, so you get less samples. I dont think that is the case on SQL size, which is why you are getting so much of data.

**Comment by VineethReddy02** [comment]
closing this issue, as we haven’t received multiple requests from users for this feature and it's quite stale! :)

If you still have a need for this, Please open a new issue.

Thanks!
