### ISSUE TITLE
-version flag returns exit code 1

### ISSUE THREAD

**Issue by toymachiner62** [timescale/promscale#601]
I'm trying to use the `-version` flag in my CI build and I run `$ promscale -version` to verify the promscale executable is working expected but my build is failing because it's returning an exit code 1. It should return an exit code 0 so that CI builds will still pass.

![image](https://user-images.githubusercontent.com/485782/116134852-fffc6100-a695-11eb-8f57-5f95affae7ee.png)

**Comment by toymachiner62** [comment]
Closed with no response?

**Comment by Harkishen-Singh** [comment]
@toymachiner62 this was fixed by #602 and hence I closed it. You can build from master to get the fix right away.

**Comment by toymachiner62** [comment]
> @toymachiner62 this was fixed by #602 and hence I closed it. You can build from master to get the fix right away.

Thanks. I had jumped the gun before I noticed the corresponding merge.

**Comment by Harkishen-Singh** [comment]
No problem 👍
