### ISSUE TITLE
Health check endpoint for promscale?

### ISSUE THREAD

**Issue by toymachiner62** [timescale/promscale#610]
Is there a healthcheck endpoint for promscale?

Prometheus uses `/-/healthy` as it's healthcheck endpoint and I couldn't find any documention that promscale uses this same endpoint or if it has its own healthcheck endpoint.

**Comment by Harkishen-Singh** [comment]
Hey @toymachiner62, I think `/healthz` is what you want in Promscale.

**Comment by Harkishen-Singh** [comment]
Please consider closing the issue if this is resolved.
