### ISSUE TITLE
Promscale fails to connect to Azure Postgresql

### ISSUE THREAD

**Issue by mauriciocirelli** [timescale/promscale#622]
Dear,

I am trying to setup promscale using a managed postgresql server I have deployed on Microsoft Azure.
It is running Postgresql v11 and I have installed timescaledb extension manually.

I can connect to this instance using psql command line, but promscale cant:

` ./promscale --db-user <USER>@<HOSTNAME> --db-host <HOST URL> --db-name <DBNAME> --db-password <PASS> --db-ssl-mode require`

> msg="aborting startup due to error" err="failed to connect to `host=<HOST URL> user=<USER>@<HOSTNAME> database=<DBNAME>`: received unexpected message"

Am I doing anything wrong?

Thank you!

**Comment by VineethReddy02** [comment]
Hi @mauriciocirelli 
The command looks good but `--db-user` expects just the db user (I am not sure on why `@ <HOSTNAME>` to the value). Also, if the DB port isn't default port `5432` then you need to explicitly provide the port using `--db-port`. 

Below are the flags exposed in Promscale to provide db details:
 ```
-db-host string
        Host for TimescaleDB/Vanilla Postgres. [PROMSCALE_DB_HOST] [TS_PROM_DB_HOST] (default "localhost")
  -db-name string
        Database name. [PROMSCALE_DB_NAME] [TS_PROM_DB_NAME] (default "timescale")
  -db-password string
        Password for connecting to TimescaleDB/Vanilla Postgres. [PROMSCALE_DB_PASSWORD] [TS_PROM_DB_PASSWORD]
  -db-port int
        TimescaleDB/Vanilla Postgres connection password. [PROMSCALE_DB_PORT] [TS_PROM_DB_PORT] (default 5432)
  -db-ssl-mode string
        TimescaleDB/Vanilla Postgres connection ssl mode. If you do not want to use ssl, pass 'allow' as value. [PROMSCALE_DB_SSL_MODE] [TS_PROM_DB_SSL_MODE] (default "require")
  -db-statements-cache
        Whether database connection pool should use cached prepared statements. Disable if using PgBouncer [PROMSCALE_DB_STATEMENTS_CACHE] [TS_PROM_DB_STATEMENTS_CACHE] (default true)
  -db-uri postgres://postgres:password@localhost:5432/timescale?sslmode=require
        TimescaleDB/Vanilla Postgres DB URI. Example DB URI postgres://postgres:password@localhost:5432/timescale?sslmode=require [PROMSCALE_DB_URI] [TS_PROM_DB_URI]
  -db-user string
        TimescaleDB/Vanilla Postgres user. [PROMSCALE_DB_USER] [TS_PROM_DB_USER] (default "postgres")
```

An alternate way to connect to managed databases is using `--db-uri` flag. All you need to provide is `db-uri` to connect to the database.

**Comment by mauriciocirelli** [comment]
Hi,

Thank you for your reply.
At first, I had forgotten to include @hostname in the user parameter.
The error was pretty clear: 

> server error (FATAL: Invalid Username specified. Please check the Username and retry connection. The Username should be in <username@hostname> format. (SQLSTATE 28000))

Then I included @hostname at the user parameter and got that cryptic error message:

> msg="aborting startup due to error" err="failed to connect to host=<HOST URL> user=<USER>@<HOSTNAME> database=<DBNAME>: received unexpected message"

It seems to me that Azure DB is sending a Welcome Message to the driver it does not expect to.

**Comment by mauriciocirelli** [comment]
Hi,

I have made some progress.
I have installed pgbouncer and I am using it to serve promscale.
It seems to be a problem between the driver and Azure.

Moving on, I have got this error message:
`must be owner of database promscale (SQLSTATE 42501)`
So, the user must be dbOwner... not a problem.

Let's move on:
`dependency error: problem checking PostgreSQL version: Incompatible postgresql version. Supported server version >=12.x <14.x`

Unfortunately, this is not something I can change... The most recent version Azure supports is Postgresql 11.
Not sure why promscale could not run on Postgresql v11... Is it something we can work around?

Thank you!

**Comment by VineethReddy02** [comment]
@mauriciocirelli All the Promscale versions (from very first release `0.1.0`) only work with Postgres version `>=12.x`. There is no workaround for this.

**Comment by mauriciocirelli** [comment]
I have seen that release notes from Microsoft... but could not create the new database using the new version.. It does not give me this option.. I think this is something pretty new from Microsoft..

I have decided to follow the tutorial for bare metal installation. It seems to be working, but I would like to know how to create a systemd service to run promscale. It seems that it does not run by itself if I do not create the service. 

Thank you!

**Comment by VineethReddy02** [comment]
Creating a service using the same Promscale cmd should work too. You can also run Timescale cloud on azure as a mnaged offering more details here https://www.timescale.com/products

**Comment by mauriciocirelli** [comment]
I will look into that.

Thank you!

**Comment by VineethReddy02** [comment]
@janbrunrasmussen I am not aware of the flex server option. But Promscale expects Timescaledb extension as also the power storing, retrieving, and compressing time-series data is dependent on timescaleDB extension. Promscale extension is optional it just enhances the performance of Promscale. 

@mauriciocirelli we haven't considered pg 11 right from the beginning of Promscale development. Let me discuss this with the team and will update you on this.

**Comment by cevian** [comment]
Azure postgres only supports PG 11 and under and does not support the timescale compression feature or the Promscale extension. The loss of the compression feature is especially significant because it results a 10x difference in size. The lack of the Promscale extension is also significant in that query performance would degrade significantly.  

Given the other limitations to Azure I don't think investing time in PG11 would be a great use of resources at this time on our end.

**Comment by mauriciocirelli** [comment]
Hi,

Thank you for your feedback.
I understand the limitations and I will work with an on-premises PG server.

Em sex, 9 de jul de 2021 17:26, Matvey Arye ***@***.***>
escreveu:
