### ISSUE TITLE
ERROR:  could not open extension control file

### ISSUE THREAD

**Issue by mohanagandlla** [timescale/promscale#625]
```
postgres=# CREATE EXTENSION IF NOT EXISTS timescaledb;
ERROR:  could not open extension control file "/usr/local/pgsql/share/extension/timescaledb.control": No such file or directory
```
how to install this contribute to psql

**Comment by antekresic** [comment]
Seems like you haven't installed the TimescaleDB extension properly. Please take a look at the documentation on how to do it: https://docs.timescale.com/timescaledb/latest/how-to-guides/install-timescaledb/self-hosted/

I'm not quite sure what is has to do with Promscale. Hope this helps.

Thanks!

**Comment by cevian** [comment]
You should use our docker image as described here: https://github.com/timescale/promscale/blob/master/docs/docker.md

**Comment by mohanagandlla** [comment]
Yes but I have a postgres which is running on alpine os how do I install
this extension.

**Comment by cevian** [comment]
if you don't want to switch the docker image (which is what I recommend) you can follow https://github.com/timescale/timescaledb-docker/blob/master/Dockerfile as a guide to install timescaledb on alpine
