### ISSUE TITLE
Prom-migrator process terminate without notice after 2 hours.

### ISSUE THREAD

**Issue by Nathapat-Boss** [timescale/promscale#638]
Hi Promscale team,

Now I'm using prom-migrator to migrate data from TimeScaleDB 1.7 to TimeScaleDB 2.2.1 as following this diagram

<img width="734" alt="Screen Shot 2564-05-25 at 13 55 49" src="https://user-images.githubusercontent.com/84016026/119452807-faf80380-bd60-11eb-96f7-f8b269792788.png">

I have run prom-migrator to migrate data with 7 day time ranges. At first it seem running fine but after 2 hours I found the prom-migrator process is terminate without notice ( the log stop generating process ). I have no idea what cause this please help investigate

Here the parameters

prom-migrator -mint= 1619802000\
-maxt= 1620406800\
read-url=http://pg_prometheus_adapter_url:9201/read \
-write-url=http://promscale_url:9201/write \
-progress-metric-url=http://promscale_url:9201/read \
-concurrent-pulls=4 \
-concurrent-push=16 \
-max-read-size=2GB >> prom-migrator-$timestamp 2>> prom-activity.log

Activity logs:

[prom-activity.log](https://github.com/timescale/promscale/files/6537075/prom-activity.log)
[prom-migrator-2021-05-25_10:16:09.log](https://github.com/timescale/promscale/files/6537076/prom-migrator-2021-05-25_10.16.09.log)
[prom-migrator-2021-05-24_22:15:39.log](https://github.com/timescale/promscale/files/6537077/prom-migrator-2021-05-24_22.15.39.log)
[prom-migrator-2021-05-24_19:48:20.log](https://github.com/timescale/promscale/files/6537078/prom-migrator-2021-05-24_19.48.20.log)

CPU& Mem usage:

TimeScaleDB 1.7

<img width="1189" alt="Screen Shot 2564-05-25 at 13 45 36" src="https://user-images.githubusercontent.com/84016026/119451489-85d7fe80-bd5f-11eb-8761-970a8c117375.png">
 
<img width="1348" alt="Screen Shot 2564-05-25 at 12 57 58" src="https://user-images.githubusercontent.com/84016026/119452462-99379980-bd60-11eb-8c42-46b3a6d6e7d6.png">

TimScaleDB 2.2.1

<img width="1174" alt="Screen Shot 2564-05-25 at 13 30 20" src="https://user-images.githubusercontent.com/84016026/119450031-97200b80-bd5d-11eb-9f45-849d68ec2cfa.png">

<img width="1360" alt="Screen Shot 2564-05-25 at 13 01 44" src="https://user-images.githubusercontent.com/84016026/119450065-a1420a00-bd5d-11eb-8287-ecbba1eadad7.png">

Request:

Please create parameter to change timeout  I'm notice that the default is 5 minutes.
Please add retry process when the timeout is occurred.

If you can provide admin dashboard for Promscale or prom-migrator to watch the migration process that would be grate.

Thanks in advance,

Nathapat Kherlao ( Boss)

**Comment by Nathapat-Boss** [comment]
I have found the root cause for 2 hours terminate. Because I ran the prom-migrator by ssh to remote storage then executed it as front process and the session for ssh will terminate within  2 hours if no interactive. 

Fix by running nohup prom-migrator & so to run it as background process.

After it bypass 2 hours barrier , I found another error cause by timeout.


level=error ts=2021-05-25T23:34:59.683Z caller=main.go:143 msg="running writer: remote-write run: Post \"http://10.87.23.xxx:9201/write\": context deadline exceeded"

level=error ts=2021-05-26T05:43:37.984Z caller=main.go:137 msg="running reader: remote-run run: executing client-read: read-channels: error sending request: Post \"http://10.87.23.xxx:9201/read\": context deadline exceeded"

**Comment by Harkishen-Singh** [comment]
Hey @Nathapat-Boss , this is a timeout issue I guess and PR #646 will add the ability for custom timeouts and retrying behaviour.

BTW, if I recall, the migration had succeeded in our conversations on the channel. If so, you can consider closing this issue unless there is some other problem.

**Comment by Nathapat-Boss** [comment]
I have resolve this case it because I'm running the migrator process as foreground by ssh to remote server. By default the ssh session will terminate in 2 hours so the migrate process will be close along with it. Thanks you for your support and looking forward to use new version of migrator. @Harkishen-Singh
