### ISSUE TITLE
failure deleting metrics with long and winding names

### ISSUE THREAD

**Issue by hacker** [timescale/promscale#648]
When deleting metrics with the name that merits shortening for the purpose of naming tables/views the operation fails resulting in "relation not found" error or some such. I believe this is due to the fact that the original metric name is passed to the `delete_series_catalog_row` instead of the table name. I *believe* this fixes it (it did for me):

```diff
diff --git a/pkg/migrations/sql/idempotent/base.sql b/pkg/migrations/sql/idempotent/base.sql
index 308e2fe..8cabe3e 100644
--- a/pkg/migrations/sql/idempotent/base.sql
+++ b/pkg/migrations/sql/idempotent/base.sql
@@ -1963,7 +1963,7 @@ BEGIN
         GET DIAGNOSTICS rows_affected = ROW_COUNT;
         num_rows_deleted = num_rows_deleted + rows_affected;
     END IF;
-    PERFORM SCHEMA_CATALOG.delete_series_catalog_row(name, series_ids);
+    PERFORM SCHEMA_CATALOG.delete_series_catalog_row(metric_table, series_ids);
     RETURN num_rows_deleted;
 END;
 $$
```

Sorry, no PR, I'm not acquainted with the code enough, I believe some changes elsewhere are also needed to trigger migration and I won't have time in the nearest future to figure it out (or even look into figuring it out or generally create a PR).

**Comment by Harkishen-Singh** [comment]
Hey @hacker , thank you for pointing this out. Yes, it should be metric_table. I don't think there are any more changes required for this, so you can open a PR after doing the `go generate ./...`.

**Comment by cevian** [comment]
@Harkishen-Singh please submit a PR for this

**Comment by hacker** [comment]
So here it comes. the generate part is what I didn't know.

Note, that I haven't tested it after rebasing on current master. Also, interestingly, when running generate atop of `0.4.1` `git diff` produced readable diff, whereas on the master it says "binary files differ". No idea why, possibly because the lines grew longer or something, just saying… Anyway, I hope your automated tests cover possible breakages, otherwise it's probably best to test before merging.
