### ISSUE TITLE
Is it possible that two PromScale replicas behind one loadbalancer pick different leaders from two Prometheus instances?

### ISSUE THREAD

**Issue by jxl4650152** [timescale/promscale#653]
Assuming Prometheus instances already configured properly based on docs: https://github.com/timescale/promscale/blob/master/docs/high-availability/prometheus-HA.md

**Comment by Harkishen-Singh** [comment]
A new leader will be chosen only if Promscale has not heard from the previous leader for some `time`. This `time` is 30 secs, please correct me @VineethReddy02  if I am wrong.

**Comment by VineethReddy02** [comment]
Yes, that's right. At any point, Promscale elects only one leader from Prometheus instances for writes.

**Comment by jxl4650152** [comment]
@Harkishen-Singh @VineethReddy02 Thanks for your quick reply. But I still have some confusion. A picture speaks a thousand words, take below deployment as an example:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/8534661/120740382-ad7c5300-c525-11eb-9afa-4ce60bb85d85.png">

If Promscale1 and Promscale2 don't communicate with each other, then will they elect different leaders and send duplicate samples to TSDB?

**Comment by Harkishen-Singh** [comment]
Promscale1 and Promscale2 talk to each other through the Timescaledb. They update their state of last received leader in Timescaledb which is read by other Promscale instances.

I think our explaination in the doc needs some more technical details so that everyone cab have a very clear picture. Cc @VineethReddy02 

Feel free to ask now questions @jxl4650152.

**Comment by jxl4650152** [comment]
@Harkishen-Singh That sounds makes sense. Thanks.
One more question about running Promscale in HA mode: why is the external labels method of leader election recommended instead of the PostgreSQL lock method? what is the advantage of external labels? The doc seems doesn't mention it.

**Comment by Harkishen-Singh** [comment]
Hey @jxl4650152 , using the `external_labels` method for HA allows you to independently scale Promscale based on your requirement. The `pg_lock` based HA has a strong one-to-one bonding _between each Prometheus and Promscale_ instance and restricts the free scaling of Promscale.

**Comment by Harkishen-Singh** [comment]
cc @VineethReddy02 for doc updates.

**Comment by cevian** [comment]
@jxl4650152 we have a blog post about this topic https://blog.timescale.com/blog/promscale-0-4-drawing-inspiration-from-cortex-to-rewrite-support-for-prometheus-high-availability/

**Comment by VineethReddy02** [comment]
The docs for the new HA already explain the inner working model. However, in upcoming releases, we deprecate the older HA.
So I do not see a reason for explaining the differences as the older one isn't an option anymore to use. 
We can add a reference to the blog post on HA shared by mat to the docs for a detailed overview of how HA in Promscale evolved.

**Comment by jxl4650152** [comment]
@cevian @VineethReddy02 Thanks, I see the blog.
