### ISSUE TITLE
Promscale maintenance tasks are taking so long to compress the data

### ISSUE THREAD

**Issue by ali-ghasempor** [timescale/promscale#663]
Hello,

I would like to report the issue after upgrading to promscale v0.4.0 (Docker image from [https://hub.docker.com/r/timescale/promscale](url))
Before upgrading to v0.4.0, we have 2 `execute_maintenance_job` jobs constantly running. It usually compress chunks in specific timeframe like (60-90 minutes). Therefore the rate of uncompressed chunks were almost near to some number.
### The Problem 
However after upgrade, the maintenance job can not keep up with compression and number of uncompressed chunks are constantly growing. Also the job is now taking more than **48 hours**!
We upgrade to v0.4.1 and still the issue exists. 
Here is the query results from job table:
```
prometheus=# SELECT * FROM timescaledb_information.jobs;
-[ RECORD 1 ]-----+------------------------------
job_id            | 2678
application_name  | User-Defined Action [2678]
schedule_interval | 00:30:00
max_runtime       | 00:00:00
max_retries       | -1
retry_period      | 00:05:00
proc_schema       | _prom_catalog
proc_name         | execute_maintenance_job
owner             | postgres
scheduled         | t
config            | 
next_start        | -infinity
hypertable_schema | 
hypertable_name   | 
-[ RECORD 2 ]-----+------------------------------
job_id            | 2679
application_name  | User-Defined Action [2679]
schedule_interval | 00:30:00
max_runtime       | 00:00:00
max_retries       | -1
retry_period      | 00:05:00
proc_schema       | _prom_catalog
proc_name         | execute_maintenance_job
owner             | postgres
scheduled         | t
config            | 
next_start        | -infinity
hypertable_schema | 
hypertable_name   | 
```
```
prometheus=# SELECT * FROM timescaledb_information.job_stats;
-[ RECORD 1 ]----------+------------------------------
hypertable_schema      | 
hypertable_name        | 
job_id                 | 2679
last_run_started_at    | 2021-06-11 06:02:15.496375+00
last_successful_finish | 2021-06-11 05:32:15.493223+00
last_run_status        | 
job_status             | Running
last_run_duration      | 
next_start             | -infinity
total_runs             | 535
total_successes        | 522
total_failures         | 6
-[ RECORD 2 ]----------+------------------------------
hypertable_schema      | 
hypertable_name        | 
job_id                 | 2678
last_run_started_at    | 2021-06-11 06:22:58.830334+00
last_successful_finish | 2021-06-11 05:52:58.828372+00
last_run_status        | 
job_status             | Running
last_run_duration      | 
next_start             | -infinity
total_runs             | 534
total_successes        | 523
total_failures         | 4
-[ RECORD 3 ]----------+------------------------------
hypertable_schema      | 
hypertable_name        | 
job_id                 | 1
last_run_started_at    | 2021-06-13 21:56:21.182706+00
last_successful_finish | 2021-05-31 00:08:17.176526+00
last_run_status        | Failed
job_status             | Scheduled
last_run_duration      | 00:01:40.042706
next_start             | 2021-06-14 18:16:46.225412+00
total_runs             | 389
total_successes        | 156
total_failures         | 233
```
We are running on TimescaleDB v2.3.0-pg12
```
Name        | timescaledb
Version     | 2.3.0
Schema      | public
Description | Enables scalable inserts and complex queries for time-series data
```
Following image is showing the number of uncompressed chunks. As you can clearly see the number significantly jumped after updating to v0.4.0
![Screenshot 2021-06-14 at 10 16 54](https://user-images.githubusercontent.com/8905367/121853519-af020400-ccf9-11eb-815d-8491e1736893.png)
Also following image shows how long a job takes to finish. Again, as you can see a job taking longer and longer to finished.
![Screenshot 2021-06-14 at 10 13 31](https://user-images.githubusercontent.com/8905367/121854065-5848fa00-ccfa-11eb-89ec-1aa841b6e116.png)

 * The rate of data that are feed to Promscale from Prometheus is same as it was before.

**Comment by ali-ghasempor** [comment]
Just adding an update.
I added one more job with similar parameter (removed one of current jobs, so again 2 in total) and it took **5 days** to finish!

**Comment by cevian** [comment]
I think this may be solved by #662. Can you try reducing to 1 job and see if the situation improves?

**Comment by cevian** [comment]
Also what was the previous version you were running?

**Comment by ali-ghasempor** [comment]
@cevian Thanks for your reply.
I removed one job and will update here how will be the situation. We are using Promscale from very early version. So basically we updated from version **3.0** to **4.0** then the mentioned issue, started.

**Comment by ali-ghasempor** [comment]
Hi @cevian
More updates for you. The running only one maintenance task didn't help at all. In fact it followed the same increasing pattern (even faster). I added two more jobs (totally 3 jobs) and it helped to reduce number of chunks. However the main issue that the jobs are taking so longs still exists. The new added jobs took 5 days to finish!
Following graph shows the uncompressed chunks started decreasing after I added jobs for first time. 
![Screenshot 2021-06-28 at 10 05 17](https://user-images.githubusercontent.com/8905367/123596331-bdbce080-d7fa-11eb-9e24-0493a774b585.png)

**Comment by cevian** [comment]
@ali-ghasempor ,

Can you tell me how many metrics you have? Is this traditional Prometheus data?

**Comment by ali-ghasempor** [comment]
@cevian 
We have 1770 metrics in our TSDB. And yes they are all usual Prometheus data. We are using standard setup for Prometheus.
```
select count(*) from _prom_catalog.metric;
 count 
-------
  1770
(1 row)
```

**Comment by cevian** [comment]
can you run `SELECT _prom_catalog.execute_compression_policy()` in a psql session and see how long it takes? (execute_maintenance runs both execute_data_retention_policy() and execute_compression_policy() and I am guessing execute_data_retention_policy() is the thing causing the problem but want to double check)

**Comment by cevian** [comment]
Hoping that #678 improves things
