### ISSUE TITLE
Migrate false gives errors

### ISSUE THREAD

**Issue by jesperpedersen** [timescale/promscale#669]
Version: 0.4.1

I'm running a completely fresh PostgreSQL 13.3 w/ TimescaleDB 2.3.0 instance and use the following command

```sh
/usr/local/bin/promscale -db-name prometheus -db-password mypass -db-user myuser -db-ssl-mode=allow -migrate false -log-level=warn
```

where `myuser` owns the `prometheus` database (has `GRANT ALL ON SCHEMA prometheus TO prometheus;`) - e.g. is not allowed to create roles, ...

Log says:
```
level=error ts=2021-06-22T18:08:06.592Z caller=client.go:124 msg="Unable to run migrations; failed to acquire the lock. If the database is on an incorrect version, ensure there are no other connectors running and try again." err="dependency error: failed to check schema version: Error getting DB version: ERROR: relation \"prom_schema_migrations\" does not exist (SQLSTATE 42P01)"
level=error ts=2021-06-22T18:08:06.594Z caller=runner.go:40 msg="aborting startup due to error" err="dependency error: failed to check schema version: Error getting DB version: ERROR: relation \"prom_schema_migrations\" does not exist (SQLSTATE 42P01)"
```
However, as $SUBJECT states `-migrate false`.

It will of course fail with `-migrate true` as well, since there are no permissions for that.

**Comment by cevian** [comment]
@jesperpedersen I am confused as to what you are trying to accomplish. if you are running -migrate=false on the new database then the connector cannot install the schema needed for promscale (and one doesn't already exist). You may want to use -migrate=only for a privileged user beforehand. See https://github.com/timescale/promscale/blob/master/docs/sql_permissions.md#deployments-with-separate-owner-and-modifier-users

**Comment by jesperpedersen** [comment]
I'm trying to deploy promscale as an unprivileged user, and don't see an option for that.

I understand the reasons described in sql_permissions.md - but they assume that a DBA with superuser rights deploy the initial solution. I think that is a **big** ask.

Maybe better logging for the `-migrate false` and `-migrate only` cases would help people understand the problem better.

Ideally, the schema should be able to deploy under an unprivileged user with the caveats that will bring.
