### ISSUE TITLE
Support read from timescaledb replications?

### ISSUE THREAD

**Issue by monsterxx03** [timescale/promscale#671]
https://docs.timescale.com/timescaledb/latest/overview/core-concepts/scaling/#primary-and-backup-replication

If promscale can be configured to use timescaledb's replications for read query, read throughput can be highly scaled. 

Also we have concerns about timescaledb's performance impact on pg master(still during research), routing promscale's read to replications helps a lot.

**Comment by cevian** [comment]
You can now use a separate Promscale instance running with `-read-only` flag connecting to the replica. Are you asking to use one Promscale instance with different read and write connection strings?

**Comment by monsterxx03** [comment]
Yes, I'll have a try, thanks
