### ISSUE TITLE
Build scripts make assumptions about packaging requirements

### ISSUE THREAD

**Issue by grawlinson** [timescale/promscale#683]
I am the maintainer for the [AUR](https://aur.archlinux.org/packages/promscale/) package of promscale.

The build scripts used are Debian-specific, and leave no wiggle room for other distributions.

1. The binary [path](https://github.com/timescale/promscale/blob/7abf6bd2712595e49e09076580bb4e433a184ebe/build/systemd/promscale.service#L12) in the systemd service is assumed to be `/usr/local/bin/promscale` which is incorrect.
2. The systemd service file is [installed](https://github.com/timescale/promscale/blob/7abf6bd2712595e49e09076580bb4e433a184ebe/build/.goreleaser.yml#L57) to `/etc/systemd/system/promscale.service` is also incorrect. Distributions must install it to `/usr/lib/systemd/system`, leaving users/sysadmins the ability to use their own replacements in `/etc/systemd/system`.
3. The [parameter](https://github.com/timescale/promscale/blob/7abf6bd2712595e49e09076580bb4e433a184ebe/build/systemd/promscale.service#L11) `EnvironmentFile` in the systemd service file is considered a bad idea by it's creator (refs: [1](https://lists.freedesktop.org/archives/systemd-devel/2015-December/035236.html), [2](https://github.com/systemd/systemd/issues/9788#issuecomment-420385947)), and alternative methods are preferred.

**Comment by cevian** [comment]
@grawlinson Thank you. cc @antekresic who is in charge of the build scripts. Am I correct in thinking https://aur.archlinux.org/cgit/aur.git/tree/systemd.service?h=promscale is the systemd definition you wrote and prefer?

**Comment by grawlinson** [comment]
I wrote that, and I can confirm it works without issue. Arch Linux packaging requirements is to keep packages as close to upstream as possible.

I’m not 100% familiar with Debian packaging requirements, but [here](https://wiki.debian.org/Packaging) is a good reference.

**Comment by antekresic** [comment]
Hi @grawlinson, thanks for reporting this. I have taken your points into consideration and will try to improve upon them. However, could you clarify this:

> 1. The binary path in the systemd service is assumed to be /usr/local/bin/promscale which is incorrect.

As far as I can tell, that's the correct path where promscale binary is stored. Could you expand on this?

Thanks.

**Comment by cevian** [comment]
@antekresic https://unix.stackexchange.com/questions/8656/usr-bin-vs-usr-local-bin-on-linux implies that package-managed binaries should go into /usr/bin not /usr/local/bin?

**Comment by antekresic** [comment]
@cevian Ah right... /usr/local/bin is the default path for goreleaser, I'll change it to /usr/bin and add this to my PR.

**Comment by cevian** [comment]
@antekresic  do we like the drop-in approach https://kinvolk.io/docs/flatcar-container-linux/latest/setup/systemd/environment-variables/ instead of EnvironmentFile. Are there other options you'd recommend @grawlinson ?

**Comment by antekresic** [comment]
Personally, I don't think current setup limits our users since you can edit systemd units and add your custom configuration that way (instead of editing the installed configuration file). 

Configuration file setup that we have right now is an easy and convenient way to configure Promscale by simply editing a file and changing some values. I'm not entirely convinced we should be changing that setup at all right now.

**Comment by antekresic** [comment]
I've merged a PR addressing the first two points of this issue. Feel free to reopen and discuss the third point if necessary so we can address that too.
