### ISSUE TITLE
Dropping a metric using Promscale's SQL API leads to corrupted prom_info.metric_stats view

### ISSUE THREAD

**Issue by mjf** [timescale/promscale#686]
Some time ago I dropped a metric using *Promscale*'s SQL API
```sql
SELECT prom_api.drop_metric('some_metric');
```
Today I ran
```sql
SELECT * FROM prom_info.metric_stats;
```
and got an error
```sql
ERROR:  relation "prom_series.some_metric" does not exist
```

**Comment by mjf** [comment]
It may be related to #617.

**Comment by Harkishen-Singh** [comment]
Thank you for the issue. It seems that the `prom_api.drop_metric(text)` is not deleting entry from metric table as per expectations, so clearly a bug.

**Comment by cevian** [comment]
@Harkishen-Singh what's the update on this?

**Comment by Harkishen-Singh** [comment]
We tried and we not reproduced. The conclusion was that there was some other thing which caused this issue. We can hence close this.
