### ISSUE TITLE
Provide option to set log level for the `prom-migrator` tool

### ISSUE THREAD

**Issue by mjf** [timescale/promscale#693]
The `prom-migrator` tool is lacking a `--log-level=<level>` which may be very handy to reduce useless messages from the output (i.e. `msg="Exceeded 'max-read-duration', setting back to 'max-read-duration' value"` and similar).

**Comment by VineethReddy02** [comment]
closing this issue, as we haven’t received multiple requests from users for this feature and it's quite stale! :)

If you still have a need for this, Please open a new issue.

Thanks!
