### ISSUE TITLE
Does create/update extension need superuser creds

### ISSUE THREAD

**Issue by VineethReddy02** [timescale/promscale#708]
A user reported below warning log
```
promscale[56356]: level=warn ts=2021-07-28T17:18:11.671Z caller=extension.go:155 msg="Unable to install/update the Promscale extension; failed to acquire the lock. Ensure there are no other connectors running and try again."
```

Also, mentioned that the warning disappeared when the user configured superuser creds to Promscale.

**Comment by JamesGuthrie** [comment]
A simple answer to this quersion: yes, the promscale extension requires superuser credentials.

One reason is that we attach support functions to some promscale functions, which requires superuser. From the postgres docs:

```
SUPPORT support_function
    The name (optionally schema-qualified) of a planner support function to use for this function. See Section 38.11 for details. You must be superuser to use this option.
```

**Comment by cevian** [comment]
There is a way around this using pgextwlist https://github.com/timescale/promscale/blob/master/docs/sql_permissions.md#using-a-non-superuser-owner-with-pgextwlist
