### ISSUE TITLE
Add HTTP HEAD support to health check endpoint

### ISSUE THREAD

**Issue by caseyandgina** [timescale/promscale#710]
Our infrastructure guys asked if it might be possible for HTTP HEAD support to be added to the health check endpoint, as this would result in less work for the load balancers to have to do as they only care about the status code?  Currently using GET is required.

```
$ curl -I http://d-gp2-dbapromscale-1.imovetv.com:9201/healthz
HTTP/1.1 405 Method Not Allowed
Allow: GET, OPTIONS
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Wed, 28 Jul 2021 19:24:13 GMT
Content-Length: 19

$ curl -s -o /dev/null -w "%{http_code}" http://d-gp2-dbapromscale-1.imovetv.com:9201/healthz
200
```

**Comment by Harkishen-Singh** [comment]
@cevian lets have this as part of our next release.

I think this will require a change in `"github.com/prometheus/common/route"` to allow `.Head()` funcs, which should be a simple one liner addition.

**Comment by paulfantom** [comment]
Change upstream is complete. We can either use `github.com/prometheus/common@5a265357` or wait for next release (possibly 0.32.0) of that package and bump our `go.mod`

**Comment by VineethReddy02** [comment]
@niksajakovljevic can we close this issue wrt #1378 ?
