### ISSUE TITLE
Add a testing option to end-to-end tests to clear the search path for all tests so that we have search-path-independence tested throughout

### ISSUE THREAD

**Issue by jgpruitt** [timescale/promscale#713]
https://github.com/timescale/promscale/pull/707#pullrequestreview-716511911

**Comment by ramonguiu** [comment]
@jgpruitt the PR linked above was merged a while ago. Is there more work left?

**Comment by jgpruitt** [comment]
@ramonguiu yes. The linked PR fixed a few known bugs. This issue is a reminder to enhance our tests to catch any future bugs of the same kind that might get introduced
