### ISSUE TITLE
-db-password option is inappropriately interpolated

### ISSUE THREAD

**Issue by babbottscott** [timescale/promscale#727]
It appears the value of -db-password (whether passed on command line or by environment variable) is being interpolated when injected into the connection string.

So far we've had trouble with `%%` and other sprintf-like strings, as well as `#`. I haven't looked into the code, so can't give a full scope, but here are some illustrative command line attempts:
```
$ PROMSCALE_DB_HOST=127.0.0.1 PROMSCALE_DB_PORT=5432 PROMSCALE_DB_NAME=prometheus PROMSCALE_DB_USER=postgres PROMSCALE_DB_SSL_MODE=prefer PROMSCALE_WEB_LISTEN_ADDRESS=:9201 promscale -db-password '%s123'
... err="cannot parse `postgresql://postgres:xxxxxx@127.0.0.1:xxxxxx@0.5.1&sslmode=prefer&connect_timeout=60`: failed to parse as URL (parse \"postgresql://postgres:%s123@127.0.0.1:5432/prometheus?application_name=promscale@0.5.1&sslmode=prefer&connect_timeout=60\": invalid URL escape \"%s1\")"

$ ... promscale -db-password '%%s123'
... err="cannot parse `postgresql://postgres:xxxxxx@127.0.0.1:xxxxxx@0.5.1&sslmode=prefer&connect_timeout=60`: failed to parse as URL (parse \"postgresql://postgres:%%s123@127.0.0.1:5432/prometheus?application_name=promscale@0.5.1&sslmode=prefer&connect_timeout=60\": invalid URL escape \"%%s\")"

$ ... promscale -db-password '\%s123'
... err="cannot parse `postgresql://postgres:xxxxxx@127.0.0.1:xxxxxx@0.5.1&sslmode=prefer&connect_timeout=60`: failed to parse as URL (parse \"postgresql://postgres:\\\\%s123@127.0.0.1:5432/prometheus?application_name=promscale@0.5.1&sslmode=prefer&connect_timeout=60\": net/url: invalid userinfo)"

$ ... promscale -db-password '123#456'
... err="failed to connect to `host=postgres user=promscale database=`: hostname resolving error (lookup postgres on <nameserver_ip>:53: no such host)"

$ ... promscale -db-password '123\#456'
... err="cannot parse `postgresql://postgres:xxxxxx@127.0.0.1:xxxxxx@0.5.1&sslmode=prefer&connect_timeout=60`: failed to parse as URL (parse \"postgresql://postgres:123\\\\\": invalid port \":123\\\\\" after host)"
```

Expected behavior:
In assembling the db url, the -db-password value should be url-encoded directly from the value received with no other interpolation.

**Comment by Harkishen-Singh** [comment]
Thank you for reporting the issue. Masking passwords always creates some corner cases when using special symbols. We will take a look on this more.

cc @antekresic

**Comment by jgpruitt** [comment]
https://www.postgresql.org/docs/current/libpq-connect.html#id-1.7.3.8.3.6

> The connection URI needs to be encoded with percent-encoding if it includes symbols with special meaning in any of its parts.

https://datatracker.ietf.org/doc/html/rfc3986#section-2.1

**Comment by jgpruitt** [comment]
This issue is not limited to just the password. Database names and user names can also contain characters that need to be url encoded.

**Comment by jgpruitt** [comment]
@babbottscott this issue is fixed and should go out with the next release
