### ISSUE TITLE
Materialized aggregate views are purged when execute_maintenance is executed

### ISSUE THREAD

**Issue by franck102** [timescale/promscale#732]
We are creating hourly aggregates as materialized views over prom_data hypertables using the SQL code below.
The expectation is that we will be able to expire the raw samples in prom_data and keep only the hourly aggregates.
When execute_maintenance runs however, it deletes data from the views in our meter_data schema... so some kind of cascading is happening.

Am I misunderstanding the CREATE MATERIALIZED VIEW meter_data.xxx statement? I expected it to create a copy of the source data (after some materialization delay) that remains unaffected by changes to the source table?

I don't understand why my "create materialized view" SQL source becomes a "CREATE OR REPLACE VIEW" when looking at the DB entities?

Source pgsql code:

        execute format('CREATE MATERIALIZED VIEW meter_data.%I ' ||
                       'WITH (timescaledb.continuous, timescaledb.materialized_only=false) AS ' ||
                        'select public.time_bucket(%L, time) as time, series_id, %s(%s) as value ' ||
                        'from prom_data.%I where %s != float8 ''NaN'' group by public.time_bucket(%L, time), series_id With NO DATA',
                        dst_name, ct_record.interval, aggr_function, col_name, prom_table_name, col_name, ct_record.interval);
        execute format('SELECT add_continuous_aggregate_policy(' ||
                       'continuous_aggregate => ''meter_data.%I'',' ||
                       'start_offset         => %L,' ||
                       'end_offset           => %L,' ||
                       'schedule_interval    => ''1 hour'')',
                       dst_name,'{{CTREFRESHSTARTOFFSET}}', ct_record.interval);

Resulting view in Postgres:

```
CREATE OR REPLACE VIEW meter_data."service:dms_fdo_query:sum:hourly"
AS SELECT _materialized_hypertable_202."time",
    _materialized_hypertable_202.series_id,
    _timescaledb_internal.finalize_agg('sum(double precision)'::text, NULL::name, NULL::name, '{{pg_catalog,float8}}'::name[], _materialized_hypertable_202.agg_3_3, NULL::double precision) AS value
   FROM _timescaledb_internal._materialized_hypertable_202
  WHERE _materialized_hypertable_202."time" < COALESCE(_timescaledb_internal.to_timestamp(_timescaledb_internal.cagg_watermark(202)), '-infinity'::timestamp with time zone)
  GROUP BY _materialized_hypertable_202."time", _materialized_hypertable_202.series_id
UNION ALL
 SELECT time_bucket('01:00:00'::interval, "service:dms_fdo_query:joined"."time") AS "time",
    "service:dms_fdo_query:joined".series_id,
    sum("service:dms_fdo_query:joined".incr) AS value
   FROM prom_data."service:dms_fdo_query:joined"
  WHERE "service:dms_fdo_query:joined".incr <> 'NaN'::double precision AND "service:dms_fdo_query:joined"."time" >= COALESCE(_timescaledb_internal.to_timestamp(_timescaledb_internal.cagg_watermark(202)), '-infinity'::timestamp with time zone)
  GROUP BY (time_bucket('01:00:00'::interval, "service:dms_fdo_query:joined"."time")), "service:dms_fdo_query:joined".series_id;

```

**Comment by cevian** [comment]
which version of PG and timescale is this running?

**Comment by franck102** [comment]
I have a feeling we simply messed up the start and end offsets compared to our expiration settings, I will experiment more tomorrow and close this if this is the case.

**Comment by franck102** [comment]
It will take a few days to fully test, but I think we simply misconfigured our caggs. The start_offset was overlapping with expiration, causing maintenance to delete records from the aggregate view.
Closing this, sorry for the false alert.
