### ISSUE TITLE
Number of partitions on tag table

### ISSUE THREAD

**Issue by jgpruitt** [timescale/promscale#748]
Experiment with different numbers of partitions on tag table to see performance impact

**Comment by sumerman** [comment]
## On Consistent-Hashing-inspired partitioning

My interpretation of "consistent-hashing", when applied to this task, is the following range partitioning scheme:

```sql
CREATE TABLE public.foobar
(
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    key ps_trace.tag_k NOT NULL,
    value ps_trace.tag_v NOT NULL
)
PARTITION BY RANGE (hashtextextended(key::text, 0));

CREATE TABLE public.foobar_1 PARTITION OF public.foobar FOR VALUES FROM (-9223372036854775808) TO (0);
CREATE TABLE public.foobar_2 PARTITION OF public.foobar FOR VALUES FROM (0) TO (9223372036854775807);
```

All keys are mapped into a `BIGINT` hash-space and it can be divided into an arbitrary number of ranges. It's pretty straightforward to progressively subdivide the hash space into power-of-two equal parts.

To avoid shuffling all data during repartitioning the following method could be used:

```sql
BEGIN;

-- detach a partition
ALTER TABLE public.foobar DETACH PARTITION public.foobar_1;
-- create a sub-partition
CREATE TABLE public.foobar_1_1 (LIKE public.foobar INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
-- move half of the data from the detached partition into the new sub-partition
WITH moved AS (DELETE FROM public.foobar_1 WHERE hashtextextended(key::text, 0) >= div(-9223372036854775808, 2) RETURNING *)
INSERT INTO public.foobar_1_1 (id, key, value) SELECT * FROM moved;
-- re-attach partittions
ALTER TABLE public.foobar ATTACH PARTITION public.foobar_1 FOR VALUES FROM (-9223372036854775808) TO (div(-9223372036854775808, 2));
ALTER TABLE public.foobar ATTACH PARTITION public.foobar_1_1 FOR VALUES FROM (div(-9223372036854775808, 2)) TO (0);
END;
```

Although, there's a problem with the `tag` table:

```
ERROR:  unsupported UNIQUE constraint with partition key definition
DETAIL:  UNIQUE constraints cannot be used when partition keys include expressions.
```

Since `key` column is used in the unique constraint we can't use `hashtextextended(key::text, 0)` as a partitioning key due to PostgreSQL limitation. We would have to materialize it. 

## On performance impact of partitioning

I performed a limited comparison between several partitioning schemes. All tests were performed on my laptop equipped with 2.4 GHz Quad-Core Intel Core i5 from 2019 with Turbo-boost disabled for consistency and PostgreSQL 14.

I've used the following queries to generate data:

```SQL
-- pre-populating tag_key table, not measured
EXPLAIN ANALYZE SELECT ps_trace.put_tag_key('test.tag.n_' || n::text, ps_trace.resource_tag_type())
FROM generate_series(0, 1000) AS gs (n);

EXPLAIN ANALYZE SELECT ps_trace.put_tag('test.tag.n_' || (n % 1000)::text, n::text::jsonb, ps_trace.resource_tag_type())
FROM generate_series(1, 20000) AS gs (n);
```

And this query to simulate a read workload:

```SQL
EXPLAIN ANALYZE SELECT tag_map_denormalize(tags) 
FROM generate_series(1, 20000) AS gs (n),
LATERAL (
	SELECT jsonb_build_object(a.key_id, a.id) AS tags
    FROM _ps_trace.tag a
    WHERE a.key = 'test.tag_99'
    AND _prom_ext.jsonb_digest(a.value) = _prom_ext.jsonb_digest(n::text::jsonb)
    AND a.value = n::text::jsonb
    LIMIT 1
) AS t 
WHERE tags IS NOT NULL;
```

For 1000 tags and 20000 values (20 values per tag) I've produced the following measurements:

| Query | No Partitioning | Hash Partitioning (mod 64) | Range, only the default partition | Range, default + 1 partition |
|-------|----------------|----------------------------|---------------------------------|-----------------------------|
| Write  |        7.9s            |                  12.5s                     |                     8.3s                            |                   13s                         |
| Read  |        1.4s             |                  1.3s                       |                     1.4s                            |                   1.3s                         |


I've also tried pushing the amount of data 10x by increasing either the number of tags or the number of values per tag, measurements seem to scale linearly. 

Even though the described testing methodology isn't particularly thorough I think it's safe to conclude: under a single-threaded workload partitioning overhead during writes far outweighs reads speed up. The unique constraint on key and value digest columns serves as an index and further partitioning brings only marginal gains. I've tried pushing the number of partitions up to 1024 which increases the read speed-up but slows down inserts even more.

## Conclusion

I propose to abandon partitioning for the GA release: it doesn't appear to be a better default, and it can be re-introduced later if necessary.

**Comment by cevian** [comment]
Just to be clear: We originally partitioned not for any read speed up but to make sure that the tags table doesn't slow down horribly on writes once the btree index grows larger than memory. That's a case that isn't really tested here. 

However thinking about this again the index is btree(key, sha(value)...) so it's not clear that hash partitioning by key ever gave us better  locality than the lead column of the btree being key anyway. And specifically, if we assume a heavy zipfian distribution on key the hot "key" area of the btree should stay memory-resident anyway. I actually no longer see how key-based partitioning helps here. 

In the future, we may actually use list partitioning here and move hot keys into dedicated partitions. But that a future problem. For now, I agree we should probably move to a single partition setup and decide on what we have to do in the future. 

I want to get @jgpruitt's input here before making any final changes.

**Comment by jgpruitt** [comment]
First of all, I would expect no partitioning to beat any partitioning scheme for 20k rows. I think the payoff would manifest at a much higher row count. Other systems suffer from poor performance when there is high cardinality in the tags, and we want to be able to handle high cardinality ideally.

**Comment by jgpruitt** [comment]
@cevian I think you're correct about the locality of the btree index, however, for each partition, the associated btree would be smaller vs no partitions. right?

**Comment by jgpruitt** [comment]
we also wanted to have some isolation between tags. If one tag has a bajillion values and they are large, at least that would only impact one partition.

**Comment by jgpruitt** [comment]
I have had the opentelemetry-demo running for ten minutes and it has 5775 tags

**Comment by sumerman** [comment]
> I have had the opentelemetry-demo running for ten minutes and it has 5775 tags

5775 tags or keys?

**Comment by jgpruitt** [comment]
<img width="439" alt="image" src="https://user-images.githubusercontent.com/4974668/165166298-20c7ac7c-c5a5-42ba-81f1-e7290201ca91.png">

**Comment by jgpruitt** [comment]
i mean, granted this is a totally made up demo, but I don't think that number is out of the realm of realistic

**Comment by jgpruitt** [comment]
<img width="584" alt="image" src="https://user-images.githubusercontent.com/4974668/165166486-07a4b78b-8b89-430a-96fa-ec5d324da06c.png">

**Comment by sumerman** [comment]
> <img alt="image" width="439" src="https://user-images.githubusercontent.com/4974668/165166298-20c7ac7c-c5a5-42ba-81f1-e7290201ca91.png">

Then we should partition by the same key as the our unique index.

**Comment by jgpruitt** [comment]
meaning key AND value digest?

**Comment by sumerman** [comment]
> meaning key AND value digest?

Yes. Otherwise we’ll have to make users chase and isolate hot keys manually via range or list partitions.

**Comment by sumerman** [comment]
Or I can implement a background job to move hot tags into their own partition 🤔

**Comment by jgpruitt** [comment]
in many cases, we know the key, but we need to scan the values. for example, if we want to match values according to a regex. If value is a part of the partition key, then we have to scan ALL partitions

**Comment by jgpruitt** [comment]
i agree though, it would be nice to have a way to identify and deal with hot and/or high-cardinality keys separately

**Comment by jgpruitt** [comment]
<img width="584" alt="image" src="https://user-images.githubusercontent.com/4974668/165167856-91941622-ed10-4fe8-bc2d-d7b7fd18df99.png">

I think many tag keys will have a fixed, small number of values, and others will have many unique values and continue to grow (like net.peer.port in the demo)

**Comment by sumerman** [comment]
>in many cases, we know the key, but we need to scan the values. for example, if we want to match values according to a regex. If value is a part of the partition key, then we have to scan ALL partitions

>if we just partition on key, at least we can jump to the one partition where all the values for that key exist, and scan it. ignore the others

Yeah, I've re-read Mat's post and scratch what I've suggested as it'll be worse than a single b-tree with hot prefixes.

**Comment by sumerman** [comment]
So then I'd suggest releasing GA with the list partitioning scheme that includes only the default partition. That would allow users to manage hot tag keys and would allow us to add automation around that in the future.

**Comment by sumerman** [comment]
> Just to be clear: We originally partitioned not for any read speed up but to make sure that the tags table doesn't slow down horribly on writes once the btree index grows larger than memory. That's a case that isn't really tested here.
> 

Thanks for clarifying that. I don't think my back-of-the-napkin method would have shown this no matter the amount of data as it is sequential. I could limit RAM allocated to PG container and make the payload random and let John's demo run alongside.

**Comment by cevian** [comment]
> So then I'd suggest releasing GA with the list partitioning scheme that includes only the default partition. That would allow users to manage hot tag keys and would allow us to add automation around that in the future.

This sounds reasonable. Is there an easy way to transform an unpartitioned table to one default partition?

> Thanks for clarifying that. I don't think my back-of-the-napkin method would have shown this no matter the amount of data as it is sequential. I could limit RAM allocated to PG container and make the payload random and let John's demo run alongside.

Yeah that could work. I also think there is a way to make a small Golang program create a zipfian distribution

**Comment by sumerman** [comment]
> > So then I'd suggest releasing GA with the list partitioning scheme that includes only the default partition. That would allow users to manage hot tag keys and would allow us to add automation around that in the future.
> 
> This sounds reasonable. Is there an easy way to transform an unpartitioned table to one default partition?
> 


Should be something along the lines of:

```SQL
BEGIN;
ALTER TABLE _ps_trace.tag RENAME TO tag_default;
CREATE TABLE _ps_trace.tag
(
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    tag_type ps_trace.tag_type NOT NULL,
    key_id bigint NOT NULL,
    key ps_trace.tag_k NOT NULL REFERENCES _ps_trace.tag_key (key) ON DELETE CASCADE,
    value ps_trace.tag_v NOT NULL
)
PARTITION BY LIST (key);
CREATE UNIQUE INDEX tag_key_value_id_key_id_key_new ON _ps_trace.tag (key, _prom_ext.jsonb_digest(value)) INCLUDE (id, key_id);
ALTER TABLE _ps_trace.tag ATTACH PARTITION _ps_trace.tag_default DEFAULT;
END;
```

**Comment by sumerman** [comment]
> The only hesitation I have about the plan to use a default partition and move hot tag keys, is that I don't know of a fast transactional way to create a new partition and migrate rows, but maybe y'all do?

I don't think there is one if we want to enforce uniqueness constraints, but it's better than not having an option to deal with hot keys. And if we automate it, I expect it to kick in before the amount of data is overwhelming.

**Comment by jgpruitt** [comment]
the fastest way i can think to do it is

1. create a new table `like` the tag table with no indexes as a detached partition
2. copy the rows we want to move into the new table
3. add the indexes/constraints to the new table
4. start a transaction
5. delete the rows from the original table that were copied
6. copy/delete any that were missed
7. attach the new table as a partition
8. commit

something along those lines

**Comment by sumerman** [comment]
> the fastest way i can think to do it is
> 
> 1. create a new table `like` the tag table with no indexes as a detached partition
> 2. copy the rows we want to move into the new table
> 3. add the indexes/constraints to the new table
> 4. start a transaction
> 5. delete the rows from the original table that were copied
> 6. copy/delete any that were missed
> 7. attach the new table as a partition
> 8. commit
> 
> something along those lines

Upon the `ATTACH PARTITION` statement the default partition needs to be scanned to re-check new partitioning conditions. We’ll either need to find a way to circumvent it or keep the default partition small enough.
