### ISSUE TITLE
promscale cli options documentation

### ISSUE THREAD

**Issue by franck102** [timescale/promscale#750]
The documentation really could be more explicit about what the "migrate" option does especially when used along with 
"install-extensions" or "upgrade-extensions".

The FAQ states that:
"you could run the Promscale with the -migrate=only flag using a superuser which will install the update the schema and install the necessary extensions and quit"... is that the case?

The CLI documentation for "migrate" only mentions upgrading the SQL schema, it doesn't mention extensions?
If we run with
-install-extensions=true -upgrade-extension=true -migrate=only

will promscale install or upgrade extensions, migrate, then exit? Or will it just try to migrate and fail if an extension is missing / the wrong version?

**Comment by VineethReddy02** [comment]
closing this issue, as it's no more relevant with the current state of Promscale. Here are the[ latest docs](https://docs.timescale.com/promscale/latest/cli/) of Promscale CLI
