### ISSUE TITLE
Make error unknown linodego revision v1.0.0

### ISSUE THREAD

**Issue by Joezczhang** [timescale/promscale#764]
Hello:

when I make this project, there is a problem I can't solve just like below, please help me.
what I am certain is linodego does not have version1.0.0 in https://github.com/linode/linodego
Now how to fix it?

go build -o dist/promscale ./cmd/promscale
go: github.com/prometheus/prometheus@v1.8.2-0.20210605142932-7bc11dcb0664 requires
        github.com/linode/linodego@v1.0.0: reading github.com/linode/linodego/go.mod at revision v1.0.0: unknown revision v1.0.0
make: *** [build] Error 1

**Comment by ramonguiu** [comment]
@Joezczhang thanks for reporting this issue. Is there a particular reason you are building Promscale manually instead of downloading the containers or binaries we provide? For which processor architecture are you building it?

**Comment by Joezczhang** [comment]
@ramonguiu I want to build a rpm package with PostgreSQL, extension pg_prometheus version is , extension timescales, promscale in docker.So I want to build by myself.Is there any suggestion.

**Comment by niksajakovljevic** [comment]
So apparently https://github.com/linode/linodego version `v1.0.0` was removed from Github. However, it is still cached in https://proxy.golang.org/. 
So there are two ways to make it work.
1. Configure `export GOPROXY="https://proxy.golang.org,direct"`
OR
2. Explicitly exclude `linodego` by adding following to Promscale `go.mod` : `exclude github.com/linode/linodego v1.0.0`.

Hope this helps.

**Comment by Harkishen-Singh** [comment]
I tried your command and it worked for me. Not sure but maybe try `go mod tidy` and then rerun the above command.

Also, please close the issue if this is resolved.
