### ISSUE TITLE
Ability to downgrade promscale version

### ISSUE THREAD

**Issue by Harkishen-Singh** [timescale/promscale#769]
Sometimes version upgrades mess up things (when someone messes with default schema). This can also be with some version of Promscale not compatible with Timescaledb. Promscale should reverse the changes and allow downgrades.

Further, a check can be added before migrating, to make sure that it's possible to do a migration, otherwise don't migrate and complain in logs.

An example of this can be adding/dropping a constraint from a table. If the constrain exists, only then move ahead.

**Comment by ramonguiu** [comment]
@cevian didn't you add automatic rollback in case the automated upgrade process fails?

**Comment by ramonguiu** [comment]
I've confirmed we're automatically rolling back if database migrations fail.
