### ISSUE TITLE
Document various ways to delete data

### ISSUE THREAD

**Issue by Atomicbeast101** [timescale/promscale#86]
Prometheus offers an option to delete some metrics via their API, however that doesn't impact any data through remote read/write. Is there a way for me to delete metrics through PostgreSQL? 

I could not find any documentation on how to do this. Perhaps a section in the design document or Wiki to show how to do metric deletions would be beneficial?

**Comment by akulkarni** [comment]
Yes, there are two ways to delete metrics through PostgreSQL/TimescaleDB:

- Manually delete data older than (or newer than) a specified time: https://docs.timescale.com/latest/api#drop_chunks

- Add a new data retention policy: https://docs.timescale.com/latest/api#add_drop_chunks_policy

I agree re: better documentation. Might be best in this repo. Will chat with the team. Thanks!

**Comment by akulkarni** [comment]
Related: Would you prefer the ability to delete metrics via the Connector directly (eg REST API)?

(See #90)

**Comment by Atomicbeast101** [comment]
Ability to do it via REST API would probably be beneficial as Prometheus has this feature too.

**Comment by cevian** [comment]
Split off the API endpoint request separate. 

This issue will remain for documentation. We should document:
- how to delete a metric
- how to delete a metric by time (drop_chunks)
- how to schedule data retention
- how to delete a series (one and multiple)

**Comment by cevian** [comment]
The rest API is implemented by #326
