### ISSUE TITLE
[prom-migrator] Add option to wait after push

### ISSUE THREAD

**Issue by mjf** [timescale/promscale#880]
To slow the ingestion down under some circumstances, please add `--wait-after-push <ms>`.
Also consider adding `--wait-before-pull <ms>` for the same reason. Thank you.

**Comment by VineethReddy02** [comment]
closing this issue, as we haven’t received multiple requests from users for this feature and it's quite stale! :)

If you still have a need for this, Please open a new issue.

Thanks!
