### ISSUE TITLE
[prom-migrator] Add ETA indicator to the log output

### ISSUE THREAD

**Issue by mjf** [timescale/promscale#881]
Add ETA indicator to the `prom-migrator`'s log output. All needed calculation parameters for at least basic ETA indicator are IMHO known to the tool when running or can be easily measured (i.e. average time for single pull/push loop etc). ETA could also be preserved across `prom-migrator`'s restarts if progress metric and migration name are in use... Thank you.

**Comment by VineethReddy02** [comment]
closing this issue, as we haven’t received multiple requests from users for this feature and it's quite stale! :)

If you still have a need for this, Please open a new issue.

Thanks!
