### ISSUE TITLE
Turn on tracing functionality with separate cli flag

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/promscale#889]
We would like to have a cli flag to enable experimental features (such as tracing support), e.g. `--enable-feature=tracing`. The command documentation for this flag should indicate that the features are beta functionality and do not have a stable API.

Setting associated configuration values for the feature (such as `-otlp-grpc-server-listen-address`) should fail if the feature is not enabled.

Aside: This flag _will not_ have an impact on the schemas which promscale installs into the database.

**Comment by paulfantom** [comment]
I like the idea! One nit though, to make it super clear to the end-user that the feature is not stable yet, imho the flag should contain some notion of experimentality in the name. Something like `--enable-experimental-tracing` or `--enable-beta-tracing`, etc. We could even be future proof and implement it as `--enable-experimental=tracing` and allow multiple `--enable-experimental` flags.

**Comment by cevian** [comment]
The prometheus flag convention would be `--enable-feature=tracing` https://prometheus.io/docs/prometheus/latest/feature_flags/ I think we should use that convention

**Comment by JamesGuthrie** [comment]
Thanks for the feedback, I've taken it into account in the description above.
