### ISSUE TITLE
Product Feedback Wanted: CLI or REST API for setting data retention period?

### ISSUE THREAD

**Issue by akulkarni** [timescale/promscale#90]
Currently, setting a default data retention period requires executing a SQL command, e.g.,:

`SELECT set_default_retention_period(180 * INTERVAL '1 day')`

As a user, would you prefer to set this via a CLI or REST API instead?

Welcome any comments.

**Comment by VineethReddy02** [comment]
CLI seems to be a better approach. In future, if the configuration flags grow. We can add an option to provide a config file. This will help in passing all config using a single file.  (This approach needs a restart of connector for modifying retention period.)

REST API has its downside i.e. we never know what is the retention period if it's set/updated using the REST API.

**Comment by ksten-ab** [comment]
I agree generally with the CLI approach; in particular it would be nice for it to just be a setting in the Helm Chart that gets read by the Connector and initialized/reset during startup in the same way that migrations currently are run.
