### ISSUE TITLE
query with regex flag to ignore case does not work and produces an error

### ISSUE THREAD

**Issue by huzlak** [timescale/promscale#920]
Running a query via prometheus GUI with promscale as a remote_read endpoint does not provide results from timescale if I use regex flag to ignore case sensitivity. It also produces an error in promscale logs:

- Query exmaple: ```netrounds_delay_ms{source=~"((?i)(a)).*"}```
- Error message produced: ```level=warn ts=2021-11-25T12:35:29.036Z caller=read.go:70 msg="Error executing query" query="unsupported value type" storage=PostgreSQL err="appending sample rows: ERROR: invalid regular expression: quantifier operand invalid (SQLSTATE 2201B)" ```

I get data from prometheus TSDB, but not from timescale with such regex.

Any help appreciated

**Comment by VineethReddy02** [comment]
As this needs investigation, re-thinking on different regex systems between Go and PostgreSQL. Moving this issue to backlog will be picked in our backlog grooming.
