### ISSUE TITLE
Memory leak with querier rows

### ISSUE THREAD

**Issue by knrafto** [timescale/promscale#933]
Hello,

We're running Promscale 0.6.2 and lately we've been having memory issues. Normally promscale uses about 7GiB, but suddenly it started to increase its memory usage over the course of 4.5 hours to about 65GiB before OOMing. Unfortunately we don't have graphs for promscale's memory usage directly, but we do have monitoring for the node's memory usage (there's about 15GiB memory used by other stuff on the node):

![Node memory usage](https://user-images.githubusercontent.com/2042019/144107161-aeb7404a-779d-45ac-9888-83b5a47cfa04.png)

I managed to take a heap profile before it died (SVG attached). Most of the allocation seems to be from the two `sync.Pool`s in `pkg/pgmodel/querier/row.go`. I don't think the traffic was unusual or causing linearly increasing amount of work, so this smells like a memory leak to me. Do you know what the issue could be, or if there's anything we could do to mitigate?

Thank you!

[profile001.svg.gz](https://github.com/timescale/promscale/files/7627965/profile001.svg.gz)

**Comment by cevian** [comment]
Thanks @knrafto for the detailed bug report. I've opened a PR to resolve the issue.

**Comment by knrafto** [comment]
Thanks for the quick fix!

Sorry I'm not too familiar with promscale (or `sync.Pool`) but I'm trying to learn. Can you explain what the issue was? I thought that forgetting to `Put()` and item back into the `sync.Pool` would defeat the purpose but would be ultimately harmless, since the item would get GC'ed after whatever's holding it goes out of scope (in this case when the `querier` goes out of scope at the end of the query). Is there another reference to the rows somewhere?

**Comment by cevian** [comment]
I believe that sync.Pool keeps a reference to all items given out and not returned, which prevents the GC from collecting them.
