### ISSUE TITLE
Helm: Support Istio application requirements (port names/labels)

### ISSUE THREAD

**Issue by bitwalker** [timescale/promscale#941]
Istio does not like when services do not have port names which follow a `<protocol>[-<suffix>]` scheme, e.g. `http-metrics`, `grpc-otel`. See [this page](https://istio.io/latest/docs/reference/config/analysis/ist0118/) for more information. We should make the port name configureable via chart values, or simply follow that convention if there aren't any other conflicting conventions that may need to be adhered to.

I have encountered issues in the past with Istio when services do not follow this scheme, so I would consider it relatively important to support this. Istio also requires the `app` and `version` labels on pods, and uses custom annotations for various purposes - so we should probably also make sure the former are set, and allow for providing custom labels/annotations on deployment resources.

The full requirements for Istio-based applications are outlined [here](https://istio.io/latest/docs/ops/deployment/requirements/).

**Comment by paulfantom** [comment]
I was always wondering why istio is such a pain. With those requirements now I know.

---

Regarding port names, we can hardcode and change them `<protocol>[-<suffix>]` schema. I don't want to expose port name change capability to end-user as it only clouds UX and moves responsibility

Regarding `app` and `version` labels. I wonder why istio cannot use [kubernetes recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) :facepalm: But that's a question for istio and I think we can ship both sets for now.

As for annotations, we might want to improve that part, but I don't have anything up my sleeve yet and putting `annotations` as top level section in `values.yaml` looks awful, especially considering we have `prometheus.annotations`.

**Comment by bitwalker** [comment]
Of the various service meshes, Istio is definitely one of the better options, and is probably the most common, or at least, best supported (e.g. GKE supports Istio-enabled clusters out of the box). One of its big benefits is an enormous amount of visibility into, and control over, network traffic in a cluster - so I suspect that amongst our target demographic, it'll be pretty common.

> Regarding port names, we can hardcode and change them <protocol>[-<suffix>] schema. I don't want to expose port name change capability to end-user as it only clouds UX and moves responsibility

I think that's probably fine, but as an end user of Helm charts myself, I generally prefer that charts set sane defaults and then let me override things that the chart itself doesn't/shouldn't necessarily care about (e.g. labels/annotations). Port names are something that can be made variable without imposing any constraints on the chart, so I don't think it presents any additional UX burden on users who don't care, nor MX burden on us - but as I mentioned, I think your proposed solution is good enough until there are specific requests for more flexibility.

> Regarding app and version labels. I wonder why istio cannot use kubernetes recommended labels 🤦 But that's a question for istio and I think we can ship both sets for now.

Istio predates those conventions by quit some time, and in general, for a very long time, `app` and `version` were conventional, so they are very commonly used still to this day. In any case, I definitely agree that they should switch to preferring those instead, since they are far more common now, and it is a [tracked issue](https://github.com/istio/istio/issues/10724) at least. That said, we can probably skip setting these ourselves, and instead simply provide facilities for setting custom labels/annotations on the service/deployment resources, as discussed below.

> As for annotations, we might want to improve that part, but I don't have anything up my sleeve yet and putting annotations as top level section in values.yaml looks awful, especially considering we have prometheus.annotations.

I would recommend providing `deployment.labels` and `deployment.annotations` at least, to match `service.annotations` (and I'd add `service.labels` to keep them matched). Speaking from the perspective of a cluster admin, I would flat-out reject any chart that didn't give me at least that much control over the resources being created, as both labels and annotations are commonly used for all manner of different purposes. The inability to set them would force users to maintain a fork of our chart if they want to customize things like that, which is a huge pain for something so trivial. There are a number of conventions for surfacing custom labels/annotations in Helm charts, and I've never really cared which one is actually followed, as long as I have the means to provide them _somehow.

**Comment by paulfantom** [comment]
> Of the various service meshes, Istio is definitely one of the better options, and is probably the most common, or at least, best supported

Everyone can have their own opinion on this matter. Personally, I am more of linkerd fan than istio.

> One of its big benefits is an enormous amount of visibility into, and control over, network traffic in a cluster - so I suspect that amongst our target demographic, it'll be pretty common.

That's a generic thing for service meshes, not only for istio. Either way we don't have any reports of people using istio and promscale. So this is all a guessing game.

> Istio predates those conventions by quite some time, 

Software is meant to evolve :) 

> instead simply provide facilities for setting custom labels/annotations on the service/deployment resources

I am fine with this as long as those are additional labels and annotations. We still need to ensure label selectors on the Service object have something to match from pods managed by a Deployment (currently it is the `app` label).
