### ISSUE TITLE
Is there best practice for distributed large-scale cluster with promscale as connector?

### ISSUE THREAD

**Issue by oleotiger** [timescale/promscale#951]
I wanna to deploy netdata in a large-scale cluster with over 100 nodes and all of them collect metrics in 1s granularity. The collected data are posted to a cloud database.

**What’s the problem?**
I have found a solution. All netdata agents export data with remote-prometheus-write. I select promscale as connector and timescaledb as backend database.

As there are over 100 nodes in the cluster, there may be large data flow. I wonder **how many agents one single promscale instance can handle?**

100 agents → 1 single promscale instance → database ?
100 agents → 100 promscale instances(each for a agent) → database?

Is redis/rabbitmq needed for cache between promscale and database?

**Comment by VineethReddy02** [comment]
Can you share the details on data being exported from your netdata agents: 
1. Number of active series?
2. Number of samples per second?

**Comment by niksajakovljevic** [comment]
I'd recommend starting with 100 agents -> 1 promscale instance and see how it goes. Promscale connector is usually not a bottleneck as it's only in memory. You don't need redis/rabbitmq.

**Comment by VineethReddy02** [comment]
@oleotiger Do you need any more details on this?

**Comment by VineethReddy02** [comment]
@oleotiger closing this issue, as relevant details are answered in the previous comments. Feel free to re-open the issue if you still feel your question is unanswered.
