### ISSUE TITLE
Automate Helm chart publishing

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/promscale#972]
Currently helm charts are manually published by @cevian. We would like to have this automated so that they are published during the release build process.

**Comment by paulfantom** [comment]
This will first need to have a helm CI pipeline in place so we can test that the released chart is correct. Done in https://github.com/timescale/promscale/pull/957.

**Comment by paulfantom** [comment]
Done with https://github.com/timescale/promscale/pull/1030 and https://github.com/timescale/promscale/pull/1055
