### ISSUE TITLE
Investigate why buffers clean by backend is high

### ISSUE THREAD

**Issue by ramonguiu** [timescale/promscale#976]

**Comment by niksajakovljevic** [comment]
<img width="500" alt="Screenshot 2021-12-17 at 10 31 24" src="https://user-images.githubusercontent.com/3705942/146524237-140e6b2a-7cbb-4db9-9d81-aec08f0b66dd.png">
<img width="428" alt="Screenshot 2021-12-17 at 10 31 07" src="https://user-images.githubusercontent.com/3705942/146524241-d89aafc6-5c84-4503-aa32-f5a26610562a.png">
<img width="516" alt="Screenshot 2021-12-17 at 10 30 57" src="https://user-images.githubusercontent.com/3705942/146524243-257eecd4-c728-48a5-8582-5e2852d93a67.png">
<img width="488" alt="Screenshot 2021-12-17 at 10 29 49" src="https://user-images.githubusercontent.com/3705942/146524246-256d2763-e0eb-44e5-935f-10c4bd8dda3d.png">
<img width="497" alt="Screenshot 2021-12-17 at 10 29 38" src="https://user-images.githubusercontent.com/3705942/146524250-66cd47be-3945-40b7-a071-941fde0d64c8.png">


It seems that covering B-tree index on metric hypertables is messing with PostgreSQL shared buffers. Indexes are basically almost the same size as tables - and they can't all easily fit into shared buffers. While ingesting PostgreSQL needs to maintain the index and constantly loading such a large indexes into shared buffers means that pages of data are quickly moving in and out and that reduces the efficiency of background workers and chekpointing. 
The charts are showing metrics with covering B-tree indexes (on the left) and without indexes on the right. It'e easy to spot that huge difference in shared buffers cleaned by backend between these two benchmarks. Cleaning shared buffers with backend processes is the least efficient way so it reduces the overall throughput.

**Comment by niksajakovljevic** [comment]
The takeaway here is that if we make indexes smaller we will not overload the shared buffers and that will alleviate the problem with shared buffers getting cleaned by the backend.

**Comment by ramonguiu** [comment]
What makes data volume read and written so spiky? Shouldn't they be fairly stable?

**Comment by niksajakovljevic** [comment]
Read and write spikes are mostly from inserts into covering B-tree index. Since it's huge it constantly needs to get loaded and written back as new data is inserted.

**Comment by niksajakovljevic** [comment]
Investigation work is completed and large indexes are to blame.
