### ISSUE TITLE
Provide sensible default for otlp-grpc-server-listen-address

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/promscale#984]
In order to enable tracing, users are expect to provide the following flags to promscale: `-enable-feature=tracing -otlp-grpc-server-listen-address=<some address>`.

In our helm charts we set `otlp-grpc-server-listen-address` to `:9202`, which could be considered to be the default.

It would make sense to just set the default value to `:9202`, that way it would only be necessary to provide `-enable-feature=tracing`.

**Comment by VineethReddy02** [comment]
closing this issue, as it's already fixed in master.
