### ISSUE TITLE
Prototype tagging operators using custom type for tag_map 

### ISSUE THREAD

**Issue by jgpruitt** [timescale/promscale#990]
Currently, we are using a jsonb type to represent a tag_map. Prototype using a custom type to represent tag_maps and determine whether or not this improves the story with operators.

- [x] set up an extension project
- [x] figure out how to define a custom type for tagmap
- [x] figure out how to cast to/from jsonb and json
- [ ] figure out how to support GIN indexes on the custom type
- [ ] figure out how to define necessary support functions

**Comment by cevian** [comment]
Resolved in #1328
